INSERT INTO
    dbo.country("countryName")
VALUES
    ('Colombia');

INSERT INTO
    dbo.state("stateName", "CountryId")
VALUES
    ('Amazonas', 1),
    ('Antioquia', 1),
    ('Arauca', 1),
    ('Atlántico', 1),
    ('Bogotá', 1),
    ('Bolívar', 1),
    ('Boyacá', 1),
    ('Caldas', 1),
    ('Caquetá', 1),
    ('Casanare', 1),
    ('Cauca', 1),
    ('Cesar', 1),
    ('Chocó', 1),
    ('Córdoba', 1),
    ('Cundinamarca', 1),
    ('Guainía', 1),
    ('Guaviare', 1),
    ('Huila', 1),
    ('La Guajira', 1),
    ('Magdalena', 1),
    ('Meta', 1),
    ('Nariño', 1),
    ('Norte de Santander', 1),
    ('Putumayo', 1),
    ('Quindío', 1),
    ('Risaralda', 1),
    ('San Andrés y Providencia', 1),
    ('Santander', 1),
    ('Sucre', 1),
    ('Tolima', 1),
    ('Valle del Cauca', 1),
    ('Vaupés', 1),
    ('Vichada', 1);

INSERT INTO
    dbo.city("cityName", "stateId")
VALUES
    ('El Encanto', 1),
    ('La Chorrera', 1),
    ('La Pedrera', 1),
    ('La Victoria', 1),
    ('Leticia', 1),
    ('Miriti - Parana', 1),
    ('Puerto Arica', 1),
    ('Puerto Nariño', 1),
    ('Puerto Santander', 1),
    ('Tarapacá', 1),
    ('Bello', 2),
    ('Caldas', 2),
    ('Copacabana', 2),
    ('Envigado', 2),
    ('Guarne', 2),
    ('Itagüí', 2),
    ('La Estrella', 2),
    ('Medellín', 2),
    ('Rionegro', 2),
    ('Sabaneta', 2),
    ('Arauca', 3),
    ('Arauquita', 3),
    ('Cameguadua', 3),
    ('Cravo Norte', 3),
    ('Fortul', 3),
    ('La Esmeralda', 3),
    ('Puerto Rondón', 3),
    ('Puerto Nariño', 3),
    ('Saravena', 3),
    ('Tame', 3),
    ('Baranoa', 4),
    ('Barranquilla', 4),
    ('Campo de la Cruz', 4),
    ('Galapa', 4),
    ('Malambo', 4),
    ('Palmar de Varela', 4),
    ('Puerto Colombia', 4),
    ('Sabanalarga', 4),
    ('Santo Tomás', 4),
    ('Soledad', 4),
    ('Bogotá', 5),
    ('Arjona', 6),
    ('Cantagallo', 6),
    ('Cartagena', 6),
    ('El Carmen de Bolívar', 6),
    ('Magangué', 6),
    ('Mompox', 6),
    ('María la Baja', 6),
    ('San Jacinto', 6),
    ('San Juan Nepomuceno', 6),
    ('Turbaná', 6),
    ('Chiquinquirá', 7),
    ('Duitama', 7),
    ('Moniquirá', 7),
    ('Paipa', 7),
    ('Puerto Boyacá', 7),
    ('Sáchica', 7),
    ('Sogamoso', 7),
    ('Togüí', 7),
    ('Tunja', 7),
    ('Villa de Leyva', 7),
    ('Anserma', 8),
    ('Chinchiná', 8),
    ('La Dorada', 8),
    ('Manizales', 8),
    ('Neira', 8),
    ('Palestina', 8),
    ('Risaralda', 8),
    ('Samaná', 8),
    ('Supía', 8),
    ('Villamaría', 8),
    ('Belén de los Andaquíes', 9),
    ('Curillo', 9),
    ('El Paujil', 9),
    ('Florencia', 9),
    ('La Montañita', 9),
    ('Milán', 9),
    ('Morelia', 9),
    ('Puerto Rico', 9),
    ('San Vicente del Caguán', 9),
    ('Solano', 9),
    ('Aguazul', 10),
    ('Maní', 10),
    ('Monterrey', 10),
    ('Orocué', 10),
    ('Paz de Ariporo', 10),
    ('Tauramena', 10),
    ('Trinidad', 10),
    ('Villanueva', 10),
    ('Yopal', 10),
    ('Cajibío', 11),
    ('Corinto', 11),
    ('El Tambo', 11),
    ('Patía', 11),
    ('Piendamó', 11),
    ('Popayán', 11),
    ('Puerto Tejada', 11),
    ('Rosas', 11),
    ('Santander de Quilichao', 11),
    ('Timbío', 11),
    ('Valledupar', 12),
    ('Aguachica', 12),
    ('Bosconia', 12),
    ('La Jagua de Ibirico', 12),
    ('La Paz', 12),
    ('Pueblo Bello', 12),
    ('Gamarra', 12),
    ('Curumaní', 12),
    ('Chiriguaná', 12),
    ('San Diego', 12),
    ('Quibdó', 13),
    ('Istmina', 13),
    ('Lloró', 13),
    ('Medio Atrato', 13),
    ('Bagadó', 13),
    ('Condoto', 13),
    ('Tadó', 13),
    ('Unión Panamericana', 13),
    ('Riosucio', 13),
    ('Nóvita', 13),
    ('Montería', 14),
    ('Cereté', 14),
    ('Lorica', 14),
    ('Sahagún', 14),
    ('Montelíbano', 14),
    ('Planeta Rica', 14),
    ('Ayapel', 14),
    ('Chimá', 14),
    ('Tierralta', 14),
    ('Puerto Escondido', 14),
    ('Soacha', 15),
    ('Zipaquirá', 15),
    ('Funza', 15),
    ('Chía', 15),
    ('Mosquera', 15),
    ('Facatativá', 15),
    ('Girardot', 15),
    ('Madrid', 15),
    ('La Calera', 15),
    ('Inírida', 16),
    ('Barranco Minas', 16),
    ('Mapiripana', 16),
    ('San Felipe', 16),
    ('Puerto Colombia', 16),
    ('La Guadalupe', 16),
    ('Cacahual', 16),
    ('Morichal', 16),
    ('Pana Pana', 16),
    ('Carniceros', 16),
    ('San José del Guaviare', 17),
    ('El Retorno', 17),
    ('Miraflores', 17),
    ('Calamar', 17),
    ('La Lindosa', 17),
    ('Morichal Nuevo', 17),
    ('Pueblo Nuevo', 17),
    ('Puerto Colombia', 17),
    ('Barranquillita', 17),
    ('El Capricho', 17),
    ('Neiva', 18),
    ('Pitalito', 18),
    ('Garzón', 18),
    ('La Plata', 18),
    ('Campoalegre', 18),
    ('Palermo', 18),
    ('Baraya', 18),
    ('Timaná', 18),
    ('Aipe', 18),
    ('Acevedo', 18),
    ('Riohacha', 19),
    ('Maicao', 19),
    ('San Juan del Cesar', 19),
    ('Fonseca', 19),
    ('Villanueva', 19),
    ('Uribia', 19),
    ('Barrancas', 19),
    ('Distracción', 19),
    ('Hatonuevo', 19),
    ('La Jagua del Pilar', 19),
    ('Santa Marta', 20),
    ('Ciénaga', 20),
    ('Fundación', 20),
    ('Plato', 20),
    ('Aracataca', 20),
    ('Puebloviejo', 20),
    ('El Banco', 20),
    ('Zona Bananera', 20),
    ('Algarrobo', 20),
    ('Chivolo', 20),
    ('Villavicencio', 21),
    ('Acacías', 21),
    ('Granada', 21),
    ('Puerto Gaitán', 21),
    ('San Carlos de Guaroa', 21),
    ('Restrepo', 21),
    ('San Juan de Arama', 21),
    ('El Castillo', 21),
    ('Cumaral', 21),
    ('Puerto Concordia', 21),
    ('Pasto', 22),
    ('Tumaco', 22),
    ('Ipiales', 22),
    ('La Unión', 22),
    ('Chachagüí', 22),
    ('Samaniego', 22),
    ('Túquerres', 22),
    ('Buesaco', 22),
    ('Iles', 22),
    ('Policarpa', 22),
    ('Cúcuta', 23),
    ('Pamplona', 23),
    ('Ocaña', 23),
    ('Tibú', 23),
    ('Villa del Rosario', 23),
    ('Los Patios', 23),
    ('El Zulia', 23),
    ('Chinácota', 23),
    ('Chitagá', 23),
    ('Bochalema', 23),
    ('Mocoa', 24),
    ('Orito', 24),
    ('Puerto Asís', 24),
    ('Puerto Leguízamo', 24),
    ('Sibundoy', 24),
    ('San Miguel', 24),
    ('Colón', 24),
    ('Villagarzón', 24),
    ('San Francisco', 24),
    ('Valle del Guamuez', 24),
    ('Armenia', 25),
    ('Calarcá', 25),
    ('Circasia', 25),
    ('Montenegro', 25),
    ('La Tebaida', 25),
    ('Salento', 25),
    ('Pijao', 25),
    ('Genova', 25),
    ('Buenavista', 25),
    ('Quimbaya', 25),
    ('Pereira', 26),
    ('Dosquebradas', 26),
    ('Santa Rosa de Cabal', 26),
    ('La Virginia', 26),
    ('Santuario', 26),
    ('Apía', 26),
    ('Marsella', 26),
    ('Guática', 26),
    ('Quinchía', 26),
    ('Balboa', 26),
    ('San Andrés', 27),
    ('Providencia', 27),
    ('Bucaramanga', 28),
    ('Girón', 28),
    ('Floridablanca', 28),
    ('Piedecuesta', 28),
    ('Barbosa', 28),
    ('Sincelejo', 29),
    ('Corozal', 29),
    ('San Marcos', 29),
    ('Tolú', 29),
    ('Coveñas', 29),
    ('Ibagué', 30),
    ('Espinal', 30),
    ('Mariquita', 30),
    ('Purificación', 30),
    ('Líbano', 30),
    ('Cali', 31),
    ('Palmira', 31),
    ('Buenaventura', 31),
    ('Yumbo', 31),
    ('Tuluá', 31),
    ('Mitú', 32),
    ('Caruru', 32),
    ('Pacoa', 32),
    ('Taraira', 32),
    ('Papunaua', 32),
    ('Puerto Carreño', 33),
    ('La Primavera', 33),
    ('Santa Rosalía', 33),
    ('Cumaribo', 33),
    ('La Guadalupe', 33);

INSERT INTO
    dbo.gender("genderType")
VALUES
    ('Masculino'),
    ('Femenino'),
    ('Otro');

INSERT INTO
    dbo.ident_document("identDocName")
VALUES
    ('Cédula de ciudadanía'),
    ('Cédula de extranjería'),
    ('Pasaporte');

INSERT INTO
    [tudata].[dbo].[plan]("planName", "planTopics", "iconpath")
VALUES
    (
        'Control',
        'Este plan te permitirá bloquear tres entidades empresariales sin ningún costo.',
        'plans/tudatacontrol.png'
    ),
    (
        'Plus',
        'Este plan te permitirá bloquear un número limitado de entidades empresariales y autorizar mínimo cinco entidades.',
        'plans/tudataplus.png'
    ),
    (
        'Premium',
        'Podrás bloquear y autorizar tantas entidades como quieras y tendrás la opción para adicionar tus intereses de forma personalizada.',
        'plans/tudatapremium.png'
    );

INSERT INTO
    [dbo].[reward_currency] (
        [rewardCurrencyValue],
        [rewardCurrencyActive],
        [planId]
    )
VALUES
    (0, 1, 1),
    (500, 1, 2),
    (800, 1, 3);

INSERT INTO
    dbo.requirement("requirementName")
VALUES
    ('Derecho de petición'),
    ('Recurso de reposición'),
    ('Tutela'),
    ('Queja ante SIC');

INSERT INTO
    [dbo].[role]([roleName])
VALUES
    ('CONTROL'),
    ('PLUS'),
    ('PREMIUM'),
    ('ABOGADO'),
    ('OPERATIVO'),
    ('ADMINISTRATIVO'),
    ('BUYER');

INSERT INTO
    [dbo].[database_type] ([databaseType])
VALUES
    ('Simple'),
    ('Especializada');

INSERT INTO
    [dbo].[status]([statusName])
VALUES
    ('Pendiente'),
    ('Finalizado'),
    ('Rechazado'),
    ('Revisión');

INSERT INTO
    [dbo].[pqr] ([pqrsName])
VALUES
    ('Petición'),
    ('Queja'),
    ('Reclamo'),
    ('Sugerencia'),
    ('Felicitación'),
    ('Registrar Empresa'),
    ('Pago Bloqueo'),
    ('Pago Compra'),
    ('Respuesta Bloqueo'),
    ('Contacto no Autorizado'),
    ('Eliminar Cuenta'),
    ('Eliminar Datos');

INSERT INTO
    dbo.company(
        companyId,
        companyBussinesName,
        companyComertialName,
        companyNit,
        companyPhone,
        companyEmail,
        companyLogoPath,
        cityId,
        directRemitent
    )
VALUES
    (
        '8450f246-41cf-4fef-81ac-d3727c33e3c1',
        'Vecino SAS',
        'Tiendas vecino',
        '123456790',
        '3215988968',
        'shisho253@yahoo.com',
        'logos/123456790/logo.png',
        1,
        1
    ),
    (
        '6c75433e-f36b-1410-81c2-009e18c9ad57',
        'Banco De Bogota',
        'Banco De Bogota',
        '860002964',
        '3213113703',
        'contacto@BancoBogota.com',
        'logos/860002964/logo.png',
        1,
        0
    ),
    (
        '7275433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Bilbao Vizcaya Argentaria Colombia S A',
        'Banco BBVA',
        '860003020',
        '3015008106',
        'contacto@BBVA.com',
        'logos/860003020/logo.png',
        1,
        0
    ),
    (
        '7875433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Caja Social Sa',
        'Banco Caja Social',
        '860007335',
        '3212740388',
        'contacto@BCSC.com',
        'logos/860007335/logo.png',
        1,
        0
    ),
    (
        '7e75433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Popular S A',
        'Banco Popular',
        '860007738',
        '3132341167',
        'contacto@BancoPopular.com',
        'logos/860007738/logo.png',
        1,
        0
    ),
    (
        '8475433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Davivienda S A',
        'Banco Davivienda',
        '860034313',
        '3224634591',
        'contacto@Davivienda.com',
        'logos/860034313/logo.png',
        1,
        0
    ),
    (
        '8a75433e-f36b-1410-81c2-009e18c9ad57',
        'Scotiabank Colpatria S.A',
        'Banco Colpatria',
        '860034594',
        '3126432686',
        'contacto@Colpatria.com',
        'logos/860034594/logo.png',
        1,
        0
    ),
    (
        '9075433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Comercial Av Villas S A',
        'Banco Av Villas',
        '860035827',
        '3184803353',
        'contacto@AvVillas.com',
        'logos/860035827/logo.png',
        1,
        0
    ),
    (
        '9675433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Gnb Sudameris S A',
        'Banco Gnb Sudameris',
        '860050750',
        '3015822316',
        'contacto@BancoSudameris.com',
        'logos/860050750/logo.png',
        1,
        0
    ),
    (
        '9c75433e-f36b-1410-81c2-009e18c9ad57',
        'Citibank Colombia S A',
        'Citibank',
        '860051135',
        '3196742139',
        'contacto@Citibank.com',
        'logos/860051135/logo.png',
        1,
        0
    ),
    (
        'a275433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Pichincha S A',
        'Banco Pichincha',
        '890200756',
        '3065266782',
        'contacto@BancoPichincha.com',
        'logos/890200756/logo.png',
        1,
        0
    ),
    (
        'a875433e-f36b-1410-81c2-009e18c9ad57',
        'Itau Corpbanca Colombia Sa',
        'Banco Itau',
        '890903937',
        '3113275948',
        'contacto@BancoItau.com',
        'logos/890903937/logo.png',
        1,
        0
    ),
    (
        'ae75433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Falabella S A',
        'Banco Falabella',
        '900047981',
        '3283156049',
        'contacto@BancoFalabella.com',
        'logos/900047981/logo.png',
        1,
        0
    ),
    (
        'b475433e-f36b-1410-81c2-009e18c9ad57',
        'CENCOSUD COLOMBIA S.A',
        'Tiendas Metro',
        '900155107',
        '3206999786',
        'Servicio.al.Cliente@cencosud.com.co',
        'logos/900155107/logo.png',
        1,
        1
    ),
    (
        'ba75433e-f36b-1410-81c2-009e18c9ad57',
        'D1 SAS',
        'Tiendas D1',
        '900276962',
        '3026416977',
        'contacto@D1.com',
        'logos/900276962/logo.png',
        1,
        1
    ),
    (
        'c075433e-f36b-1410-81c2-009e18c9ad57',
        'Virgin Mobile Colombia Sas',
        'Virgin Mobile',
        '900420122',
        '3175157243',
        'contacto@VirginMobile.com',
        'logos/900420122/logo.png',
        1,
        1
    ),
    (
        'c675433e-f36b-1410-81c2-009e18c9ad57',
        'Wom Colombia Sas',
        'Wom',
        '900424796',
        '3136456382',
        'contacto@Wom.com',
        'logos/900424796/logo.png',
        1,
        1
    ),
    (
        'cc75433e-f36b-1410-81c2-009e18c9ad57',
        'Ara Colombia Sas',
        'Tiendas Ara',
        '900618429',
        '3225857809',
        'contacto@Ara.com',
        'logos/900618429/logo.png',
        1,
        1
    ),
    (
        'd275433e-f36b-1410-81c2-009e18c9ad57',
        'Movii S A',
        'Movii',
        '901077952',
        '3238874965',
        'contacto@Movii.com',
        'logos/901077952/logo.png',
        1,
        1
    ),
    (
        'd875433e-f36b-1410-81c2-009e18c9ad57',
        'Lulo Bank S A',
        'Lulo Bank',
        '901383474',
        '3266438993',
        'contacto@LuloBank.com',
        'logos/901383474/logo.png',
        1,
        0
    ),
    (
        'de75433e-f36b-1410-81c2-009e18c9ad57',
        'Nequi S A Compania De Financiamiento',
        'Nequi',
        '901633276',
        '3207040104',
        'contacto@Nequi.com',
        'logos/901633276/logo.png',
        1,
        0
    ),
    (
        'e475433e-f36b-1410-81c2-009e18c9ad57',
        'Claro Ltda',
        'Claro',
        '805014822',
        '3044266250',
        'contacto@Claro.com',
        'logos/805014822/logo.png',
        1,
        0
    ),
    (
        'ea75433e-f36b-1410-81c2-009e18c9ad57',
        'Banco De Occidente',
        'Banco De Occidente',
        '890300279',
        '3018756957',
        'contacto@BancodeOccidente.com',
        'logos/890300279/logo.png',
        1,
        0
    ),
    (
        'f075433e-f36b-1410-81c2-009e18c9ad57',
        'Almacenes Exito S.a.',
        'Supermercado Exito',
        '890900608',
        '3206295989',
        'contacto@exito.com',
        'logos/890900608/logo.png',
        1,
        1
    ),
    (
        'f675433e-f36b-1410-81c2-009e18c9ad57',
        'Bancolombia S A',
        'Bancolombia',
        '890903938',
        '3254255760',
        'contacto@Bancolombia.com',
        'logos/890903938/logo.png',
        1,
        0
    ),
    (
        'fc75433e-f36b-1410-81c2-009e18c9ad57',
        'UNE EPM Telecomunicaciones S.A',
        'UNE',
        '900092385',
        '3034190315',
        'contacto@Tigo.com',
        'logos/900092385/logo.png',
        1,
        1
    ),
    (
        '0276433e-f36b-1410-81c2-009e18c9ad57',
        'Banco Mundo Mujer Sa O Mundo Mujer El Banco De La Comunidad O Mundo Mujer',
        'Banco Mundo Mujer',
        '900768933',
        '3258700724',
        'contacto@BancoMundoMujer.com',
        'logos/900768933/logo.png',
        1,
        0
    ),
    (
        '0876433e-f36b-1410-81c2-009e18c9ad57',
        'Empresa De Telecomunicaciones De Bogotá S.A. E.S.P.',
        'ETB',
        '899999115',
        '3285012225',
        'asuntos.contenciosos@etb.com.co',
        'logos/899999115/logo.png',
        1,
        1
    ),
    (
        '0e76433e-f36b-1410-81c2-009e18c9ad57',
        'Colombia Telecomunicaciones S.A. ESP',
        'Teléfonica Movistar',
        '830122566',
        '3216051674',
        'notificacionesjudiciales@telefonica.com',
        'logos/830122566/logo.png',
        1,
        1
    ),
    (
        '1476433e-f36b-1410-81c2-009e18c9ad57',
        'Royal Films S.A.S',
        'Royal Films',
        '890105652',
        '3172774304',
        'protecciondatos@royal-films.com',
        'logos/890105652/logo.png',
        1,
        1
    ),
    (
        '1a76433e-f36b-1410-81c2-009e18c9ad57',
        'Red Empresarial de Servicios S.A',
        'Supergiros',
        '900084777',
        '3294288882',
        'servicioalcliente@supergiros.com.co',
        'logos/900084777/logo.png',
        1,
        1
    );

INSERT INTO
    dbo.buyer (
        buyerId,
        buyerRUTPath,
        buyerAddress,
        buyerLegalRepresentative,
        buyerContactName,
        buyerActive,
        buyerRepresentativeIdNum,
        companyId,
        buyerRepresentativeIdType
    )
VALUES
    (
        '70FF423E-F36B-1410-86B4-00CBB56CB138',
        'RUT',
        'Calle falsa 123',
        'Pingüina',
        'Caballo',
        1,
        '1026563730',
        '8450f246-41cf-4fef-81ac-d3727c33e3c1',
        1
    ),
    (
        '321088ce-3276-4b31-87d5-dd3770a29a37',
        'RUT_Movistar',
        'Calle falsa 12345',
        'El dueño',
        'El asignado',
        1,
        '1073924878',
        '0e76433e-f36b-1410-81c2-009e18c9ad57',
        1
    );

INSERT INTO
    dbo.category("categoryName", "iconpath")
VALUES
    ('Economía', 'categories/icon_economia.png'),
    ('Hogar', 'categories/icon_hogar.svg'),
    (
        'Entretenimiento',
        'categories/icon_entretenimiento.png'
    ),
    ('Ocupación', 'categories/icon_ocupacion.png'),
    ('Gastronomía', 'categories/icon_gastronomia.png'),
    ('Tecnología', 'categories/icon_tecnologia.png');

INSERT INTO
    dbo.buyer_credential (
        buyerCredentialId,
        buyerCredentialEmail,
        buyerCredentialPass,
        buyerCredentialsEnabled,
        buyerCredentialVerified,
        buyerId
    )
VALUES
    (
        '72FF423E-F36B-1410-86B4-00CBB56CB138',
        'shisho253@yahoo.com',
        'Pass123*',
        1,
        1,
        '70FF423E-F36B-1410-86B4-00CBB56CB138'
    ),
    (
        'c181dc5a-9d04-405a-8001-b986c36b553c',
        'notificacionesjudiciales@telefonica.com',
        'Pass123*',
        1,
        1,
        '321088ce-3276-4b31-87d5-dd3770a29a37'
    );

INSERT INTO
    dbo.subcategory("subcategoryName", "iconpath", "categoryId")
VALUES
    (
        'Finanzas personales',
        'subcategories/icon_finanzas-personales.svg',
        1
    ),
    (
        'Inversiones',
        'subcategories/icon_inversiones.svg',
        1
    ),
    (
        'Mercados financieros',
        'subcategories/icon_mercados-financieros.svg',
        1
    ),
    (
        'Economía global',
        'subcategories/icon_economia-global.svg',
        1
    ),
    (
        'Decoración',
        'subcategories/icon_decoracion.svg',
        2
    ),
    (
        'Organización',
        'subcategories/icon_organizacion.svg',
        2
    ),
    (
        'Mantenimiento',
        'subcategories/icon_mantenimiento.svg',
        2
    ),
    (
        'Jardinería',
        'subcategories/icon_jardineria.svg',
        2
    ),
    ('Deportes', 'subcategories/icon_deportes.svg', 3),
    ('Música', 'subcategories/icon_musica.svg', 3),
    ('Viajes', 'subcategories/icon_viajes.svg', 3),
    ('Moda', 'subcategories/icon_moda.svg', 3),
    (
        'Literatura',
        'subcategories/icon_literatura.svg',
        3
    ),
    (
        'Cine y TV',
        'subcategories/icon_cine-y-tv.svg',
        3
    ),
    ('Mascotas', 'subcategories/icon_mascotas.svg', 3),
    (
        'Redes sociales',
        'subcategories/icon_redes-sociales.svg',
        3
    ),
    (
        'Carreras profesionales',
        'subcategories/icon_carreras-profesionales.svg',
        4
    ),
    (
        'Habilidades laborales',
        'subcategories/icon_habilidades-laborales.svg',
        4
    ),
    (
        'Emprendimiento',
        'subcategories/icon_emprendimiento.svg',
        4
    ),
    (
        'Búsqueda de empleo',
        'subcategories/icon_busqueda-de-empleo.svg',
        4
    ),
    (
        'Cocina internacional',
        'subcategories/icon_cocina-internacional.svg',
        5
    ),
    (
        'Recetas saludables',
        'subcategories/icon_recetas-saludables.svg',
        5
    ),
    ('Postres', 'subcategories/icon_postres.svg', 5),
    ('Bebidas', 'subcategories/icon_bebidas.svg', 5),
    (
        'Dispositivos electrónicos',
        'subcategories/icon_dispositivos-electronicos.svg',
        6
    ),
    (
        'Internet y redes',
        'subcategories/icon_internet-y-redes.svg',
        6
    ),
    (
        'Aplicaciones móviles',
        'subcategories/icon_aplicaciones-moviles.svg',
        6
    ),
    (
        'Programación y desarrollo',
        'subcategories/icon_programacion-y-desarrollo.svg',
        6
    );

INSERT INTO
    dbo.element("elementName", "subCategoryId")
VALUES
    ('Ahorro de emergencia', 1),
    ('Planificación para jubilación', 1),
    ('Fondos para educación', 1),
    ('Seguro de vida', 1),
    ('Seguro de salud', 1),
    ('Planificación patrimonial', 1),
    ('Impuestos personales', 1),
    ('Compra de vivienda', 1),
    ('Compra de automóvil', 1),
    ('Ahorro para vacaciones', 1),
    ('Ahorro para viajes', 1),
    ('Control de gastos', 1),
    ('Metas financieras a corto plazo', 1),
    ('Metas financieras a largo plazo', 1),
    ('Ingresos pasivos', 1),
    ('Aumentar ingresos', 1),
    ('Ahorro para proyectos personales', 1),
    ('Deudas', 1),
    ('Acciones de empresas tecnológicas', 2),
    ('Bonos del gobierno', 2),
    ('Fondos mutuos', 2),
    ('Fondos de índice', 2),
    ('Cuentas de ahorro con intereses altos', 2),
    ('Certificados de depósito', 2),
    ('Inversiones en bienes raíces', 2),
    ('Materias primas', 2),
    ('Crowdfunding', 2),
    ('Criptomonedas', 2),
    ('Fondos de capital de riesgo', 2),
    ('Acciones de dividendos', 2),
    ('Inversiones en startups', 2),
    ('Bonos corporativos', 2),
    ('Inversiones en arte o coleccionables', 2),
    ('Planes de pensiones o jubilación', 2),
    ('Anualidades', 2),
    ('Bienes raíces comerciales', 2),
    ('Obligaciones convertibles', 2),
    ('Inversión inmobiliaria', 2),
    ('Bolsa de valores nacional', 3),
    ('Bolsa de valores internacional', 3),
    ('Mercado de divisas (Forex)', 3),
    ('Mercado de bonos', 3),
    ('Mercado de materias primas', 3),
    ('Mercado de futuros', 3),
    ('Mercado de opciones', 3),
    ('Mercado de criptomonedas', 3),
    ('Mercado de derivados financieros', 3),
    ('Mercado de valores gubernamentales', 3),
    ('Mercado de valores corporativos', 3),
    ('Mercado monetario', 3),
    ('Mercado de metales preciosos', 3),
    ('Mercado de energía', 3),
    ('Mercado de alimentos y agricultura', 3),
    ('Mercado de bienes inmuebles comerciales', 3),
    ('Mercado de seguros y reaseguros', 3),
    ('Mercado de productos básicos', 3),
    ('Mercado de índices bursátiles', 3),
    ('Mercado de renta fija y renta variable', 3),
    ('Inversiones extranjeras', 4),
    ('Acuerdos comerciales', 4),
    ('Política monetaria', 4),
    ('Indicadores económicos', 4),
    ('Comercio internacional', 4),
    ('Crisis económicas', 4),
    ('Organizaciones internacionales', 4),
    ('Fluctuaciones cambiarias', 4),
    ('Deuda soberana', 4),
    ('Sostenibilidad ambiental', 4),
    ('Migración económica', 4),
    ('Innovación tecnológica', 4),
    ('Mercados emergentes', 4),
    ('Regulación financiera', 4),
    ('Desarrollo económico', 4),
    ('Economía colaborativa', 4),
    ('Políticas fiscales', 4),
    ('Riesgos financieros', 4),
    ('Economía circular', 4),
    ('Competencia global', 4),
    ('Mobiliario moderno', 5),
    ('Iluminación ambiental', 5),
    ('Tapicería elegante', 5),
    ('Estilo minimalista', 5),
    ('Colores vibrantes', 5),
    ('Arte mural', 5),
    ('Diseño de interiores', 5),
    ('Alfombras exquisitas', 5),
    ('Cortinas elegantes', 5),
    ('Accesorios decorativos', 5),
    ('Plantas ornamentales', 5),
    ('Diseño industrial', 5),
    ('Espacios abiertos', 5),
    ('Elegancia clásica', 5),
    ('Estilo rústico', 5),
    ('Diseño ergonómico', 5),
    ('Organización funcional', 5),
    ('Arquitectura interior', 5),
    ('Detalles personalizados', 5),
    ('Tendencias actuales', 5),
    ('Gestión del tiempo', 6),
    ('Optimización de procesos', 6),
    ('Espacios funcionales', 6),
    ('Almacenamiento eficiente', 6),
    ('Planificación estratégica', 6),
    ('Gestión de proyectos', 6),
    ('Eficiencia operativa', 6),
    ('Organización digital', 6),
    ('Flujo de trabajo', 6),
    ('Comunicación efectiva', 6),
    ('Control de inventario', 6),
    ('Simplificación administrativa', 6),
    ('Organización del flujo de trabajo', 6),
    ('Reducción de desperdicios', 6),
    ('Programación eficiente', 6),
    ('Gestión de documentos', 6),
    ('Sistema de archivo', 6),
    ('Coordinación logística', 6),
    ('Organización del espacio', 6),
    ('Delegación efectiva', 6),
    ('Servicio técnico', 7),
    ('Mantenimiento preventivo', 7),
    ('Reparaciones rápidas', 7),
    ('Calidad de equipos', 7),
    ('Inspección regular', 7),
    ('Limpieza profunda', 7),
    ('Sustitución de piezas', 7),
    ('Mantenimiento predictivo', 7),
    ('Actualizaciones necesarias', 7),
    ('Conservación eficiente', 7),
    ('Plan de mantenimiento', 7),
    ('Monitoreo constante', 7),
    ('Gestión de activos', 7),
    ('Mantenimiento correctivo', 7),
    ('Mantenimiento programado', 7),
    ('Optimización de rendimiento', 7),
    ('Sistemas operativos', 7),
    ('Mantenimiento de infraestructuras', 7),
    ('Mantenimiento de vehículos', 7),
    ('Mantenimiento de redes', 7),
    ('Diseño paisajístico', 8),
    ('Cuidado de plantas', 8),
    ('Mantenimiento de césped', 8),
    ('Riego automático', 8),
    ('Paisajismo urbano', 8),
    ('Vivero especializado', 8),
    ('Control de plagas', 8),
    ('Podas regulares', 8),
    ('Decoración exterior', 8),
    ('Jardinería sostenible', 8),
    ('Huertos urbanos', 8),
    ('Jardines verticales', 8),
    ('Diseño de terrazas', 8),
    ('Instalación de sistemas de iluminación', 8),
    ('Jardinería ornamental', 8),
    ('Plantas de interior', 8),
    ('Jardinería corporativa', 8),
    ('Arreglo floral', 8),
    ('Paisajismo residencial', 8),
    ('Suministro de materiales', 8),
    ('Fútbol', 9),
    ('Baloncesto', 9),
    ('Tenis', 9),
    ('Golf', 9),
    ('Béisbol', 9),
    ('Natación', 9),
    ('Atletismo', 9),
    ('Voleibol', 9),
    ('Rugby', 9),
    ('Ciclismo', 9),
    ('Boxeo', 9),
    ('Esgrima', 9),
    ('Artes marciales', 9),
    ('Hockey', 9),
    ('Surf', 9),
    ('Patinaje', 9),
    ('Gimnasia', 9),
    ('Automovilismo', 9),
    ('Ajedrez', 9),
    ('Karate', 9),
    ('Tenis de mesa', 9),
    ('Equitación', 9),
    ('Pop', 10),
    ('Rock', 10),
    ('Hip-hop', 10),
    ('R&B', 10),
    ('Jazz', 10),
    ('Reggae', 10),
    ('Dance', 10),
    ('Electrónica', 10),
    ('Country', 10),
    ('Folk', 10),
    ('Blues', 10),
    ('Salsa', 10),
    ('Reguetón', 10),
    ('Metal', 10),
    ('Funk', 10),
    ('Soul', 10),
    ('Clásica', 10),
    ('Indie', 10),
    ('Rap', 10),
    ('Latina', 10),
    ('Agencia de viajes', 11),
    ('Alojamiento turístico', 11),
    ('Transporte aéreo', 11),
    ('Cruceros marítimos', 11),
    ('Excursiones guiadas', 11),
    ('Paquetes vacacionales', 11),
    ('Reservas de hoteles', 11),
    ('Turismo de aventura', 11),
    ('Destinos exóticos', 11),
    ('Viajes de negocios', 11),
    ('Turismo gastronómico', 11),
    ('Turismo rural', 11),
    ('Agencia de turismo', 11),
    ('Viajes en grupo', 11),
    ('Turismo sostenible', 11),
    ('Turismo cultural', 11),
    ('Turismo de lujo', 11),
    ('Viajes todo incluido', 11),
    ('Agencia de turismo receptivo', 11),
    ('Viajes temáticos', 11),
    ('Ropa de diseño', 12),
    ('Accesorios de moda', 12),
    ('Pasarela de moda', 12),
    ('Tienda de ropa', 12),
    ('Marcas de lujo', 12),
    ('Moda femenina', 12),
    ('Moda masculina', 12),
    ('Calzado elegante', 12),
    ('Tendencias actuales', 12),
    ('Estilo urbano', 12),
    ('Moda infantil', 12),
    ('Alta costura', 12),
    ('Moda sostenible', 12),
    ('Joyería fina', 12),
    ('Moda vintage', 12),
    ('Estilismo personal', 12),
    ('Complementos de moda', 12),
    ('Moda deportiva', 12),
    ('Lencería íntima', 12),
    ('Moda casual', 12),
    ('Libros bestseller', 13),
    ('Novela romántica', 13),
    ('Thriller psicológico', 13),
    ('Ciencia ficción', 13),
    ('Literatura infantil', 13),
    ('Poesía contemporánea', 13),
    ('Libros de autoayuda', 13),
    ('Literatura clásica', 13),
    ('Libros de cocina', 13),
    ('Novela histórica', 13),
    ('Libros de viajes', 13),
    ('Libros ilustrados', 13),
    ('Literatura fantástica', 13),
    ('Libros de negocios', 13),
    ('Cuentos cortos', 13),
    ('Biografías famosas', 13),
    ('Libros de misterio', 13),
    ('Drama teatral', 13),
    ('Literatura juvenil', 13),
    ('Libros de arte', 13),
    ('Películas taquilleras', 14),
    ('Series de televisión', 14),
    ('Documentales populares', 14),
    ('Estrenos cinematográficos', 14),
    ('Cine independiente', 14),
    ('Reality shows', 14),
    ('Programas de entrevistas', 14),
    ('Comedias románticas', 14),
    ('Acción y aventura', 14),
    ('Programas de cocina', 14),
    ('Dramas televisivos', 14),
    ('Películas de animación', 14),
    ('Thrillers cinematográficos', 14),
    ('Programas de telerrealidad', 14),
    ('Películas de terror', 14),
    ('Series de ciencia ficción', 14),
    ('Programas de competición', 14),
    ('Comedias televisivas', 14),
    ('Películas de superhéroes', 14),
    ('Programas de viajes', 14),
    ('Alimentos premium', 15),
    ('Accesorios para mascotas', 15),
    ('Juegos interactivos', 15),
    ('Cuidado veterinario', 15),
    ('Peluquería canina', 15),
    ('Entrenamiento canino', 15),
    ('Camas cómodas', 15),
    ('Transporte seguro', 15),
    ('Juguetes divertidos', 15),
    ('Servicios de paseo', 15),
    ('Ropa para mascotas', 15),
    ('Snacks saludables', 15),
    ('Comederos automáticos', 15),
    ('Productos de higiene', 15),
    ('Jaulas y cercados', 15),
    ('Collares y correas', 15),
    ('Cajas de arena', 15),
    ('Servicios de adopción', 15),
    ('Entrenamiento felino', 15),
    ('Grooming profesional', 15),
    ('Perros', 15),
    ('Gatos', 15),
    ('Conejos', 15),
    ('Hámsteres', 15),
    ('Pájaros', 15),
    ('Peces', 15),
    ('Serpientes', 15),
    ('Tortugas', 15),
    ('Vacunos', 15),
    ('Caballos', 15),
    ('Instagram', 16),
    ('Facebook', 16),
    ('Twitter', 16),
    ('LinkedIn', 16),
    ('TikTok', 16),
    ('Snapchat', 16),
    ('YouTube', 16),
    ('Pinterest', 16),
    ('WhatsApp', 16),
    ('Twitch', 16),
    ('WeChat', 16),
    ('Telegram', 16),
    ('Reddit', 16),
    ('Tumblr', 16),
    ('Clubhouse', 16),
    ('Spotify', 16),
    ('Vimeo', 16),
    ('Behance', 16),
    ('Discord', 16),
    ('Medium', 16),
    ('Marketing digital', 17),
    ('Desarrollo web', 17),
    ('Gestión empresarial', 17),
    ('Recursos humanos', 17),
    ('Finanzas corporativas', 17),
    ('Consultoría estratégica', 17),
    ('Diseño gráfico', 17),
    ('Ventas internacionales', 17),
    ('Administración de proyectos', 17),
    ('Contabilidad fiscal', 17),
    ('dbidad creativa', 17),
    ('Ingeniería de software', 17),
    ('Gestión de eventos', 17),
    ('Comercio internacional', 17),
    ('Analítica de datos', 17),
    ('Derecho laboral', 17),
    ('Gestión logística', 17),
    ('Servicio al cliente', 17),
    ('Investigación de mercado', 17),
    ('Gestión de calidad', 17),
    ('Comunicación efectiva', 18),
    ('Trabajo en equipo', 18),
    ('Liderazgo estratégico', 18),
    ('Resolución de problemas', 18),
    ('Pensamiento crítico', 18),
    ('Creatividad e innovación', 18),
    ('Gestión del tiempo', 18),
    ('Negociación exitosa', 18),
    ('Adaptabilidad y flexibilidad', 18),
    ('Orientación al cliente', 18),
    ('Pensamiento analítico', 18),
    ('Competencias digitales', 18),
    ('Gestión de proyectos', 18),
    ('Empatía y habilidades sociales', 18),
    ('Toma de decisiones', 18),
    ('Pensamiento estratégico', 18),
    ('Capacidad de aprendizaje rápido', 18),
    ('Organización y planificación', 18),
    ('Resiliencia y manejo del estrés', 18),
    ('Habilidades de presentación', 18),
    ('Planificación estratégica', 19),
    ('Investigación de mercado', 19),
    ('Identificación de oportunidades', 19),
    ('Modelo de negocio', 19),
    ('Financiamiento inicial', 19),
    ('Desarrollo de productos', 19),
    ('Marketing digital', 19),
    ('Ventas efectivas', 19),
    ('Gestión de recursos', 19),
    ('Networking empresarial', 19),
    ('Análisis de competencia', 19),
    ('Innovación disruptiva', 19),
    ('Construcción de marca', 19),
    ('Gestión financiera', 19),
    ('Negociación empresarial', 19),
    ('Manejo de riesgos', 19),
    ('Administración del tiempo', 19),
    ('Cultura empresarial', 19),
    ('Resiliencia emprendedora', 19),
    ('Escalabilidad empresarial', 19),
    ('Currículum vitae', 20),
    ('Carta de presentación', 20),
    ('Entrevista laboral', 20),
    ('Portales de empleo', 20),
    ('Redes profesionales', 20),
    ('Perfil profesional', 20),
    ('Branding personal', 20),
    ('Estrategia de búsqueda', 20),
    ('Investigación de empresas', 20),
    ('Networking laboral', 20),
    ('Aplicaciones móviles', 20),
    ('Reclutamiento online', 20),
    ('Habilidades transferibles', 20),
    ('Cartas de recomendación', 20),
    ('Preparación de entrevistas', 20),
    ('Perfil en LinkedIn', 20),
    ('Estrategia de seguimiento', 20),
    ('Preparación de pruebas', 20),
    ('Desarrollo de habilidades', 20),
    ('Evaluación de competencias', 20),
    ('Japonés', 21),
    ('Italiana', 21),
    ('Mexicana', 21),
    ('Española', 21),
    ('Indio', 21),
    ('Chino', 21),
    ('Suiza', 21),
    ('Británica', 21),
    ('Alemán', 21),
    ('Griega', 21),
    ('Peruana', 21),
    ('Coreana', 21),
    ('Argentina', 21),
    ('Tailandés', 21),
    ('Canadiense', 21),
    ('Vietnamita', 21),
    ('Francesa', 21),
    ('Brasileña', 21),
    ('Austríaca', 21),
    ('Pakistaní', 21),
    ('Comidas vegetarianas', 22),
    ('Platos bajos en calorías', 22),
    ('Opciones sin gluten', 22),
    ('Ensaladas y bowls nutritivos', 22),
    ('Smoothies saludables', 22),
    ('Postres saludables', 22),
    ('Snacks energéticos', 22),
    ('Desayunos balanceados', 22),
    ('Almuerzos equilibrados', 22),
    ('Cenas saludables', 22),
    ('Meriendas saludables', 22),
    ('Comidas rápidas y saludables', 22),
    ('Recetas veganas', 22),
    ('Platos altos en proteínas', 22),
    ('Menús balanceados', 22),
    ('Bebidas saludables', 22),
    ('Recetas para niños saludables', 22),
    ('Comidas para llevar', 22),
    ('Platos sin azúcar añadido', 22),
    ('Recetas sin lactosa', 22),
    ('Tartas frutales', 23),
    ('Helados naturales', 23),
    ('Galletas integrales', 23),
    ('Muffins sin azúcar', 23),
    ('Brownies saludables', 23),
    ('Yogur con frutas', 23),
    ('Pudín', 23),
    ('Trufas', 23),
    ('Cheesecakes ligeros', 23),
    ('Barritas de cereales', 23),
    ('Crepes', 23),
    ('Natillas sin azúcar', 23),
    ('Flanes', 23),
    ('Crumbles de frutas', 23),
    ('Tartaletas saludables', 23),
    ('Bizcochos', 23),
    ('Popsicles', 23),
    ('Tortitas de proteínas', 23),
    ('Postres con chocolate negro', 23),
    ('Budines', 23),
    ('Batidos', 24),
    ('Smoothies', 24),
    ('Café helado', 24),
    ('Té matcha', 24),
    ('Jugos detox', 24),
    ('Aguas saborizadas', 24),
    ('Refrescos naturales', 24),
    ('Limonadas', 24),
    ('Mocktails sin alcohol', 24),
    ('Cócteles de frutas', 24),
    ('Margaritas', 24),
    ('Mojitos', 24),
    ('Piña colada', 24),
    ('Sangrías', 24),
    ('Caipirinhas', 24),
    ('Agua de coco', 24),
    ('Infusiones', 24),
    ('Leches', 24),
    ('Licuados', 24),
    ('Agua de sandía', 24),
    ('Router inalámbrico', 25),
    ('Servicio de hosting', 25),
    ('Dominio personalizado', 25),
    ('Redes sociales', 25),
    ('Navegador web', 25),
    ('Aplicaciones móviles', 25),
    ('Correo electrónico', 25),
    ('Servicio de streaming', 25),
    ('VPN segura', 25),
    ('dbidad online', 25),
    ('Marketing digital', 25),
    ('Comercio electrónico', 25),
    ('Análisis de datos', 25),
    ('Plataforma de blogging', 25),
    ('Redes de afiliados', 25),
    ('Herramientas de SEO', 25),
    ('Plataforma de videoconferencias', 25),
    ('Seguridad en línea', 25),
    ('Gestión de contenidos', 25),
    ('Comunidades en línea', 25),
    ('Calculadoras', 26),
    ('Editores de fotos', 26),
    ('Plataformas de mensajería', 26),
    ('Mapas y navegación', 26),
    ('Redes sociales', 26),
    ('Reproductores de música', 26),
    ('Lector de libros', 26),
    ('Agenda digital', 26),
    ('Gestor de tareas', 26),
    ('Aplicaciones de citas', 26),
    ('Asistentes virtuales', 26),
    ('Juegos de puzzle', 26),
    ('Entrenadores personales', 26),
    ('Aplicación de noticias', 26),
    ('Traductor en línea', 26),
    ('Herramienta de edición de video', 26),
    ('Aplicación de clima', 26),
    ('Guía de viajes', 26),
    ('Aplicación de ejercicios', 26),
    ('Video en streaming', 26),
    ('Editor de código', 27),
    ('IDE móvil', 27),
    ('Emulador de dispositivos', 27),
    ('Depurador integrado', 27),
    ('Control de versiones', 27),
    ('Framework frontend', 27),
    ('Biblioteca de código', 27),
    ('Generador de código', 27),
    ('Documentación técnica', 27),
    ('Gestión de dependencias', 27),
    ('Herramienta de pruebas', 27),
    ('Analizador de código', 27),
    ('Entorno de desarrollo', 27),
    ('Plantillas de diseño', 27),
    ('Simulador de redes', 27),
    ('Asistente de automatización', 27),
    ('Compilador móvil', 27),
    ('Gestor de paquetes', 27),
    ('Motor de plantillas', 27),
    ('Generador de documentación', 27);

INSERT INTO
    role_permission
VALUES
    ('BUYER', 'PLUS', 'POST', 0),
    ('BUYER', 'PLUS', 'GET', 0),
    ('BUYER', 'PLUS', 'PATCH', 0),
    ('BUYER', 'PLUS', 'DELETE', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'POST', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'GET', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'DELETE', 0),
    ('CATEGORY', 'PLUS', 'POST', 0),
    ('CATEGORY', 'PLUS', 'GET', 1),
    ('CATEGORY', 'PLUS', 'PATCH', 0),
    ('CATEGORY', 'PLUS', 'DELETE', 0),
    ('CITY', 'PLUS', 'POST', 0),
    ('CITY', 'PLUS', 'GET', 1),
    ('CITY', 'PLUS', 'PATCH', 0),
    ('CITY', 'PLUS', 'DELETE', 0),
    ('COMPANY', 'PLUS', 'POST', 0),
    ('COMPANY', 'PLUS', 'GET', 1),
    ('COMPANY', 'PLUS', 'PATCH', 0),
    ('COMPANY', 'PLUS', 'DELETE', 0),
    ('COUNTRY', 'PLUS', 'POST', 0),
    ('COUNTRY', 'PLUS', 'GET', 1),
    ('COUNTRY', 'PLUS', 'PATCH', 0),
    ('COUNTRY', 'PLUS', 'DELETE', 0),
    ('CREDENTIALS', 'PLUS', 'POST', 1),
    ('CREDENTIALS', 'PLUS', 'GET', 1),
    ('CREDENTIALS', 'PLUS', 'PATCH', 1),
    ('CREDENTIALS', 'PLUS', 'DELETE', 0),
    ('DATABASE-TYPE', 'PLUS', 'POST', 0),
    ('DATABASE-TYPE', 'PLUS', 'GET', 0),
    ('DATABASE-TYPE', 'PLUS', 'PATCH', 0),
    ('DATABASE-TYPE', 'PLUS', 'DELETE', 0),
    ('DEMAND', 'PLUS', 'POST', 1),
    ('DEMAND', 'PLUS', 'GET', 1),
    ('DEMAND', 'PLUS', 'PATCH', 0),
    ('DEMAND', 'PLUS', 'DELETE', 0),
    ('ELEMENT', 'PLUS', 'POST', 0),
    ('ELEMENT', 'PLUS', 'GET', 1),
    ('ELEMENT', 'PLUS', 'PATCH', 0),
    ('ELEMENT', 'PLUS', 'DELETE', 0),
    ('EMPLOYEE', 'PLUS', 'POST', 0),
    ('EMPLOYEE', 'PLUS', 'GET', 0),
    ('EMPLOYEE', 'PLUS', 'PATCH', 0),
    ('EMPLOYEE', 'PLUS', 'DELETE', 0),
    ('ERROR-LOG', 'PLUS', 'POST', 0),
    ('ERROR-LOG', 'PLUS', 'GET', 0),
    ('ERROR-LOG', 'PLUS', 'PATCH', 0),
    ('ERROR-LOG', 'PLUS', 'DELETE', 0),
    ('FAQ', 'PLUS', 'POST', 0),
    ('FAQ', 'PLUS', 'GET', 1),
    ('FAQ', 'PLUS', 'PATCH', 0),
    ('FAQ', 'PLUS', 'DELETE', 0),
    ('GENDER', 'PLUS', 'POST', 0),
    ('GENDER', 'PLUS', 'GET', 1),
    ('GENDER', 'PLUS', 'PATCH', 0),
    ('GENDER', 'PLUS', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'PLUS', 'POST', 0),
    ('IDENT-DOCUMENT', 'PLUS', 'GET', 1),
    ('IDENT-DOCUMENT', 'PLUS', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'PLUS', 'DELETE', 0),
    ('OBJECT', 'PLUS', 'POST', 0),
    ('OBJECT', 'PLUS', 'GET', 0),
    ('OBJECT', 'PLUS', 'PATCH', 0),
    ('OBJECT', 'PLUS', 'DELETE', 0),
    ('PERSON', 'PLUS', 'POST', 1),
    ('PERSON', 'PLUS', 'GET', 1),
    ('PERSON', 'PLUS', 'PATCH', 1),
    ('PERSON', 'PLUS', 'DELETE', 0),
    ('PLAN', 'PLUS', 'POST', 0),
    ('PLAN', 'PLUS', 'GET', 1),
    ('PLAN', 'PLUS', 'PATCH', 0),
    ('PLAN', 'PLUS', 'DELETE', 0),
    ('POLITIC', 'PLUS', 'POST', 0),
    ('POLITIC', 'PLUS', 'GET', 1),
    ('POLITIC', 'PLUS', 'PATCH', 0),
    ('POLITIC', 'PLUS', 'DELETE', 0),
    ('POLITIC-BODY', 'PLUS', 'POST', 0),
    ('POLITIC-BODY', 'PLUS', 'GET', 1),
    ('POLITIC-BODY', 'PLUS', 'PATCH', 0),
    ('POLITIC-BODY', 'PLUS', 'DELETE', 0),
    ('POLITICS-ACCEPTED', 'PLUS', 'POST', 1),
    ('POLITICS-ACCEPTED', 'PLUS', 'GET', 0),
    ('POLITICS-ACCEPTED', 'PLUS', 'PATCH', 0),
    ('POLITICS-ACCEPTED', 'PLUS', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'PLUS', 'POST', 0),
    ('REDEEMED-HISTORY', 'PLUS', 'GET', 1),
    ('REDEEMED-HISTORY', 'PLUS', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'PLUS', 'DELETE', 0),
    ('REQUEST', 'PLUS', 'POST', 1),
    ('REQUEST', 'PLUS', 'GET', 1),
    ('REQUEST', 'PLUS', 'PATCH', 0),
    ('REQUEST', 'PLUS', 'DELETE', 0),
    ('REQUIREMENT', 'PLUS', 'POST', 0),
    ('REQUIREMENT', 'PLUS', 'GET', 1),
    ('REQUIREMENT', 'PLUS', 'PATCH', 0),
    ('REQUIREMENT', 'PLUS', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'PLUS', 'POST', 0),
    ('REQUIREMENT-BODY', 'PLUS', 'GET', 1),
    ('REQUIREMENT-BODY', 'PLUS', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'PLUS', 'DELETE', 0),
    ('REWARD', 'PLUS', 'POST', 0),
    ('REWARD', 'PLUS', 'GET', 1),
    ('REWARD', 'PLUS', 'PATCH', 0),
    ('REWARD', 'PLUS', 'DELETE', 0),
    ('REWARD-CURRENCY', 'PLUS', 'POST', 0),
    ('REWARD-CURRENCY', 'PLUS', 'GET', 1),
    ('REWARD-CURRENCY', 'PLUS', 'PATCH', 0),
    ('REWARD-CURRENCY', 'PLUS', 'DELETE', 0),
    ('ROLE', 'PLUS', 'POST', 0),
    ('ROLE', 'PLUS', 'GET', 0),
    ('ROLE', 'PLUS', 'PATCH', 0),
    ('ROLE', 'PLUS', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'POST', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'GET', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'DELETE', 0),
    ('SELECTION', 'PLUS', 'POST', 0),
    ('SELECTION', 'PLUS', 'GET', 0),
    ('SELECTION', 'PLUS', 'PATCH', 0),
    ('SELECTION', 'PLUS', 'DELETE', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'PATCH', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'DELETE', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'POST', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'GET', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'DELETE', 0),
    ('STATE', 'PLUS', 'POST', 0),
    ('STATE', 'PLUS', 'GET', 1),
    ('STATE', 'PLUS', 'PATCH', 0),
    ('STATE', 'PLUS', 'DELETE', 0),
    ('STATUS', 'PLUS', 'POST', 0),
    ('STATUS', 'PLUS', 'GET', 1),
    ('STATUS', 'PLUS', 'PATCH', 0),
    ('STATUS', 'PLUS', 'DELETE', 0),
    ('SUBCATEGORY', 'PLUS', 'POST', 0),
    ('SUBCATEGORY', 'PLUS', 'GET', 0),
    ('SUBCATEGORY', 'PLUS', 'PATCH', 0),
    ('SUBCATEGORY', 'PLUS', 'DELETE', 0),
    ('USER', 'PLUS', 'POST', 1),
    ('USER', 'PLUS', 'GET', 1),
    ('USER', 'PLUS', 'PATCH', 1),
    ('USER', 'PLUS', 'DELETE', 0),
    ('USERS-BUYED', 'PLUS', 'POST', 0),
    ('USERS-BUYED', 'PLUS', 'GET', 0),
    ('USERS-BUYED', 'PLUS', 'PATCH', 0),
    ('USERS-BUYED', 'PLUS', 'DELETE', 0),
    ('WHITE-LIST', 'PLUS', 'POST', 1),
    ('WHITE-LIST', 'PLUS', 'GET', 1),
    ('WHITE-LIST', 'PLUS', 'PATCH', 0),
    ('WHITE-LIST', 'PLUS', 'DELETE', 0),
    ('PQR', 'PLUS', 'POST', 0),
    ('PQR', 'PLUS', 'GET', 1),
    ('PQR', 'PLUS', 'PATCH', 0),
    ('PQR', 'PLUS', 'DELETE', 0),
    ('BUYER', 'CONTROL', 'POST', 0),
    ('BUYER', 'CONTROL', 'GET', 0),
    ('BUYER', 'CONTROL', 'PATCH', 0),
    ('BUYER', 'CONTROL', 'DELETE', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'POST', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'GET', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'DELETE', 0),
    ('CATEGORY', 'CONTROL', 'POST', 0),
    ('CATEGORY', 'CONTROL', 'GET', 0),
    ('CATEGORY', 'CONTROL', 'PATCH', 0),
    ('CATEGORY', 'CONTROL', 'DELETE', 0),
    ('CITY', 'CONTROL', 'POST', 0),
    ('CITY', 'CONTROL', 'GET', 1),
    ('CITY', 'CONTROL', 'PATCH', 0),
    ('CITY', 'CONTROL', 'DELETE', 0),
    ('COMPANY', 'CONTROL', 'POST', 0),
    ('COMPANY', 'CONTROL', 'GET', 1),
    ('COMPANY', 'CONTROL', 'PATCH', 0),
    ('COMPANY', 'CONTROL', 'DELETE', 0),
    ('COUNTRY', 'CONTROL', 'POST', 0),
    ('COUNTRY', 'CONTROL', 'GET', 1),
    ('COUNTRY', 'CONTROL', 'PATCH', 0),
    ('COUNTRY', 'CONTROL', 'DELETE', 0),
    ('CREDENTIALS', 'CONTROL', 'POST', 1),
    ('CREDENTIALS', 'CONTROL', 'GET', 1),
    ('CREDENTIALS', 'CONTROL', 'PATCH', 1),
    ('CREDENTIALS', 'CONTROL', 'DELETE', 0),
    ('DATABASE-TYPE', 'CONTROL', 'POST', 0),
    ('DATABASE-TYPE', 'CONTROL', 'GET', 0),
    ('DATABASE-TYPE', 'CONTROL', 'PATCH', 0),
    ('DATABASE-TYPE', 'CONTROL', 'DELETE', 0),
    ('DEMAND', 'CONTROL', 'POST', 1),
    ('DEMAND', 'CONTROL', 'GET', 1),
    ('DEMAND', 'CONTROL', 'PATCH', 0),
    ('DEMAND', 'CONTROL', 'DELETE', 0),
    ('ELEMENT', 'CONTROL', 'POST', 0),
    ('ELEMENT', 'CONTROL', 'GET', 0),
    ('ELEMENT', 'CONTROL', 'PATCH', 0),
    ('ELEMENT', 'CONTROL', 'DELETE', 0),
    ('EMPLOYEE', 'CONTROL', 'POST', 0),
    ('EMPLOYEE', 'CONTROL', 'GET', 0),
    ('EMPLOYEE', 'CONTROL', 'PATCH', 0),
    ('EMPLOYEE', 'CONTROL', 'DELETE', 0),
    ('ERROR-LOG', 'CONTROL', 'POST', 0),
    ('ERROR-LOG', 'CONTROL', 'GET', 0),
    ('ERROR-LOG', 'CONTROL', 'PATCH', 0),
    ('ERROR-LOG', 'CONTROL', 'DELETE', 0),
    ('FAQ', 'CONTROL', 'POST', 0),
    ('FAQ', 'CONTROL', 'GET', 1),
    ('FAQ', 'CONTROL', 'PATCH', 0),
    ('FAQ', 'CONTROL', 'DELETE', 0),
    ('GENDER', 'CONTROL', 'POST', 0),
    ('GENDER', 'CONTROL', 'GET', 1),
    ('GENDER', 'CONTROL', 'PATCH', 0),
    ('GENDER', 'CONTROL', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'CONTROL', 'POST', 0),
    ('IDENT-DOCUMENT', 'CONTROL', 'GET', 1),
    ('IDENT-DOCUMENT', 'CONTROL', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'CONTROL', 'DELETE', 0),
    ('OBJECT', 'CONTROL', 'POST', 0),
    ('OBJECT', 'CONTROL', 'GET', 0),
    ('OBJECT', 'CONTROL', 'PATCH', 0),
    ('OBJECT', 'CONTROL', 'DELETE', 0),
    ('PERSON', 'CONTROL', 'POST', 1),
    ('PERSON', 'CONTROL', 'GET', 1),
    ('PERSON', 'CONTROL', 'PATCH', 1),
    ('PERSON', 'CONTROL', 'DELETE', 0),
    ('PLAN', 'CONTROL', 'POST', 0),
    ('PLAN', 'CONTROL', 'GET', 1),
    ('PLAN', 'CONTROL', 'PATCH', 0),
    ('PLAN', 'CONTROL', 'DELETE', 0),
    ('POLITIC', 'CONTROL', 'POST', 0),
    ('POLITIC', 'CONTROL', 'GET', 1),
    ('POLITIC', 'CONTROL', 'PATCH', 0),
    ('POLITIC', 'CONTROL', 'DELETE', 0),
    ('POLITIC-BODY', 'CONTROL', 'POST', 0),
    ('POLITIC-BODY', 'CONTROL', 'GET', 1),
    ('POLITIC-BODY', 'CONTROL', 'PATCH', 0),
    ('POLITIC-BODY', 'CONTROL', 'DELETE', 0),
    ('POLITICS-ACCEPTED', 'CONTROL', 'POST', 1),
    ('POLITICS-ACCEPTED', 'CONTROL', 'GET', 0),
    ('POLITICS-ACCEPTED', 'CONTROL', 'PATCH', 0),
    ('POLITICS-ACCEPTED', 'CONTROL', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'CONTROL', 'POST', 0),
    ('REDEEMED-HISTORY', 'CONTROL', 'GET', 1),
    ('REDEEMED-HISTORY', 'CONTROL', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'CONTROL', 'DELETE', 0),
    ('REQUEST', 'CONTROL', 'POST', 1),
    ('REQUEST', 'CONTROL', 'GET', 1),
    ('REQUEST', 'CONTROL', 'PATCH', 0),
    ('REQUEST', 'CONTROL', 'DELETE', 0),
    ('REQUIREMENT', 'CONTROL', 'POST', 0),
    ('REQUIREMENT', 'CONTROL', 'GET', 1),
    ('REQUIREMENT', 'CONTROL', 'PATCH', 0),
    ('REQUIREMENT', 'CONTROL', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'CONTROL', 'POST', 0),
    ('REQUIREMENT-BODY', 'CONTROL', 'GET', 1),
    ('REQUIREMENT-BODY', 'CONTROL', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'CONTROL', 'DELETE', 0),
    ('REWARD', 'CONTROL', 'POST', 0),
    ('REWARD', 'CONTROL', 'GET', 0),
    ('REWARD', 'CONTROL', 'PATCH', 0),
    ('REWARD', 'CONTROL', 'DELETE', 0),
    ('REWARD-CURRENCY', 'CONTROL', 'POST', 0),
    ('REWARD-CURRENCY', 'CONTROL', 'GET', 1),
    ('REWARD-CURRENCY', 'CONTROL', 'PATCH', 0),
    ('REWARD-CURRENCY', 'CONTROL', 'DELETE', 0),
    ('ROLE', 'CONTROL', 'POST', 0),
    ('ROLE', 'CONTROL', 'GET', 0),
    ('ROLE', 'CONTROL', 'PATCH', 0),
    ('ROLE', 'CONTROL', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'POST', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'GET', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'DELETE', 0),
    ('SELECTION', 'CONTROL', 'POST', 0),
    ('SELECTION', 'CONTROL', 'GET', 0),
    ('SELECTION', 'CONTROL', 'PATCH', 0),
    ('SELECTION', 'CONTROL', 'DELETE', 0),
    ('SHOPPING-DEMAND-HISTORY', 'CONTROL', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'CONTROL', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'CONTROL', 'PATCH', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'CONTROL',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'CONTROL', 'POST', 0),
    ('SHOPPINGHISTORY', 'CONTROL', 'GET', 1),
    ('SHOPPINGHISTORY', 'CONTROL', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'CONTROL', 'DELETE', 0),
    ('STATE', 'CONTROL', 'POST', 0),
    ('STATE', 'CONTROL', 'GET', 1),
    ('STATE', 'CONTROL', 'PATCH', 0),
    ('STATE', 'CONTROL', 'DELETE', 0),
    ('STATUS', 'CONTROL', 'POST', 0),
    ('STATUS', 'CONTROL', 'GET', 1),
    ('STATUS', 'CONTROL', 'PATCH', 0),
    ('STATUS', 'CONTROL', 'DELETE', 0),
    ('SUBCATEGORY', 'CONTROL', 'POST', 0),
    ('SUBCATEGORY', 'CONTROL', 'GET', 0),
    ('SUBCATEGORY', 'CONTROL', 'PATCH', 0),
    ('SUBCATEGORY', 'CONTROL', 'DELETE', 0),
    ('USER', 'CONTROL', 'POST', 1),
    ('USER', 'CONTROL', 'GET', 1),
    ('USER', 'CONTROL', 'PATCH', 1),
    ('USER', 'CONTROL', 'DELETE', 0),
    ('USERS-BUYED', 'CONTROL', 'POST', 0),
    ('USERS-BUYED', 'CONTROL', 'GET', 0),
    ('USERS-BUYED', 'CONTROL', 'PATCH', 0),
    ('USERS-BUYED', 'CONTROL', 'DELETE', 0),
    ('WHITE-LIST', 'CONTROL', 'POST', 0),
    ('WHITE-LIST', 'CONTROL', 'GET', 0),
    ('WHITE-LIST', 'CONTROL', 'PATCH', 0),
    ('WHITE-LIST', 'CONTROL', 'DELETE', 0),
    ('PQR', 'CONTROL', 'POST', 0),
    ('PQR', 'CONTROL', 'GET', 1),
    ('PQR', 'CONTROL', 'PATCH', 0),
    ('PQR', 'CONTROL', 'DELETE', 0),
    ('BUYER', 'PREMIUM', 'POST', 0),
    ('BUYER', 'PREMIUM', 'GET', 0),
    ('BUYER', 'PREMIUM', 'PATCH', 0),
    ('BUYER', 'PREMIUM', 'DELETE', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'POST', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'GET', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'DELETE', 0),
    ('CATEGORY', 'PREMIUM', 'POST', 0),
    ('CATEGORY', 'PREMIUM', 'GET', 1),
    ('CATEGORY', 'PREMIUM', 'PATCH', 0),
    ('CATEGORY', 'PREMIUM', 'DELETE', 0),
    ('CITY', 'PREMIUM', 'POST', 0),
    ('CITY', 'PREMIUM', 'GET', 1),
    ('CITY', 'PREMIUM', 'PATCH', 0),
    ('CITY', 'PREMIUM', 'DELETE', 0),
    ('COMPANY', 'PREMIUM', 'POST', 0),
    ('COMPANY', 'PREMIUM', 'GET', 1),
    ('COMPANY', 'PREMIUM', 'PATCH', 0),
    ('COMPANY', 'PREMIUM', 'DELETE', 0),
    ('COUNTRY', 'PREMIUM', 'POST', 0),
    ('COUNTRY', 'PREMIUM', 'GET', 1),
    ('COUNTRY', 'PREMIUM', 'PATCH', 0),
    ('COUNTRY', 'PREMIUM', 'DELETE', 0),
    ('CREDENTIALS', 'PREMIUM', 'POST', 1),
    ('CREDENTIALS', 'PREMIUM', 'GET', 1),
    ('CREDENTIALS', 'PREMIUM', 'PATCH', 1),
    ('CREDENTIALS', 'PREMIUM', 'DELETE', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'POST', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'GET', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'PATCH', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'DELETE', 0),
    ('DEMAND', 'PREMIUM', 'POST', 1),
    ('DEMAND', 'PREMIUM', 'GET', 1),
    ('DEMAND', 'PREMIUM', 'PATCH', 0),
    ('DEMAND', 'PREMIUM', 'DELETE', 0),
    ('ELEMENT', 'PREMIUM', 'POST', 0),
    ('ELEMENT', 'PREMIUM', 'GET', 1),
    ('ELEMENT', 'PREMIUM', 'PATCH', 0),
    ('ELEMENT', 'PREMIUM', 'DELETE', 0),
    ('EMPLOYEE', 'PREMIUM', 'POST', 0),
    ('EMPLOYEE', 'PREMIUM', 'GET', 0),
    ('EMPLOYEE', 'PREMIUM', 'PATCH', 0),
    ('EMPLOYEE', 'PREMIUM', 'DELETE', 0),
    ('ERROR-LOG', 'PREMIUM', 'POST', 0),
    ('ERROR-LOG', 'PREMIUM', 'GET', 0),
    ('ERROR-LOG', 'PREMIUM', 'PATCH', 0),
    ('ERROR-LOG', 'PREMIUM', 'DELETE', 0),
    ('FAQ', 'PREMIUM', 'POST', 0),
    ('FAQ', 'PREMIUM', 'GET', 1),
    ('FAQ', 'PREMIUM', 'PATCH', 0),
    ('FAQ', 'PREMIUM', 'DELETE', 0),
    ('GENDER', 'PREMIUM', 'POST', 0),
    ('GENDER', 'PREMIUM', 'GET', 1),
    ('GENDER', 'PREMIUM', 'PATCH', 0),
    ('GENDER', 'PREMIUM', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'PREMIUM', 'POST', 0),
    ('IDENT-DOCUMENT', 'PREMIUM', 'GET', 1),
    ('IDENT-DOCUMENT', 'PREMIUM', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'PREMIUM', 'DELETE', 0),
    ('OBJECT', 'PREMIUM', 'POST', 0),
    ('OBJECT', 'PREMIUM', 'GET', 0),
    ('OBJECT', 'PREMIUM', 'PATCH', 0),
    ('OBJECT', 'PREMIUM', 'DELETE', 0),
    ('PERSON', 'PREMIUM', 'POST', 1),
    ('PERSON', 'PREMIUM', 'GET', 1),
    ('PERSON', 'PREMIUM', 'PATCH', 1),
    ('PERSON', 'PREMIUM', 'DELETE', 0),
    ('PLAN', 'PREMIUM', 'POST', 0),
    ('PLAN', 'PREMIUM', 'GET', 1),
    ('PLAN', 'PREMIUM', 'PATCH', 0),
    ('PLAN', 'PREMIUM', 'DELETE', 0),
    ('POLITIC', 'PREMIUM', 'POST', 0),
    ('POLITIC', 'PREMIUM', 'GET', 1),
    ('POLITIC', 'PREMIUM', 'PATCH', 0),
    ('POLITIC', 'PREMIUM', 'DELETE', 0),
    ('POLITIC-BODY', 'PREMIUM', 'POST', 0),
    ('POLITIC-BODY', 'PREMIUM', 'GET', 1),
    ('POLITIC-BODY', 'PREMIUM', 'PATCH', 0),
    ('POLITIC-BODY', 'PREMIUM', 'DELETE', 0),
    ('POLITICS-ACCEPTED', 'PREMIUM', 'POST', 1),
    ('POLITICS-ACCEPTED', 'PREMIUM', 'GET', 0),
    ('POLITICS-ACCEPTED', 'PREMIUM', 'PATCH', 0),
    ('POLITICS-ACCEPTED', 'PREMIUM', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'PREMIUM', 'POST', 0),
    ('REDEEMED-HISTORY', 'PREMIUM', 'GET', 1),
    ('REDEEMED-HISTORY', 'PREMIUM', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'PREMIUM', 'DELETE', 0),
    ('REQUEST', 'PREMIUM', 'POST', 1),
    ('REQUEST', 'PREMIUM', 'GET', 1),
    ('REQUEST', 'PREMIUM', 'PATCH', 0),
    ('REQUEST', 'PREMIUM', 'DELETE', 0),
    ('REQUIREMENT', 'PREMIUM', 'POST', 0),
    ('REQUIREMENT', 'PREMIUM', 'GET', 1),
    ('REQUIREMENT', 'PREMIUM', 'PATCH', 0),
    ('REQUIREMENT', 'PREMIUM', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'PREMIUM', 'POST', 0),
    ('REQUIREMENT-BODY', 'PREMIUM', 'GET', 1),
    ('REQUIREMENT-BODY', 'PREMIUM', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'PREMIUM', 'DELETE', 0),
    ('REWARD', 'PREMIUM', 'POST', 1),
    ('REWARD', 'PREMIUM', 'GET', 1),
    ('REWARD', 'PREMIUM', 'PATCH', 0),
    ('REWARD', 'PREMIUM', 'DELETE', 0),
    ('REWARD-CURRENCY', 'PREMIUM', 'POST', 0),
    ('REWARD-CURRENCY', 'PREMIUM', 'GET', 1),
    ('REWARD-CURRENCY', 'PREMIUM', 'PATCH', 0),
    ('REWARD-CURRENCY', 'PREMIUM', 'DELETE', 0),
    ('ROLE', 'PREMIUM', 'POST', 0),
    ('ROLE', 'PREMIUM', 'GET', 0),
    ('ROLE', 'PREMIUM', 'PATCH', 0),
    ('ROLE', 'PREMIUM', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'POST', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'GET', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'DELETE', 0),
    ('SELECTION', 'PREMIUM', 'POST', 1),
    ('SELECTION', 'PREMIUM', 'GET', 1),
    ('SELECTION', 'PREMIUM', 'PATCH', 0),
    ('SELECTION', 'PREMIUM', 'DELETE', 1),
    ('SHOPPING-DEMAND-HISTORY', 'PREMIUM', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PREMIUM', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PREMIUM', 'PATCH', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'PREMIUM',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'PREMIUM', 'POST', 0),
    ('SHOPPINGHISTORY', 'PREMIUM', 'GET', 1),
    ('SHOPPINGHISTORY', 'PREMIUM', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'PREMIUM', 'DELETE', 0),
    ('STATE', 'PREMIUM', 'POST', 0),
    ('STATE', 'PREMIUM', 'GET', 1),
    ('STATE', 'PREMIUM', 'PATCH', 0),
    ('STATE', 'PREMIUM', 'DELETE', 0),
    ('STATUS', 'PREMIUM', 'POST', 0),
    ('STATUS', 'PREMIUM', 'GET', 1),
    ('STATUS', 'PREMIUM', 'PATCH', 0),
    ('STATUS', 'PREMIUM', 'DELETE', 0),
    ('SUBCATEGORY', 'PREMIUM', 'POST', 0),
    ('SUBCATEGORY', 'PREMIUM', 'GET', 1),
    ('SUBCATEGORY', 'PREMIUM', 'PATCH', 0),
    ('SUBCATEGORY', 'PREMIUM', 'DELETE', 0),
    ('USER', 'PREMIUM', 'POST', 1),
    ('USER', 'PREMIUM', 'GET', 1),
    ('USER', 'PREMIUM', 'PATCH', 1),
    ('USER', 'PREMIUM', 'DELETE', 0),
    ('USERS-BUYED', 'PREMIUM', 'POST', 0),
    ('USERS-BUYED', 'PREMIUM', 'GET', 0),
    ('USERS-BUYED', 'PREMIUM', 'PATCH', 0),
    ('USERS-BUYED', 'PREMIUM', 'DELETE', 0),
    ('WHITE-LIST', 'PREMIUM', 'POST', 1),
    ('WHITE-LIST', 'PREMIUM', 'GET', 1),
    ('WHITE-LIST', 'PREMIUM', 'PATCH', 0),
    ('WHITE-LIST', 'PREMIUM', 'DELETE', 0),
    ('PQR', 'PREMIUM', 'POST', 0),
    ('PQR', 'PREMIUM', 'GET', 1),
    ('PQR', 'PREMIUM', 'PATCH', 0),
    ('PQR', 'PREMIUM', 'DELETE', 0),
    ('BUYER', 'ABOGADO', 'POST', 0),
    ('BUYER', 'ABOGADO', 'GET', 1),
    ('BUYER', 'ABOGADO', 'PATCH', 0),
    ('BUYER', 'ABOGADO', 'DELETE', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'POST', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'GET', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'DELETE', 0),
    ('CATEGORY', 'ABOGADO', 'POST', 0),
    ('CATEGORY', 'ABOGADO', 'GET', 1),
    ('CATEGORY', 'ABOGADO', 'PATCH', 0),
    ('CATEGORY', 'ABOGADO', 'DELETE', 0),
    ('CITY', 'ABOGADO', 'POST', 0),
    ('CITY', 'ABOGADO', 'GET', 1),
    ('CITY', 'ABOGADO', 'PATCH', 0),
    ('CITY', 'ABOGADO', 'DELETE', 0),
    ('COMPANY', 'ABOGADO', 'POST', 1),
    ('COMPANY', 'ABOGADO', 'GET', 1),
    ('COMPANY', 'ABOGADO', 'PATCH', 1),
    ('COMPANY', 'ABOGADO', 'DELETE', 0),
    ('COUNTRY', 'ABOGADO', 'POST', 0),
    ('COUNTRY', 'ABOGADO', 'GET', 1),
    ('COUNTRY', 'ABOGADO', 'PATCH', 0),
    ('COUNTRY', 'ABOGADO', 'DELETE', 0),
    ('CREDENTIALS', 'ABOGADO', 'POST', 0),
    ('CREDENTIALS', 'ABOGADO', 'GET', 0),
    ('CREDENTIALS', 'ABOGADO', 'PATCH', 0),
    ('CREDENTIALS', 'ABOGADO', 'DELETE', 0),
    ('DATABASE-TYPE', 'ABOGADO', 'POST', 0),
    ('DATABASE-TYPE', 'ABOGADO', 'GET', 1),
    ('DATABASE-TYPE', 'ABOGADO', 'PATCH', 0),
    ('DATABASE-TYPE', 'ABOGADO', 'DELETE', 0),
    ('DEMAND', 'ABOGADO', 'POST', 1),
    ('DEMAND', 'ABOGADO', 'GET', 1),
    ('DEMAND', 'ABOGADO', 'PATCH', 1),
    ('DEMAND', 'ABOGADO', 'DELETE', 0),
    ('ELEMENT', 'ABOGADO', 'POST', 0),
    ('ELEMENT', 'ABOGADO', 'GET', 1),
    ('ELEMENT', 'ABOGADO', 'PATCH', 0),
    ('ELEMENT', 'ABOGADO', 'DELETE', 0),
    ('EMPLOYEE', 'ABOGADO', 'POST', 0),
    ('EMPLOYEE', 'ABOGADO', 'GET', 1),
    ('EMPLOYEE', 'ABOGADO', 'PATCH', 0),
    ('EMPLOYEE', 'ABOGADO', 'DELETE', 0),
    ('ERROR-LOG', 'ABOGADO', 'POST', 0),
    ('ERROR-LOG', 'ABOGADO', 'GET', 0),
    ('ERROR-LOG', 'ABOGADO', 'PATCH', 0),
    ('ERROR-LOG', 'ABOGADO', 'DELETE', 0),
    ('FAQ', 'ABOGADO', 'POST', 0),
    ('FAQ', 'ABOGADO', 'GET', 1),
    ('FAQ', 'ABOGADO', 'PATCH', 0),
    ('FAQ', 'ABOGADO', 'DELETE', 0),
    ('GENDER', 'ABOGADO', 'POST', 0),
    ('GENDER', 'ABOGADO', 'GET', 1),
    ('GENDER', 'ABOGADO', 'PATCH', 0),
    ('GENDER', 'ABOGADO', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'ABOGADO', 'POST', 0),
    ('IDENT-DOCUMENT', 'ABOGADO', 'GET', 1),
    ('IDENT-DOCUMENT', 'ABOGADO', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'ABOGADO', 'DELETE', 0),
    ('OBJECT', 'ABOGADO', 'POST', 0),
    ('OBJECT', 'ABOGADO', 'GET', 0),
    ('OBJECT', 'ABOGADO', 'PATCH', 0),
    ('OBJECT', 'ABOGADO', 'DELETE', 0),
    ('PERSON', 'ABOGADO', 'POST', 0),
    ('PERSON', 'ABOGADO', 'GET', 1),
    ('PERSON', 'ABOGADO', 'PATCH', 0),
    ('PERSON', 'ABOGADO', 'DELETE', 0),
    ('PLAN', 'ABOGADO', 'POST', 0),
    ('PLAN', 'ABOGADO', 'GET', 1),
    ('PLAN', 'ABOGADO', 'PATCH', 0),
    ('PLAN', 'ABOGADO', 'DELETE', 0),
    ('POLITIC', 'ABOGADO', 'POST', 0),
    ('POLITIC', 'ABOGADO', 'GET', 1),
    ('POLITIC', 'ABOGADO', 'PATCH', 0),
    ('POLITIC', 'ABOGADO', 'DELETE', 0),
    ('POLITIC-BODY', 'ABOGADO', 'POST', 0),
    ('POLITIC-BODY', 'ABOGADO', 'GET', 1),
    ('POLITIC-BODY', 'ABOGADO', 'PATCH', 0),
    ('POLITIC-BODY', 'ABOGADO', 'DELETE', 0),
    ('POLITICS-ACCEPTED', 'ABOGADO', 'POST', 0),
    ('POLITICS-ACCEPTED', 'ABOGADO', 'GET', 1),
    ('POLITICS-ACCEPTED', 'ABOGADO', 'PATCH', 0),
    ('POLITICS-ACCEPTED', 'ABOGADO', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'ABOGADO', 'POST', 0),
    ('REDEEMED-HISTORY', 'ABOGADO', 'GET', 1),
    ('REDEEMED-HISTORY', 'ABOGADO', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'ABOGADO', 'DELETE', 0),
    ('REQUEST', 'ABOGADO', 'POST', 1),
    ('REQUEST', 'ABOGADO', 'GET', 1),
    ('REQUEST', 'ABOGADO', 'PATCH', 1),
    ('REQUEST', 'ABOGADO', 'DELETE', 0),
    ('REQUIREMENT', 'ABOGADO', 'POST', 0),
    ('REQUIREMENT', 'ABOGADO', 'GET', 1),
    ('REQUIREMENT', 'ABOGADO', 'PATCH', 0),
    ('REQUIREMENT', 'ABOGADO', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'ABOGADO', 'POST', 0),
    ('REQUIREMENT-BODY', 'ABOGADO', 'GET', 1),
    ('REQUIREMENT-BODY', 'ABOGADO', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'ABOGADO', 'DELETE', 0),
    ('REWARD', 'ABOGADO', 'POST', 0),
    ('REWARD', 'ABOGADO', 'GET', 1),
    ('REWARD', 'ABOGADO', 'PATCH', 0),
    ('REWARD', 'ABOGADO', 'DELETE', 0),
    ('REWARD-CURRENCY', 'ABOGADO', 'POST', 0),
    ('REWARD-CURRENCY', 'ABOGADO', 'GET', 1),
    ('REWARD-CURRENCY', 'ABOGADO', 'PATCH', 0),
    ('REWARD-CURRENCY', 'ABOGADO', 'DELETE', 0),
    ('ROLE', 'ABOGADO', 'POST', 0),
    ('ROLE', 'ABOGADO', 'GET', 1),
    ('ROLE', 'ABOGADO', 'PATCH', 0),
    ('ROLE', 'ABOGADO', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'POST', 0),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'GET', 1),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'DELETE', 0),
    ('SELECTION', 'ABOGADO', 'POST', 0),
    ('SELECTION', 'ABOGADO', 'GET', 1),
    ('SELECTION', 'ABOGADO', 'PATCH', 0),
    ('SELECTION', 'ABOGADO', 'DELETE', 0),
    ('SHOPPING-DEMAND-HISTORY', 'ABOGADO', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'ABOGADO', 'GET', 1),
    ('SHOPPING-DEMAND-HISTORY', 'ABOGADO', 'PATCH', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ABOGADO',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'ABOGADO', 'POST', 0),
    ('SHOPPINGHISTORY', 'ABOGADO', 'GET', 1),
    ('SHOPPINGHISTORY', 'ABOGADO', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'ABOGADO', 'DELETE', 0),
    ('STATE', 'ABOGADO', 'POST', 0),
    ('STATE', 'ABOGADO', 'GET', 1),
    ('STATE', 'ABOGADO', 'PATCH', 0),
    ('STATE', 'ABOGADO', 'DELETE', 0),
    ('STATUS', 'ABOGADO', 'POST', 0),
    ('STATUS', 'ABOGADO', 'GET', 1),
    ('STATUS', 'ABOGADO', 'PATCH', 0),
    ('STATUS', 'ABOGADO', 'DELETE', 0),
    ('SUBCATEGORY', 'ABOGADO', 'POST', 0),
    ('SUBCATEGORY', 'ABOGADO', 'GET', 1),
    ('SUBCATEGORY', 'ABOGADO', 'PATCH', 0),
    ('SUBCATEGORY', 'ABOGADO', 'DELETE', 0),
    ('USER', 'ABOGADO', 'POST', 0),
    ('USER', 'ABOGADO', 'GET', 1),
    ('USER', 'ABOGADO', 'PATCH', 0),
    ('USER', 'ABOGADO', 'DELETE', 0),
    ('USERS-BUYED', 'ABOGADO', 'POST', 0),
    ('USERS-BUYED', 'ABOGADO', 'GET', 1),
    ('USERS-BUYED', 'ABOGADO', 'PATCH', 0),
    ('USERS-BUYED', 'ABOGADO', 'DELETE', 0),
    ('WHITE-LIST', 'ABOGADO', 'POST', 0),
    ('WHITE-LIST', 'ABOGADO', 'GET', 1),
    ('WHITE-LIST', 'ABOGADO', 'PATCH', 0),
    ('WHITE-LIST', 'ABOGADO', 'DELETE', 0),
    ('PQR', 'ABOGADO', 'POST', 0),
    ('PQR', 'ABOGADO', 'GET', 1),
    ('PQR', 'ABOGADO', 'PATCH', 0),
    ('PQR', 'ABOGADO', 'DELETE', 0),
    ('BUYER', 'OPERATIVO', 'POST', 1),
    ('BUYER', 'OPERATIVO', 'GET', 1),
    ('BUYER', 'OPERATIVO', 'PATCH', 1),
    ('BUYER', 'OPERATIVO', 'DELETE', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'POST', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'GET', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'DELETE', 1),
    ('CATEGORY', 'OPERATIVO', 'POST', 0),
    ('CATEGORY', 'OPERATIVO', 'GET', 1),
    ('CATEGORY', 'OPERATIVO', 'PATCH', 0),
    ('CATEGORY', 'OPERATIVO', 'DELETE', 0),
    ('CITY', 'OPERATIVO', 'POST', 1),
    ('CITY', 'OPERATIVO', 'GET', 1),
    ('CITY', 'OPERATIVO', 'PATCH', 1),
    ('CITY', 'OPERATIVO', 'DELETE', 1),
    ('COMPANY', 'OPERATIVO', 'POST', 1),
    ('COMPANY', 'OPERATIVO', 'GET', 1),
    ('COMPANY', 'OPERATIVO', 'PATCH', 1),
    ('COMPANY', 'OPERATIVO', 'DELETE', 1),
    ('COUNTRY', 'OPERATIVO', 'POST', 1),
    ('COUNTRY', 'OPERATIVO', 'GET', 1),
    ('COUNTRY', 'OPERATIVO', 'PATCH', 1),
    ('COUNTRY', 'OPERATIVO', 'DELETE', 1),
    ('CREDENTIALS', 'OPERATIVO', 'POST', 1),
    ('CREDENTIALS', 'OPERATIVO', 'GET', 1),
    ('CREDENTIALS', 'OPERATIVO', 'PATCH', 1),
    ('CREDENTIALS', 'OPERATIVO', 'DELETE', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'POST', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'GET', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'PATCH', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'DELETE', 1),
    ('DEMAND', 'OPERATIVO', 'POST', 0),
    ('DEMAND', 'OPERATIVO', 'GET', 1),
    ('DEMAND', 'OPERATIVO', 'PATCH', 0),
    ('DEMAND', 'OPERATIVO', 'DELETE', 0),
    ('ELEMENT', 'OPERATIVO', 'POST', 1),
    ('ELEMENT', 'OPERATIVO', 'GET', 1),
    ('ELEMENT', 'OPERATIVO', 'PATCH', 1),
    ('ELEMENT', 'OPERATIVO', 'DELETE', 1),
    ('EMPLOYEE', 'OPERATIVO', 'POST', 0),
    ('EMPLOYEE', 'OPERATIVO', 'GET', 1),
    ('EMPLOYEE', 'OPERATIVO', 'PATCH', 0),
    ('EMPLOYEE', 'OPERATIVO', 'DELETE', 0),
    ('ERROR-LOG', 'OPERATIVO', 'POST', 0),
    ('ERROR-LOG', 'OPERATIVO', 'GET', 0),
    ('ERROR-LOG', 'OPERATIVO', 'PATCH', 0),
    ('ERROR-LOG', 'OPERATIVO', 'DELETE', 0),
    ('FAQ', 'OPERATIVO', 'POST', 1),
    ('FAQ', 'OPERATIVO', 'GET', 1),
    ('FAQ', 'OPERATIVO', 'PATCH', 1),
    ('FAQ', 'OPERATIVO', 'DELETE', 1),
    ('GENDER', 'OPERATIVO', 'POST', 1),
    ('GENDER', 'OPERATIVO', 'GET', 1),
    ('GENDER', 'OPERATIVO', 'PATCH', 1),
    ('GENDER', 'OPERATIVO', 'DELETE', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'POST', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'GET', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'PATCH', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'DELETE', 1),
    ('OBJECT', 'OPERATIVO', 'POST', 0),
    ('OBJECT', 'OPERATIVO', 'GET', 0),
    ('OBJECT', 'OPERATIVO', 'PATCH', 0),
    ('OBJECT', 'OPERATIVO', 'DELETE', 0),
    ('PERSON', 'OPERATIVO', 'POST', 1),
    ('PERSON', 'OPERATIVO', 'GET', 1),
    ('PERSON', 'OPERATIVO', 'PATCH', 1),
    ('PERSON', 'OPERATIVO', 'DELETE', 1),
    ('PLAN', 'OPERATIVO', 'POST', 1),
    ('PLAN', 'OPERATIVO', 'GET', 1),
    ('PLAN', 'OPERATIVO', 'PATCH', 1),
    ('PLAN', 'OPERATIVO', 'DELETE', 1),
    ('POLITIC', 'OPERATIVO', 'POST', 1),
    ('POLITIC', 'OPERATIVO', 'GET', 1),
    ('POLITIC', 'OPERATIVO', 'PATCH', 1),
    ('POLITIC', 'OPERATIVO', 'DELETE', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'POST', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'GET', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'PATCH', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'DELETE', 1),
    ('POLITICS-ACCEPTED', 'OPERATIVO', 'POST', 0),
    ('POLITICS-ACCEPTED', 'OPERATIVO', 'GET', 1),
    ('POLITICS-ACCEPTED', 'OPERATIVO', 'PATCH', 0),
    ('POLITICS-ACCEPTED', 'OPERATIVO', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'POST', 1),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'GET', 1),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'PATCH', 1),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'DELETE', 1),
    ('REQUEST', 'OPERATIVO', 'POST', 1),
    ('REQUEST', 'OPERATIVO', 'GET', 1),
    ('REQUEST', 'OPERATIVO', 'PATCH', 1),
    ('REQUEST', 'OPERATIVO', 'DELETE', 0),
    ('REQUIREMENT', 'OPERATIVO', 'POST', 1),
    ('REQUIREMENT', 'OPERATIVO', 'GET', 1),
    ('REQUIREMENT', 'OPERATIVO', 'PATCH', 1),
    ('REQUIREMENT', 'OPERATIVO', 'DELETE', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'POST', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'GET', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'PATCH', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'DELETE', 1),
    ('REWARD', 'OPERATIVO', 'POST', 1),
    ('REWARD', 'OPERATIVO', 'GET', 1),
    ('REWARD', 'OPERATIVO', 'PATCH', 0),
    ('REWARD', 'OPERATIVO', 'DELETE', 0),
    ('REWARD-CURRENCY', 'OPERATIVO', 'POST', 1),
    ('REWARD-CURRENCY', 'OPERATIVO', 'GET', 1),
    ('REWARD-CURRENCY', 'OPERATIVO', 'PATCH', 1),
    ('REWARD-CURRENCY', 'OPERATIVO', 'DELETE', 1),
    ('ROLE', 'OPERATIVO', 'POST', 1),
    ('ROLE', 'OPERATIVO', 'GET', 1),
    ('ROLE', 'OPERATIVO', 'PATCH', 1),
    ('ROLE', 'OPERATIVO', 'DELETE', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'POST', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'GET', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'PATCH', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'DELETE', 1),
    ('SELECTION', 'OPERATIVO', 'POST', 1),
    ('SELECTION', 'OPERATIVO', 'GET', 1),
    ('SELECTION', 'OPERATIVO', 'PATCH', 1),
    ('SELECTION', 'OPERATIVO', 'DELETE', 1),
    (
        'SHOPPING-DEMAND-HISTORY',
        'OPERATIVO',
        'POST',
        0
    ),
    ('SHOPPING-DEMAND-HISTORY', 'OPERATIVO', 'GET', 1),
    (
        'SHOPPING-DEMAND-HISTORY',
        'OPERATIVO',
        'PATCH',
        0
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'OPERATIVO',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'POST', 0),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'GET', 1),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'DELETE', 0),
    ('STATE', 'OPERATIVO', 'POST', 1),
    ('STATE', 'OPERATIVO', 'GET', 1),
    ('STATE', 'OPERATIVO', 'PATCH', 1),
    ('STATE', 'OPERATIVO', 'DELETE', 1),
    ('STATUS', 'OPERATIVO', 'POST', 1),
    ('STATUS', 'OPERATIVO', 'GET', 1),
    ('STATUS', 'OPERATIVO', 'PATCH', 1),
    ('STATUS', 'OPERATIVO', 'DELETE', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'POST', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'GET', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'PATCH', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'DELETE', 1),
    ('USER', 'OPERATIVO', 'POST', 1),
    ('USER', 'OPERATIVO', 'GET', 1),
    ('USER', 'OPERATIVO', 'PATCH', 1),
    ('USER', 'OPERATIVO', 'DELETE', 1),
    ('USERS-BUYED', 'OPERATIVO', 'POST', 0),
    ('USERS-BUYED', 'OPERATIVO', 'GET', 1),
    ('USERS-BUYED', 'OPERATIVO', 'PATCH', 0),
    ('USERS-BUYED', 'OPERATIVO', 'DELETE', 0),
    ('WHITE-LIST', 'OPERATIVO', 'POST', 0),
    ('WHITE-LIST', 'OPERATIVO', 'GET', 1),
    ('WHITE-LIST', 'OPERATIVO', 'PATCH', 0),
    ('WHITE-LIST', 'OPERATIVO', 'DELETE', 0),
    ('PQR', 'OPERATIVO', 'POST', 1),
    ('PQR', 'OPERATIVO', 'GET', 1),
    ('PQR', 'OPERATIVO', 'PATCH', 1),
    ('PQR', 'OPERATIVO', 'DELETE', 1),
    ('BUYER', 'ADMINISTRATIVO', 'POST', 1),
    ('BUYER', 'ADMINISTRATIVO', 'GET', 1),
    ('BUYER', 'ADMINISTRATIVO', 'PATCH', 1),
    ('BUYER', 'ADMINISTRATIVO', 'DELETE', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'POST', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'GET', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'DELETE', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'POST', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'GET', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('CITY', 'ADMINISTRATIVO', 'POST', 1),
    ('CITY', 'ADMINISTRATIVO', 'GET', 1),
    ('CITY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('CITY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'POST', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'GET', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'POST', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'GET', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'POST', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'GET', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'PATCH', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'DELETE', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'POST', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'GET', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'POST', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'GET', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'PATCH', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'POST', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'GET', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'POST', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'GET', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'POST', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'GET', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'DELETE', 1),
    ('FAQ', 'ADMINISTRATIVO', 'POST', 1),
    ('FAQ', 'ADMINISTRATIVO', 'GET', 1),
    ('FAQ', 'ADMINISTRATIVO', 'PATCH', 1),
    ('FAQ', 'ADMINISTRATIVO', 'DELETE', 1),
    ('GENDER', 'ADMINISTRATIVO', 'POST', 1),
    ('GENDER', 'ADMINISTRATIVO', 'GET', 1),
    ('GENDER', 'ADMINISTRATIVO', 'PATCH', 1),
    ('GENDER', 'ADMINISTRATIVO', 'DELETE', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'POST', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'GET', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'POST', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'GET', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('PERSON', 'ADMINISTRATIVO', 'POST', 1),
    ('PERSON', 'ADMINISTRATIVO', 'GET', 1),
    ('PERSON', 'ADMINISTRATIVO', 'PATCH', 1),
    ('PERSON', 'ADMINISTRATIVO', 'DELETE', 1),
    ('PLAN', 'ADMINISTRATIVO', 'POST', 1),
    ('PLAN', 'ADMINISTRATIVO', 'GET', 1),
    ('PLAN', 'ADMINISTRATIVO', 'PATCH', 1),
    ('PLAN', 'ADMINISTRATIVO', 'DELETE', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'POST', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'GET', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'PATCH', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'DELETE', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'POST', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'GET', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('POLITICS-ACCEPTED', 'ADMINISTRATIVO', 'POST', 1),
    ('POLITICS-ACCEPTED', 'ADMINISTRATIVO', 'GET', 1),
    (
        'POLITICS-ACCEPTED',
        'ADMINISTRATIVO',
        'PATCH',
        1
    ),
    (
        'POLITICS-ACCEPTED',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('REDEEMED-HISTORY', 'ADMINISTRATIVO', 'POST', 1),
    ('REDEEMED-HISTORY', 'ADMINISTRATIVO', 'GET', 1),
    ('REDEEMED-HISTORY', 'ADMINISTRATIVO', 'PATCH', 1),
    (
        'REDEEMED-HISTORY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('REQUEST', 'ADMINISTRATIVO', 'POST', 1),
    ('REQUEST', 'ADMINISTRATIVO', 'GET', 1),
    ('REQUEST', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REQUEST', 'ADMINISTRATIVO', 'DELETE', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'POST', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'GET', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('REQUIREMENT-BODY', 'ADMINISTRATIVO', 'POST', 1),
    ('REQUIREMENT-BODY', 'ADMINISTRATIVO', 'GET', 1),
    ('REQUIREMENT-BODY', 'ADMINISTRATIVO', 'PATCH', 1),
    (
        'REQUIREMENT-BODY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('REWARD', 'ADMINISTRATIVO', 'POST', 1),
    ('REWARD', 'ADMINISTRATIVO', 'GET', 1),
    ('REWARD', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REWARD', 'ADMINISTRATIVO', 'DELETE', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'POST', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'GET', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ROLE', 'ADMINISTRATIVO', 'POST', 1),
    ('ROLE', 'ADMINISTRATIVO', 'GET', 1),
    ('ROLE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ROLE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'POST', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'GET', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'DELETE', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'POST', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'GET', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'PATCH', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'DELETE', 1),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'POST',
        1
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'GET',
        1
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'PATCH',
        1
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('SHOPPINGHISTORY', 'ADMINISTRATIVO', 'POST', 1),
    ('SHOPPINGHISTORY', 'ADMINISTRATIVO', 'GET', 1),
    ('SHOPPINGHISTORY', 'ADMINISTRATIVO', 'PATCH', 1),
    (
        'SHOPPINGHISTORY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('STATE', 'ADMINISTRATIVO', 'POST', 1),
    ('STATE', 'ADMINISTRATIVO', 'GET', 1),
    ('STATE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('STATE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('STATUS', 'ADMINISTRATIVO', 'POST', 1),
    ('STATUS', 'ADMINISTRATIVO', 'GET', 1),
    ('STATUS', 'ADMINISTRATIVO', 'PATCH', 1),
    ('STATUS', 'ADMINISTRATIVO', 'DELETE', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'POST', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'GET', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('USER', 'ADMINISTRATIVO', 'POST', 1),
    ('USER', 'ADMINISTRATIVO', 'GET', 1),
    ('USER', 'ADMINISTRATIVO', 'PATCH', 1),
    ('USER', 'ADMINISTRATIVO', 'DELETE', 1),
    ('USERS-BUYED', 'ADMINISTRATIVO', 'POST', 1),
    ('USERS-BUYED', 'ADMINISTRATIVO', 'GET', 1),
    ('USERS-BUYED', 'ADMINISTRATIVO', 'PATCH', 1),
    ('USERS-BUYED', 'ADMINISTRATIVO', 'DELETE', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'POST', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'GET', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'PATCH', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'DELETE', 1),
    ('PQR', 'ADMINISTRATIVO', 'POST', 1),
    ('PQR', 'ADMINISTRATIVO', 'GET', 1),
    ('PQR', 'ADMINISTRATIVO', 'PATCH', 1),
    ('PQR', 'ADMINISTRATIVO', 'DELETE', 1),
    ('BUYER', 'BUYER', 'POST', 1),
    ('BUYER', 'BUYER', 'GET', 0),
    ('BUYER', 'BUYER', 'PATCH', 1),
    ('BUYER', 'BUYER', 'DELETE', 0),
    ('BUYERCREDENTIAL', 'BUYER', 'POST', 1),
    ('BUYERCREDENTIAL', 'BUYER', 'GET', 0),
    ('BUYERCREDENTIAL', 'BUYER', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'BUYER', 'DELETE', 0),
    ('CATEGORY', 'BUYER', 'POST', 0),
    ('CATEGORY', 'BUYER', 'GET', 1),
    ('CATEGORY', 'BUYER', 'PATCH', 0),
    ('CATEGORY', 'BUYER', 'DELETE', 0),
    ('CITY', 'BUYER', 'POST', 0),
    ('CITY', 'BUYER', 'GET', 1),
    ('CITY', 'BUYER', 'PATCH', 0),
    ('CITY', 'BUYER', 'DELETE', 0),
    ('COMPANY', 'BUYER', 'POST', 1),
    ('COMPANY', 'BUYER', 'GET', 0),
    ('COMPANY', 'BUYER', 'PATCH', 1);

INSERT INTO
    role_permission
VALUES
    ('COMPANY', 'BUYER', 'DELETE', 0),
    ('COUNTRY', 'BUYER', 'POST', 0),
    ('COUNTRY', 'BUYER', 'GET', 1),
    ('COUNTRY', 'BUYER', 'PATCH', 0),
    ('COUNTRY', 'BUYER', 'DELETE', 0),
    ('CREDENTIALS', 'BUYER', 'POST', 0),
    ('CREDENTIALS', 'BUYER', 'GET', 0),
    ('CREDENTIALS', 'BUYER', 'PATCH', 0),
    ('CREDENTIALS', 'BUYER', 'DELETE', 0),
    ('DATABASE-TYPE', 'BUYER', 'POST', 0),
    ('DATABASE-TYPE', 'BUYER', 'GET', 1),
    ('DATABASE-TYPE', 'BUYER', 'PATCH', 0),
    ('DATABASE-TYPE', 'BUYER', 'DELETE', 0),
    ('DEMAND', 'BUYER', 'POST', 0),
    ('DEMAND', 'BUYER', 'GET', 0),
    ('DEMAND', 'BUYER', 'PATCH', 0),
    ('DEMAND', 'BUYER', 'DELETE', 0),
    ('ELEMENT', 'BUYER', 'POST', 0),
    ('ELEMENT', 'BUYER', 'GET', 1),
    ('ELEMENT', 'BUYER', 'PATCH', 0),
    ('ELEMENT', 'BUYER', 'DELETE', 0),
    ('EMPLOYEE', 'BUYER', 'POST', 0),
    ('EMPLOYEE', 'BUYER', 'GET', 0),
    ('EMPLOYEE', 'BUYER', 'PATCH', 0),
    ('EMPLOYEE', 'BUYER', 'DELETE', 0),
    ('ERROR-LOG', 'BUYER', 'POST', 0),
    ('ERROR-LOG', 'BUYER', 'GET', 0),
    ('ERROR-LOG', 'BUYER', 'PATCH', 0),
    ('ERROR-LOG', 'BUYER', 'DELETE', 0),
    ('FAQ', 'BUYER', 'POST', 0),
    ('FAQ', 'BUYER', 'GET', 1),
    ('FAQ', 'BUYER', 'PATCH', 0),
    ('FAQ', 'BUYER', 'DELETE', 0),
    ('GENDER', 'BUYER', 'POST', 0),
    ('GENDER', 'BUYER', 'GET', 1),
    ('GENDER', 'BUYER', 'PATCH', 0),
    ('GENDER', 'BUYER', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'BUYER', 'POST', 0),
    ('IDENT-DOCUMENT', 'BUYER', 'GET', 1),
    ('IDENT-DOCUMENT', 'BUYER', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'BUYER', 'DELETE', 0),
    ('OBJECT', 'BUYER', 'POST', 0),
    ('OBJECT', 'BUYER', 'GET', 0),
    ('OBJECT', 'BUYER', 'PATCH', 0),
    ('OBJECT', 'BUYER', 'DELETE', 0),
    ('PERSON', 'BUYER', 'POST', 0),
    ('PERSON', 'BUYER', 'GET', 0),
    ('PERSON', 'BUYER', 'PATCH', 0),
    ('PERSON', 'BUYER', 'DELETE', 0),
    ('PLAN', 'BUYER', 'POST', 0),
    ('PLAN', 'BUYER', 'GET', 0),
    ('PLAN', 'BUYER', 'PATCH', 0),
    ('PLAN', 'BUYER', 'DELETE', 0),
    ('POLITIC', 'BUYER', 'POST', 0),
    ('POLITIC', 'BUYER', 'GET', 0),
    ('POLITIC', 'BUYER', 'PATCH', 0),
    ('POLITIC', 'BUYER', 'DELETE', 0),
    ('POLITIC-BODY', 'BUYER', 'POST', 0),
    ('POLITIC-BODY', 'BUYER', 'GET', 0),
    ('POLITIC-BODY', 'BUYER', 'PATCH', 0),
    ('POLITIC-BODY', 'BUYER', 'DELETE', 0),
    ('POLITICS-ACCEPTED', 'BUYER', 'POST', 1),
    ('POLITICS-ACCEPTED', 'BUYER', 'GET', 0),
    ('POLITICS-ACCEPTED', 'BUYER', 'PATCH', 0),
    ('POLITICS-ACCEPTED', 'BUYER', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'POST', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'GET', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'DELETE', 0),
    ('REQUEST', 'BUYER', 'POST', 1),
    ('REQUEST', 'BUYER', 'GET', 1),
    ('REQUEST', 'BUYER', 'PATCH', 0),
    ('REQUEST', 'BUYER', 'DELETE', 0),
    ('REQUIREMENT', 'BUYER', 'POST', 0),
    ('REQUIREMENT', 'BUYER', 'GET', 1),
    ('REQUIREMENT', 'BUYER', 'PATCH', 0),
    ('REQUIREMENT', 'BUYER', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'BUYER', 'POST', 0),
    ('REQUIREMENT-BODY', 'BUYER', 'GET', 1),
    ('REQUIREMENT-BODY', 'BUYER', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'BUYER', 'DELETE', 0),
    ('REWARD', 'BUYER', 'POST', 0),
    ('REWARD', 'BUYER', 'GET', 0),
    ('REWARD', 'BUYER', 'PATCH', 0),
    ('REWARD', 'BUYER', 'DELETE', 0),
    ('REWARD-CURRENCY', 'BUYER', 'POST', 0),
    ('REWARD-CURRENCY', 'BUYER', 'GET', 0),
    ('REWARD-CURRENCY', 'BUYER', 'PATCH', 0),
    ('REWARD-CURRENCY', 'BUYER', 'DELETE', 0),
    ('ROLE', 'BUYER', 'POST', 0),
    ('ROLE', 'BUYER', 'GET', 0),
    ('ROLE', 'BUYER', 'PATCH', 0),
    ('ROLE', 'BUYER', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'POST', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'GET', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'DELETE', 0),
    ('SELECTION', 'BUYER', 'POST', 1),
    ('SELECTION', 'BUYER', 'GET', 1),
    ('SELECTION', 'BUYER', 'PATCH', 0),
    ('SELECTION', 'BUYER', 'DELETE', 1),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'PATCH', 0),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'DELETE', 0),
    ('SHOPPINGHISTORY', 'BUYER', 'POST', 1),
    ('SHOPPINGHISTORY', 'BUYER', 'GET', 1),
    ('SHOPPINGHISTORY', 'BUYER', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'BUYER', 'DELETE', 0),
    ('STATE', 'BUYER', 'POST', 0),
    ('STATE', 'BUYER', 'GET', 1),
    ('STATE', 'BUYER', 'PATCH', 0),
    ('STATE', 'BUYER', 'DELETE', 0),
    ('STATUS', 'BUYER', 'POST', 0),
    ('STATUS', 'BUYER', 'GET', 1),
    ('STATUS', 'BUYER', 'PATCH', 0),
    ('STATUS', 'BUYER', 'DELETE', 0),
    ('SUBCATEGORY', 'BUYER', 'POST', 0),
    ('SUBCATEGORY', 'BUYER', 'GET', 1),
    ('SUBCATEGORY', 'BUYER', 'PATCH', 0),
    ('SUBCATEGORY', 'BUYER', 'DELETE', 0),
    ('USER', 'BUYER', 'POST', 0),
    ('USER', 'BUYER', 'GET', 0),
    ('USER', 'BUYER', 'PATCH', 0),
    ('USER', 'BUYER', 'DELETE', 0),
    ('USERS-BUYED', 'BUYER', 'POST', 0),
    ('USERS-BUYED', 'BUYER', 'GET', 0),
    ('USERS-BUYED', 'BUYER', 'PATCH', 0),
    ('USERS-BUYED', 'BUYER', 'DELETE', 0),
    ('WHITE-LIST', 'BUYER', 'POST', 0),
    ('WHITE-LIST', 'BUYER', 'GET', 0),
    ('WHITE-LIST', 'BUYER', 'PATCH', 0),
    ('WHITE-LIST', 'BUYER', 'DELETE', 0),
    ('PQR', 'BUYER', 'POST', 0),
    ('PQR', 'BUYER', 'GET', 1),
    ('PQR', 'BUYER', 'PATCH', 0),
    ('PQR', 'BUYER', 'DELETE', 0);

INSERT INTO
    [dbo].[politic] ([politicName])
VALUES
    ('GENERAL-USER'),
    ('GENERAL-BUYER'),
    ('PREMIUM-USER'),
    ('PLUS-USER'),
    ('CONTROL-USER'),
    ('DATA-USER'),
    ('DATA-CONTROL'),
    ('DATA-PLUS'),
    ('DATA-PREMIUM'),
    ('MOVISTAR-USER');

INSERT INTO
    [dbo].[politic_body] (
        [politicText],
        [politicVersion],
        [politicState],
        [politicId]
    )
VALUES
    ('politics/GENERAL-USER.pdf','1.0', 1, 1),
    ('politics/GENERAL-BUYER.pdf','1.0', 1, 2),
    ('politics/PREMIUM-USER.pdf','1.0', 0, 3),
    ('politics/PLUS-USER.pdf','1.0', 1, 4),
    ('politics/CONTROL-USER.pdf','1.0', 1, 5),
    ('politics/DATA-USER.pdf','1.0', 1, 6),
    ('politics/PREMIUM-USER.pdf','2.0', 1, 3),
    ('politics/DATA-CONTROL.pdf','1.0', 1, 7),
    ('politics/DATA-PLUS.pdf','1.0', 1, 8),
    ('politics/DATA-PREMIUM.pdf','1.0', 1, 9),
    (
       'politics/MOVISTAR-USER.pdf',
       '1.0',
        1,
        10
    );

INSERT INTO
    [dbo].[sponsor_code] (
        [sponsorCode],
        [documentNumber],
        [companyId]
    )
VALUES
    (
        'MOV123456',
        '1234567890',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    ),
    (
        'MOV123457',
        '1122334455',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    ),
    (
        'MOV123458',
        '987654321',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    );

INSERT INTO
    [dbo].[company_competence] (
        [companyCompetenceId],
        [competenceId],
        [companyId]
    )
VALUES
    (
        '3934433e-f36b-1410-87a6-0065356853cd',
        'c075433e-f36b-1410-81c2-009e18c9ad57',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    ),
    (
        '3c34433e-f36b-1410-87a6-0065356853cd',
        'c675433e-f36b-1410-81c2-009e18c9ad57',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    ),
    (
        '3f34433e-f36b-1410-87a6-0065356853cd',
        'e475433e-f36b-1410-81c2-009e18c9ad57',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    ),
    (
        '4234433e-f36b-1410-87a6-0065356853cd',
        'fc75433e-f36b-1410-81c2-009e18c9ad57',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    ),
    (
        '4534433e-f36b-1410-87a6-0065356853cd',
        '0876433e-f36b-1410-81c2-009e18c9ad57',
        '0e76433e-f36b-1410-81c2-009e18c9ad57'
    );

INSERT INTO
    [dbo].[bd_price] (
        [bdPriceMinUsers],
        [bdPriceMaxUsers],
        [bdPriceValue],
        [bdPriceActive],
        [databaseId]
    )
VALUES
    (0, 100, 1000, 1, 1),
    (101, 500, 2000, 1, 1),
    (501, 1000, 3000, 1, 1),
    (1001, 5000, 4000, 1, 1),
    (5001, 10000, 5000, 1, 1),
    (10001, 1000000, 6000, 1, 1),
    (0, 100, 1100, 1, 2),
    (101, 500, 2100, 1, 2),
    (501, 1000, 3100, 1, 2),
    (1001, 5000, 4100, 1, 2),
    (5001, 10000, 5100, 1, 2),
    (10001, 1000000, 6100, 1, 2),
    (0, 100, 10000, 0, 1),
    (101, 500, 20000, 0, 1),
    (501, 1000, 30000, 0, 1),
    (1001, 5000, 40000, 0, 1),
    (5001, 10000, 50000, 0, 1),
    (10001, 1000000, 60000, 0, 1),
    (0, 100, 11000, 0, 2),
    (101, 500, 21000, 0, 2),
    (501, 1000, 31000, 0, 2),
    (1001, 5000, 41000, 0, 2),
    (5001, 10000, 51000, 0, 2),
    (10001, 1000000, 61000, 0, 2);