USE tudata;

INSERT INTO
    dbo.country ("countryName")
VALUES
    ('Colombia');

INSERT INTO
    dbo.state ("stateName", "CountryId")
VALUES
    ('Amazonas', 1),
    ('Antioquia', 1),
    ('Arauca', 1),
    ('Atlántico', 1),
    ('Bogotá D.C.', 1),
    ('Bolívar', 1),
    ('Boyacá', 1),
    ('Caldas', 1),
    ('Caquetá', 1),
    ('Casanare', 1),
    ('Cauca', 1),
    ('Cesar', 1),
    ('Chocó', 1),
    ('Córdoba', 1),
    ('Cundinamarca', 1),
    ('Guainía', 1),
    ('Guaviare', 1),
    ('Huila', 1),
    ('La Guajira', 1),
    ('Magdalena', 1),
    ('Meta', 1),
    ('Nariño', 1),
    ('Norte de Santander', 1),
    ('Putumayo', 1),
    ('Quindío', 1),
    ('Risaralda', 1),
    ('San Andrés y Providencia', 1),
    ('Santander', 1),
    ('Sucre', 1),
    ('Tolima', 1),
    ('Valle del Cauca', 1),
    ('Vaupés', 1),
    ('Vichada', 1);

INSERT INTO
    dbo.city("cityName", "stateId")
VALUES
    ('Leticia', 1),
    ('El Encanto', 1),
    ('La Chorrera', 1),
    ('La Pedrera', 1),
    ('La Victoria', 1),
    ('Puerto Arica', 1),
    ('Puerto Nariño', 1),
    ('Puerto Santander', 1),
    ('Tarapacá', 1),
    ('Puerto Alegría', 1),
    ('Miriti Paraná', 1),
    ('Aburrá', 2),
    ('Medellín', 2),
    ('Abejorral', 2),
    ('Abriaquí', 2),
    ('Alejandría', 2),
    ('Amagá', 2),
    ('Amalfi', 2),
    ('Andes', 2),
    ('Angelópolis', 2),
    ('Angostura', 2),
    ('Anorí', 2),
    ('Anza', 2),
    ('Apartadó', 2),
    ('Arboletes', 2),
    ('Argelia', 2),
    ('Armenia', 2),
    ('Barbosa', 2),
    ('Bello', 2),
    ('Betania', 2),
    ('Betulia', 2),
    ('Ciudad Bolívar', 2),
    ('Briceño', 2),
    ('Buriticá', 2),
    ('Cáceres', 2),
    ('Caicedo', 2),
    ('Caldas', 2),
    ('Campamento', 2),
    ('Cañasgordas', 2),
    ('Caracolí', 2),
    ('Caramanta', 2),
    ('Carepa', 2),
    ('Carolina', 2),
    ('Caucasia', 2),
    ('Chigorodó', 2),
    ('Cisneros', 2),
    ('Cocorná', 2),
    ('Concepción', 2),
    ('Concordia', 2),
    ('Copacabana', 2),
    ('Dabeiba', 2),
    ('Don Matías', 2),
    ('Ebéjico', 2),
    ('El Bagre', 2),
    ('Entrerrios', 2),
    ('Envigado', 2),
    ('Fredonia', 2),
    ('Giraldo', 2),
    ('Girardota', 2),
    ('Gómez Plata', 2),
    ('Guadalupe', 2),
    ('Guarne', 2),
    ('Guatapé', 2),
    ('Heliconia', 2),
    ('Hispania', 2),
    ('Itagui', 2),
    ('Ituango', 2),
    ('Belmira', 2),
    ('Jericó', 2),
    ('La Ceja', 2),
    ('La Estrella', 2),
    ('La Pintada', 2),
    ('La Unión', 2),
    ('Liborina', 2),
    ('Maceo', 2),
    ('Marinilla', 2),
    ('Montebello', 2),
    ('Murindó', 2),
    ('Mutatá', 2),
    ('Nariño', 2),
    ('Necoclí', 2),
    ('Nechí', 2),
    ('Olaya', 2),
    ('Peñol', 2),
    ('Peque', 2),
    ('Pueblorrico', 2),
    ('Puerto Berrío', 2),
    ('Puerto Nare', 2),
    ('Puerto Triunfo', 2),
    ('Remedios', 2),
    ('Retiro', 2),
    ('Rionegro', 2),
    ('Sabanalarga', 2),
    ('Sabaneta', 2),
    ('Salgar', 2),
    ('San Francisco', 2),
    ('San Jerónimo', 2),
    ('San Luis', 2),
    ('San Pedro', 2),
    ('San Rafael', 2),
    ('San Roque', 2),
    ('San Vicente', 2),
    ('Santa Bárbara', 2),
    ('Santo Domingo', 2),
    ('El Santuario', 2),
    ('Segovia', 2),
    ('Sopetrán', 2),
    ('Támesis', 2),
    ('Tarazá', 2),
    ('Tarso', 2),
    ('Titiribí', 2),
    ('Toledo', 2),
    ('Turbo', 2),
    ('Uramita', 2),
    ('Urrao', 2),
    ('Valdivia', 2),
    ('Valparaíso', 2),
    ('Vegachí', 2),
    ('Venecia', 2),
    ('Yalí', 2),
    ('Yarumal', 2),
    ('Yolombó', 2),
    ('Yondó', 2),
    ('Zaragoza', 2),
    ('San Pedro de Uraba', 2),
    ('Santafé de Antioquia', 2),
    ('Santa Rosa de Osos', 2),
    ('San Andrés de Cuerquía', 2),
    ('Vigía del Fuerte', 2),
    ('San José de La Montaña', 2),
    ('San Juan de Urabá', 2),
    ('El Carmen de Viboral', 2),
    ('San Carlos', 2),
    ('Frontino', 2),
    ('Granada', 2),
    ('Jardín', 2),
    ('Sonsón', 2),
    ('Arauquita', 3),
    ('Cravo Norte', 3),
    ('Fortul', 3),
    ('Puerto Rondón', 3),
    ('Saravena', 3),
    ('Tame', 3),
    ('Arauca', 3),
    ('Barranquilla', 4),
    ('Baranoa', 4),
    ('Candelaria', 4),
    ('Galapa', 4),
    ('Luruaco', 4),
    ('Malambo', 4),
    ('Manatí', 4),
    ('Piojó', 4),
    ('Polonuevo', 4),
    ('Sabanagrande', 4),
    ('Sabanalarga', 4),
    ('Santa Lucía', 4),
    ('Santo Tomás', 4),
    ('Soledad', 4),
    ('Suan', 4),
    ('Tubará', 4),
    ('Usiacurí', 4),
    ('Juan de Acosta', 4),
    ('Palmar de Varela', 4),
    ('Campo de La Cruz', 4),
    ('Repelón', 4),
    ('Puerto Colombia', 4),
    ('Ponedera', 4),
    ('Bogotá D.C.', 5),
    ('Achí', 6),
    ('Arenal', 6),
    ('Arjona', 6),
    ('Arroyohondo', 6),
    ('Calamar', 6),
    ('Cantagallo', 6),
    ('Cicuco', 6),
    ('Córdoba', 6),
    ('Clemencia', 6),
    ('El Guamo', 6),
    ('Magangué', 6),
    ('Mahates', 6),
    ('Margarita', 6),
    ('Montecristo', 6),
    ('Mompós', 6),
    ('Morales', 6),
    ('Norosí', 6),
    ('Pinillos', 6),
    ('Regidor', 6),
    ('Río Viejo', 6),
    ('San Estanislao', 6),
    ('San Fernando', 6),
    ('San Juan Nepomuceno', 6),
    ('Santa Catalina', 6),
    ('Santa Rosa', 6),
    ('Simití', 6),
    ('Soplaviento', 6),
    ('Talaigua Nuevo', 6),
    ('Tiquisio', 6),
    ('Turbaco', 6),
    ('Turbaná', 6),
    ('Villanueva', 6),
    ('Barranco de Loba', 6),
    ('Santa Rosa del Sur', 6),
    ('Hatillo de Loba', 6),
    ('El Carmen de Bolívar', 6),
    ('San Martín de Loba', 6),
    ('Altos del Rosario', 6),
    ('San Jacinto del Cauca', 6),
    ('San Pablo de Borbur', 6),
    ('San Jacinto', 6),
    ('El Peñón', 6),
    ('Cartagena', 6),
    ('María la Baja', 6),
    ('San Cristóbal', 6),
    ('Zambrano', 6),
    ('Tununguá', 7),
    ('Motavita', 7),
    ('Ciénega', 7),
    ('Tunja', 7),
    ('Almeida', 7),
    ('Aquitania', 7),
    ('Arcabuco', 7),
    ('Berbeo', 7),
    ('Betéitiva', 7),
    ('Boavita', 7),
    ('Boyacá', 7),
    ('Briceño', 7),
    ('Buena Vista', 7),
    ('Busbanzá', 7),
    ('Caldas', 7),
    ('Campohermoso', 7),
    ('Cerinza', 7),
    ('Chinavita', 7),
    ('Chiquinquirá', 7),
    ('Chiscas', 7),
    ('Chita', 7),
    ('Chitaraque', 7),
    ('Chivatá', 7),
    ('Cómbita', 7),
    ('Coper', 7),
    ('Corrales', 7),
    ('Covarachía', 7),
    ('Cubará', 7),
    ('Cucaita', 7),
    ('Cuítiva', 7),
    ('Chíquiza', 7),
    ('Chivor', 7),
    ('Duitama', 7),
    ('El Cocuy', 7),
    ('El Espino', 7),
    ('Firavitoba', 7),
    ('Floresta', 7),
    ('Gachantivá', 7),
    ('Gameza', 7),
    ('Garagoa', 7),
    ('Guacamayas', 7),
    ('Guateque', 7),
    ('Guayatá', 7),
    ('Güicán', 7),
    ('Iza', 7),
    ('Jenesano', 7),
    ('Jericó', 7),
    ('Labranzagrande', 7),
    ('La Capilla', 7),
    ('La Victoria', 7),
    ('Macanal', 7),
    ('Maripí', 7),
    ('Miraflores', 7),
    ('Mongua', 7),
    ('Monguí', 7),
    ('Moniquirá', 7),
    ('Muzo', 7),
    ('Nobsa', 7),
    ('Nuevo Colón', 7),
    ('Oicatá', 7),
    ('Otanche', 7),
    ('Pachavita', 7),
    ('Páez', 7),
    ('Paipa', 7),
    ('Pajarito', 7),
    ('Panqueba', 7),
    ('Pauna', 7),
    ('Paya', 7),
    ('Pesca', 7),
    ('Pisba', 7),
    ('Puerto Boyacá', 7),
    ('Quípama', 7),
    ('Ramiriquí', 7),
    ('Ráquira', 7),
    ('Rondón', 7),
    ('Saboyá', 7),
    ('Sáchica', 7),
    ('Samacá', 7),
    ('San Eduardo', 7),
    ('San Mateo', 7),
    ('Santana', 7),
    ('Santa María', 7),
    ('Santa Sofía', 7),
    ('Sativanorte', 7),
    ('Sativasur', 7),
    ('Siachoque', 7),
    ('Soatá', 7),
    ('Socotá', 7),
    ('Socha', 7),
    ('Sogamoso', 7),
    ('Somondoco', 7),
    ('Sora', 7),
    ('Sotaquirá', 7),
    ('Soracá', 7),
    ('Susacón', 7),
    ('Sutamarchán', 7),
    ('Sutatenza', 7),
    ('Tasco', 7),
    ('Tenza', 7),
    ('Tibaná', 7),
    ('Tinjacá', 7),
    ('Tipacoque', 7),
    ('Toca', 7),
    ('Tópaga', 7),
    ('Tota', 7),
    ('Turmequé', 7),
    ('Tutazá', 7),
    ('Umbita', 7),
    ('Ventaquemada', 7),
    ('Viracachá', 7),
    ('Zetaquira', 7),
    ('Togüí', 7),
    ('Villa de Leyva', 7),
    ('Paz de Río', 7),
    ('Santa Rosa de Viterbo', 7),
    ('San Pablo de Borbur', 7),
    ('San Luis de Gaceno', 7),
    ('San José de Pare', 7),
    ('San Miguel de Sema', 7),
    ('Tuta', 7),
    ('Tibasosa', 7),
    ('La Uvita', 7),
    ('Belén', 7),
    ('Manizales', 8),
    ('Aguadas', 8),
    ('Anserma', 8),
    ('Aranzazu', 8),
    ('Belalcázar', 8),
    ('Chinchiná', 8),
    ('Filadelfia', 8),
    ('La Dorada', 8),
    ('La Merced', 8),
    ('Manzanares', 8),
    ('Marmato', 8),
    ('Marulanda', 8),
    ('Neira', 8),
    ('Norcasia', 8),
    ('Pácora', 8),
    ('Palestina', 8),
    ('Pensilvania', 8),
    ('Riosucio', 8),
    ('Risaralda', 8),
    ('Salamina', 8),
    ('Samaná', 8),
    ('San José', 8),
    ('Supía', 8),
    ('Victoria', 8),
    ('Villamaría', 8),
    ('Viterbo', 8),
    ('Marquetalia', 8),
    ('Florencia', 9),
    ('Albania', 9),
    ('Curillo', 9),
    ('El Doncello', 9),
    ('El Paujil', 9),
    ('Morelia', 9),
    ('Puerto Rico', 9),
    ('Solano', 9),
    ('Solita', 9),
    ('Valparaíso', 9),
    ('San José del Fragua', 9),
    ('Belén de Los Andaquies', 9),
    ('Cartagena del Chairá', 9),
    ('Milán', 9),
    ('La Montañita', 9),
    ('San Vicente del Caguán', 9),
    ('Yopal', 10),
    ('Aguazul', 10),
    ('Chámeza', 10),
    ('Hato Corozal', 10),
    ('La Salina', 10),
    ('Monterrey', 10),
    ('Pore', 10),
    ('Recetor', 10),
    ('Sabanalarga', 10),
    ('Sácama', 10),
    ('Tauramena', 10),
    ('Trinidad', 10),
    ('Villanueva', 10),
    ('San Luis de Gaceno', 10),
    ('Paz de Ariporo', 10),
    ('Nunchía', 10),
    ('Maní', 10),
    ('Támara', 10),
    ('Orocué', 10),
    ('Popayán', 11),
    ('Almaguer', 11),
    ('Argelia', 11),
    ('Balboa', 11),
    ('Bolívar', 11),
    ('Buenos Aires', 11),
    ('Cajibío', 11),
    ('Caldono', 11),
    ('Caloto', 11),
    ('Corinto', 11),
    ('El Tambo', 11),
    ('Florencia', 11),
    ('Guachené', 11),
    ('Guapi', 11),
    ('Inzá', 11),
    ('Jambaló', 11),
    ('La Sierra', 11),
    ('La Vega', 11),
    ('López', 11),
    ('Mercaderes', 11),
    ('Miranda', 11),
    ('Morales', 11),
    ('Padilla', 11),
    ('Patía', 11),
    ('Piamonte', 11),
    ('Piendamó', 11),
    ('Puerto Tejada', 11),
    ('Puracé', 11),
    ('Rosas', 11),
    ('Santa Rosa', 11),
    ('Silvia', 11),
    ('Sotara', 11),
    ('Suárez', 11),
    ('Sucre', 11),
    ('Timbío', 11),
    ('Timbiquí', 11),
    ('Toribio', 11),
    ('Totoró', 11),
    ('Villa Rica', 11),
    ('Santander de Quilichao', 11),
    ('San Sebastián', 11),
    ('Páez', 11),
    ('Valledupar', 12),
    ('Aguachica', 12),
    ('Agustín Codazzi', 12),
    ('Astrea', 12),
    ('Becerril', 12),
    ('Bosconia', 12),
    ('Chimichagua', 12),
    ('Chiriguaná', 12),
    ('Curumaní', 12),
    ('El Copey', 12),
    ('El Paso', 12),
    ('Gamarra', 12),
    ('González', 12),
    ('La Gloria', 12),
    ('Manaure', 12),
    ('Pailitas', 12),
    ('Pelaya', 12),
    ('Pueblo Bello', 12),
    ('La Paz', 12),
    ('San Alberto', 12),
    ('San Diego', 12),
    ('San Martín', 12),
    ('Tamalameque', 12),
    ('Río de Oro', 12),
    ('La Jagua de Ibirico', 12),
    ('Istmina', 13),
    ('Quibdó', 13),
    ('Acandí', 13),
    ('Alto Baudo', 13),
    ('Atrato', 13),
    ('Bagadó', 13),
    ('Bahía Solano', 13),
    ('Bajo Baudó', 13),
    ('Bojaya', 13),
    ('Cértegui', 13),
    ('Condoto', 13),
    ('Juradó', 13),
    ('Lloró', 13),
    ('Medio Atrato', 13),
    ('Medio Baudó', 13),
    ('Medio San Juan', 13),
    ('Nóvita', 13),
    ('Nuquí', 13),
    ('Río Iro', 13),
    ('Río Quito', 13),
    ('Riosucio', 13),
    ('Sipí', 13),
    ('Unguía', 13),
    ('El Litoral del San Juan', 13),
    ('El Cantón del San Pablo', 13),
    ('El Carmen de Atrato', 13),
    ('San José del Palmar', 13),
    ('Belén de Bajira', 13),
    ('Carmen del Darien', 13),
    ('Tadó', 13),
    ('Unión Panamericana', 13),
    ('San Bernardo del Viento', 14),
    ('Montería', 14),
    ('Ayapel', 14),
    ('Buenavista', 14),
    ('Canalete', 14),
    ('Cereté', 14),
    ('Chimá', 14),
    ('Chinú', 14),
    ('Cotorra', 14),
    ('Lorica', 14),
    ('Los Córdobas', 14),
    ('Momil', 14),
    ('Moñitos', 14),
    ('Planeta Rica', 14),
    ('Pueblo Nuevo', 14),
    ('Puerto Escondido', 14),
    ('Purísima', 14),
    ('Sahagún', 14),
    ('San Andrés Sotavento', 14),
    ('San Antero', 14),
    ('San Pelayo', 14),
    ('Tierralta', 14),
    ('Tuchín', 14),
    ('Valencia', 14),
    ('San José de Uré', 14),
    ('Ciénaga de Oro', 14),
    ('San Carlos', 14),
    ('Montelíbano', 14),
    ('La Apartada', 14),
    ('Puerto Libertador', 14),
    ('Anapoima', 15),
    ('Arbeláez', 15),
    ('Beltrán', 15),
    ('Bituima', 15),
    ('Bojacá', 15),
    ('Cabrera', 15),
    ('Cachipay', 15),
    ('Cajicá', 15),
    ('Caparrapí', 15),
    ('Caqueza', 15),
    ('Chaguaní', 15),
    ('Chipaque', 15),
    ('Choachí', 15),
    ('Chocontá', 15),
    ('Cogua', 15),
    ('Cota', 15),
    ('Cucunubá', 15),
    ('El Colegio', 15),
    ('El Rosal', 15),
    ('Fomeque', 15),
    ('Fosca', 15),
    ('Funza', 15),
    ('Fúquene', 15),
    ('Gachala', 15),
    ('Gachancipá', 15),
    ('Gachetá', 15),
    ('Girardot', 15),
    ('Granada', 15),
    ('Guachetá', 15),
    ('Guaduas', 15),
    ('Guasca', 15),
    ('Guataquí', 15),
    ('Guatavita', 15),
    ('Guayabetal', 15),
    ('Gutiérrez', 15),
    ('Jerusalén', 15),
    ('Junín', 15),
    ('La Calera', 15),
    ('La Mesa', 15),
    ('La Palma', 15),
    ('La Peña', 15),
    ('La Vega', 15),
    ('Lenguazaque', 15),
    ('Macheta', 15),
    ('Madrid', 15),
    ('Manta', 15),
    ('Medina', 15),
    ('Mosquera', 15),
    ('Nariño', 15),
    ('Nemocón', 15),
    ('Nilo', 15),
    ('Nimaima', 15),
    ('Nocaima', 15),
    ('Venecia', 15),
    ('Pacho', 15),
    ('Paime', 15),
    ('Pandi', 15),
    ('Paratebueno', 15),
    ('Pasca', 15),
    ('Puerto Salgar', 15),
    ('Pulí', 15),
    ('Quebradanegra', 15),
    ('Quetame', 15),
    ('Quipile', 15),
    ('Apulo', 15),
    ('Ricaurte', 15),
    ('San Bernardo', 15),
    ('San Cayetano', 15),
    ('San Francisco', 15),
    ('Sesquilé', 15),
    ('Sibaté', 15),
    ('Silvania', 15),
    ('Simijaca', 15),
    ('Soacha', 15),
    ('Subachoque', 15),
    ('Suesca', 15),
    ('Supatá', 15),
    ('Susa', 15),
    ('Sutatausa', 15),
    ('Tabio', 15),
    ('Tausa', 15),
    ('Tena', 15),
    ('Tenjo', 15),
    ('Tibacuy', 15),
    ('Tibirita', 15),
    ('Tocaima', 15),
    ('Tocancipá', 15),
    ('Topaipí', 15),
    ('Ubalá', 15),
    ('Ubaque', 15),
    ('Une', 15),
    ('Útica', 15),
    ('Vianí', 15),
    ('Villagómez', 15),
    ('Villapinzón', 15),
    ('Villeta', 15),
    ('Viotá', 15),
    ('Zipacón', 15),
    ('San Juan de Río Seco', 15),
    ('Villa de San Diego de Ubate', 15),
    ('Guayabal de Siquima', 15),
    ('San Antonio del Tequendama', 15),
    ('Agua de Dios', 15),
    ('Carmen de Carupa', 15),
    ('Vergara', 15),
    ('Albán', 15),
    ('Anolaima', 15),
    ('Chía', 15),
    ('El Peñón', 15),
    ('Sopó', 15),
    ('Gama', 15),
    ('Sasaima', 15),
    ('Yacopí', 15),
    ('Fusagasugá', 15),
    ('Zipaquirá', 15),
    ('Facatativá', 15),
    ('Inírida', 16),
    ('Barranco Minas', 16),
    ('Mapiripana', 16),
    ('San Felipe', 16),
    ('Puerto Colombia', 16),
    ('La Guadalupe', 16),
    ('Cacahual', 16),
    ('Pana Pana', 16),
    ('Morichal', 16),
    ('Calamar', 17),
    ('San José del Guaviare', 17),
    ('Miraflores', 17),
    ('El Retorno', 17),
    ('Neiva', 18),
    ('Acevedo', 18),
    ('Agrado', 18),
    ('Aipe', 18),
    ('Algeciras', 18),
    ('Altamira', 18),
    ('Baraya', 18),
    ('Campoalegre', 18),
    ('Colombia', 18),
    ('Elías', 18),
    ('Garzón', 18),
    ('Gigante', 18),
    ('Guadalupe', 18),
    ('Hobo', 18),
    ('Iquira', 18),
    ('Isnos', 18),
    ('La Argentina', 18),
    ('La Plata', 18),
    ('Nátaga', 18),
    ('Oporapa', 18),
    ('Paicol', 18),
    ('Palermo', 18),
    ('Palestina', 18),
    ('Pital', 18),
    ('Pitalito', 18),
    ('Rivera', 18),
    ('Saladoblanco', 18),
    ('Santa María', 18),
    ('Suaza', 18),
    ('Tarqui', 18),
    ('Tesalia', 18),
    ('Tello', 18),
    ('Teruel', 18),
    ('Timaná', 18),
    ('Villavieja', 18),
    ('Yaguará', 18),
    ('San Agustín', 18),
    ('Riohacha', 19),
    ('Albania', 19),
    ('Barrancas', 19),
    ('Dibula', 19),
    ('Distracción', 19),
    ('El Molino', 19),
    ('Fonseca', 19),
    ('Hatonuevo', 19),
    ('Maicao', 19),
    ('Manaure', 19),
    ('Uribia', 19),
    ('Urumita', 19),
    ('Villanueva', 19),
    ('La Jagua del Pilar', 19),
    ('San Juan del Cesar', 19),
    ('Santa Marta', 20),
    ('Algarrobo', 20),
    ('Aracataca', 20),
    ('Ariguaní', 20),
    ('Cerro San Antonio', 20),
    ('Chivolo', 20),
    ('Concordia', 20),
    ('El Banco', 20),
    ('El Piñon', 20),
    ('El Retén', 20),
    ('Fundación', 20),
    ('Guamal', 20),
    ('Nueva Granada', 20),
    ('Pedraza', 20),
    ('Pivijay', 20),
    ('Plato', 20),
    ('Remolino', 20),
    ('Salamina', 20),
    ('San Zenón', 20),
    ('Santa Ana', 20),
    ('Sitionuevo', 20),
    ('Tenerife', 20),
    ('Zapayán', 20),
    ('Zona Bananera', 20),
    ('San Sebastián de Buenavista', 20),
    ('Sabanas de San Angel', 20),
    ('Pijiño del Carmen', 20),
    ('Santa Bárbara de Pinto', 20),
    ('Pueblo Viejo', 20),
    ('Ciénaga', 20),
    ('Uribe', 21),
    ('Villavicencio', 21),
    ('Acacias', 21),
    ('Cabuyaro', 21),
    ('Cubarral', 21),
    ('Cumaral', 21),
    ('El Calvario', 21),
    ('El Castillo', 21),
    ('El Dorado', 21),
    ('Granada', 21),
    ('Guamal', 21),
    ('Mapiripán', 21),
    ('Mesetas', 21),
    ('La Macarena', 21),
    ('Lejanías', 21),
    ('Puerto Concordia', 21),
    ('Puerto Gaitán', 21),
    ('Puerto López', 21),
    ('Puerto Lleras', 21),
    ('Puerto Rico', 21),
    ('Restrepo', 21),
    ('San Juanito', 21),
    ('San Martín', 21),
    ('Vista Hermosa', 21),
    ('Barranca de Upía', 21),
    ('Fuente de Oro', 21),
    ('San Carlos de Guaroa', 21),
    ('San Juan de Arama', 21),
    ('Castilla la Nueva', 21),
    ('Santacruz', 22),
    ('Pasto', 22),
    ('Albán', 22),
    ('Aldana', 22),
    ('Ancuyá', 22),
    ('Barbacoas', 22),
    ('Colón', 22),
    ('Consaca', 22),
    ('Contadero', 22),
    ('Córdoba', 22),
    ('Cuaspud', 22),
    ('Cumbal', 22),
    ('Cumbitara', 22),
    ('El Charco', 22),
    ('El Peñol', 22),
    ('El Rosario', 22),
    ('El Tambo', 22),
    ('Funes', 22),
    ('Guachucal', 22),
    ('Guaitarilla', 22),
    ('Gualmatán', 22),
    ('Iles', 22),
    ('Imués', 22),
    ('Ipiales', 22),
    ('La Cruz', 22),
    ('La Florida', 22),
    ('La Llanada', 22),
    ('La Tola', 22),
    ('La Unión', 22),
    ('Leiva', 22),
    ('Linares', 22),
    ('Los Andes', 22),
    ('Magüí', 22),
    ('Mallama', 22),
    ('Mosquera', 22),
    ('Nariño', 22),
    ('Olaya Herrera', 22),
    ('Ospina', 22),
    ('Francisco Pizarro', 22),
    ('Policarpa', 22),
    ('Potosí', 22),
    ('Providencia', 22),
    ('Puerres', 22),
    ('Pupiales', 22),
    ('Ricaurte', 22),
    ('Roberto Payán', 22),
    ('Samaniego', 22),
    ('Sandoná', 22),
    ('San Bernardo', 22),
    ('San Lorenzo', 22),
    ('San Pablo', 22),
    ('Santa Bárbara', 22),
    ('Sapuyes', 22),
    ('Taminango', 22),
    ('Tangua', 22),
    ('Túquerres', 22),
    ('Yacuanquer', 22),
    ('San Pedro de Cartago', 22),
    ('El Tablón de Gómez', 22),
    ('Buesaco', 22),
    ('San Andrés de Tumaco', 22),
    ('Belén', 22),
    ('Chachagüí', 22),
    ('Arboleda', 22),
    ('Silos', 23),
    ('Cácota', 23),
    ('Toledo', 23),
    ('Mutiscua', 23),
    ('El Zulia', 23),
    ('Salazar', 23),
    ('Cucutilla', 23),
    ('Puerto Santander', 23),
    ('Gramalote', 23),
    ('El Tarra', 23),
    ('Teorama', 23),
    ('Arboledas', 23),
    ('Lourdes', 23),
    ('Bochalema', 23),
    ('Convención', 23),
    ('Hacarí', 23),
    ('Herrán', 23),
    ('Tibú', 23),
    ('San Cayetano', 23),
    ('San Calixto', 23),
    ('La Playa', 23),
    ('Chinácota', 23),
    ('Ragonvalia', 23),
    ('La Esperanza', 23),
    ('Villa del Rosario', 23),
    ('Chitagá', 23),
    ('Sardinata', 23),
    ('Abrego', 23),
    ('Los Patios', 23),
    ('Ocaña', 23),
    ('Bucarasica', 23),
    ('Santiago', 23),
    ('Labateca', 23),
    ('Cachirá', 23),
    ('Villa Caro', 23),
    ('Durania', 23),
    ('Pamplona', 23),
    ('Pamplonita', 23),
    ('Cúcuta', 23),
    ('El Carmen', 23),
    ('Mocoa', 24),
    ('Colón', 24),
    ('Orito', 24),
    ('Puerto Caicedo', 24),
    ('Puerto Guzmán', 24),
    ('Leguízamo', 24),
    ('Sibundoy', 24),
    ('San Francisco', 24),
    ('San Miguel', 24),
    ('Santiago', 24),
    ('Valle de Guamez', 24),
    ('Puerto Asís', 24),
    ('Villagarzón', 24),
    ('Armenia', 25),
    ('Buenavista', 25),
    ('Circasia', 25),
    ('Córdoba', 25),
    ('Filandia', 25),
    ('La Tebaida', 25),
    ('Montenegro', 25),
    ('Pijao', 25),
    ('Quimbaya', 25),
    ('Salento', 25),
    ('Calarcá', 25),
    ('Génova', 25),
    ('Pereira', 26),
    ('Apía', 26),
    ('Balboa', 26),
    ('Dosquebradas', 26),
    ('Guática', 26);

INSERT INTO
    dbo.city("cityName", "stateId")
VALUES
    ('La Celia', 26),
    ('La Virginia', 26),
    ('Marsella', 26),
    ('Mistrató', 26),
    ('Pueblo Rico', 26),
    ('Quinchía', 26),
    ('Santuario', 26),
    ('Santa Rosa de Cabal', 26),
    ('Belén de Umbría', 26),
    ('Providencia', 27),
    ('San Andrés', 27),
    ('Puerto Wilches', 28),
    ('Puerto Parra', 28),
    ('Bucaramanga', 28),
    ('Aguada', 28),
    ('Albania', 28),
    ('Aratoca', 28),
    ('Barbosa', 28),
    ('Barichara', 28),
    ('Barrancabermeja', 28),
    ('Betulia', 28),
    ('Bolívar', 28),
    ('Cabrera', 28),
    ('California', 28),
    ('Carcasí', 28),
    ('Cepitá', 28),
    ('Cerrito', 28),
    ('Charalá', 28),
    ('Charta', 28),
    ('Chipatá', 28),
    ('Cimitarra', 28),
    ('Concepción', 28),
    ('Confines', 28),
    ('Contratación', 28),
    ('Coromoro', 28),
    ('Curití', 28),
    ('El Guacamayo', 28),
    ('El Playón', 28),
    ('Encino', 28),
    ('Enciso', 28),
    ('Florián', 28),
    ('Floridablanca', 28),
    ('Galán', 28),
    ('Gambita', 28),
    ('Girón', 28),
    ('Guaca', 28),
    ('Guadalupe', 28),
    ('Guapotá', 28),
    ('Guavatá', 28),
    ('Güepsa', 28),
    ('Jesús María', 28),
    ('Jordán', 28),
    ('La Belleza', 28),
    ('Landázuri', 28),
    ('La Paz', 28),
    ('Lebríja', 28),
    ('Los Santos', 28),
    ('Macaravita', 28),
    ('Málaga', 28),
    ('Matanza', 28),
    ('Mogotes', 28),
    ('Molagavita', 28),
    ('Ocamonte', 28),
    ('Oiba', 28),
    ('Onzaga', 28),
    ('Palmar', 28),
    ('Páramo', 28),
    ('Piedecuesta', 28),
    ('Pinchote', 28),
    ('Puente Nacional', 28),
    ('Rionegro', 28),
    ('San Andrés', 28),
    ('San Gil', 28),
    ('San Joaquín', 28),
    ('San Miguel', 28),
    ('Santa Bárbara', 28),
    ('Simacota', 28),
    ('Socorro', 28),
    ('Suaita', 28),
    ('Sucre', 28),
    ('Suratá', 28),
    ('Tona', 28),
    ('Vélez', 28),
    ('Vetas', 28),
    ('Villanueva', 28),
    ('Zapatoca', 28),
    ('Palmas del Socorro', 28),
    ('San Vicente de Chucurí', 28),
    ('San José de Miranda', 28),
    ('Santa Helena del Opón', 28),
    ('Sabana de Torres', 28),
    ('El Carmen de Chucurí', 28),
    ('Valle de San José', 28),
    ('San Benito', 28),
    ('Hato', 28),
    ('Chimá', 28),
    ('Capitanejo', 28),
    ('El Peñón', 28),
    ('Sincelejo', 29),
    ('Buenavista', 29),
    ('Caimito', 29),
    ('Coloso', 29),
    ('Coveñas', 29),
    ('Chalán', 29),
    ('El Roble', 29),
    ('Galeras', 29),
    ('Guaranda', 29),
    ('La Unión', 29),
    ('Los Palmitos', 29),
    ('Majagual', 29),
    ('Morroa', 29),
    ('Ovejas', 29),
    ('Palmito', 29),
    ('San Benito Abad', 29),
    ('San Marcos', 29),
    ('San Onofre', 29),
    ('San Pedro', 29),
    ('Sucre', 29),
    ('Tolú Viejo', 29),
    ('San Luis de Sincé', 29),
    ('San Juan de Betulia', 29),
    ('Santiago de Tolú', 29),
    ('Sampués', 29),
    ('Corozal', 29),
    ('Alpujarra', 30),
    ('Alvarado', 30),
    ('Ambalema', 30),
    ('Armero', 30),
    ('Ataco', 30),
    ('Cajamarca', 30),
    ('Chaparral', 30),
    ('Coello', 30),
    ('Coyaima', 30),
    ('Cunday', 30),
    ('Dolores', 30),
    ('Espinal', 30),
    ('Falan', 30),
    ('Flandes', 30),
    ('Fresno', 30),
    ('Guamo', 30),
    ('Herveo', 30),
    ('Honda', 30),
    ('Icononzo', 30),
    ('Mariquita', 30),
    ('Melgar', 30),
    ('Murillo', 30),
    ('Natagaima', 30),
    ('Ortega', 30),
    ('Palocabildo', 30),
    ('Piedras', 30),
    ('Planadas', 30),
    ('Prado', 30),
    ('Purificación', 30),
    ('Rio Blanco', 30),
    ('Roncesvalles', 30),
    ('Rovira', 30),
    ('Saldaña', 30),
    ('Santa Isabel', 30),
    ('Venadillo', 30),
    ('Villahermosa', 30),
    ('Villarrica', 30),
    ('Valle de San Juan', 30),
    ('Carmen de Apicala', 30),
    ('San Luis', 30),
    ('San Antonio', 30),
    ('Casabianca', 30),
    ('Anzoátegui', 30),
    ('Ibagué', 30),
    ('Líbano', 30),
    ('Lérida', 30),
    ('Suárez', 30),
    ('El Dovio', 31),
    ('Roldanillo', 31),
    ('Argelia', 31),
    ('Sevilla', 31),
    ('Zarzal', 31),
    ('El Cerrito', 31),
    ('Cartago', 31),
    ('Caicedonia', 31),
    ('El Cairo', 31),
    ('La Unión', 31),
    ('Restrepo', 31),
    ('Dagua', 31),
    ('Guacarí', 31),
    ('Ansermanuevo', 31),
    ('Bugalagrande', 31),
    ('La Victoria', 31),
    ('Ginebra', 31),
    ('Yumbo', 31),
    ('Obando', 31),
    ('Bolívar', 31),
    ('Cali', 31),
    ('San Pedro', 31),
    ('Guadalajara de Buga', 31),
    ('Calima', 31),
    ('Andalucía', 31),
    ('Pradera', 31),
    ('Yotoco', 31),
    ('Palmira', 31),
    ('Riofrío', 31),
    ('Alcalá', 31),
    ('Versalles', 31),
    ('El Águila', 31),
    ('Toro', 31),
    ('Candelaria', 31),
    ('La Cumbre', 31),
    ('Ulloa', 31),
    ('Trujillo', 31),
    ('Vijes', 31),
    ('Tuluá', 31),
    ('Florida', 31),
    ('Jamundí', 31),
    ('Buenaventura', 31),
    ('Mitú', 32),
    ('Carurú', 32),
    ('Taraira', 32),
    ('Papunahua', 32),
    ('Yavaraté', 32),
    ('Pacoa', 32),
    ('Puerto Carreño', 33),
    ('La Primavera', 33),
    ('Santa Rosalía', 33),
    ('Cumaribo', 33);

INSERT INTO
    dbo.gender("genderType")
VALUES
    ('Masculino'),
    ('Femenino'),
    ('Otro'),
    ('No binario'),
    ('Transgénero'),
    ('Prefiero no decir');

INSERT INTO
    dbo.ident_document("identDocName")
VALUES
    ('Cédula de ciudadanía');

INSERT INTO
    [tudata].[dbo].[plan]("planName", "planTopics", "iconpath")
VALUES
    (
        'Control',
        'Este plan te permitirá bloquear tres entidades empresariales sin ningún costo.',
        'plans/tudatacontrol.png'
    ),
    (
        'Plus',
        'Este plan te permitirá bloquear un número limitado de entidades empresariales y autorizar mínimo cinco entidades.',
        'plans/tudataplus.png'
    ),
    (
        'Premium',
        'Podrás bloquear y autorizar tantas entidades como quieras y tendrás la opción para adicionar tus intereses de forma personalizada.',
        'plans/tudatapremium.png'
    );

INSERT INTO
    dbo.requirement("requirementName")
VALUES
    ('Derecho de petición'),
    ('Recurso de reposición'),
    ('Tutela'),
    ('Queja ante SIC');

INSERT INTO
    [dbo].[reward_currency] (
        [rewardCurrencyValue],
        [rewardCurrencyActive],
        [planId]
    )
VALUES
    (0, 1, 1),
    (500, 1, 2),
    (800, 1, 3);

INSERT INTO
    [dbo].[reward_currency] (
        [rewardCurrencyValue],
        [rewardCurrencyActive],
        [requirementId]
    )
VALUES
    (400, 1, 4);

INSERT INTO
    [dbo].[reward_currency] (
        [rewardCurrencyValue],
        [rewardCurrencyActive],
        [sponsor]
    )
VALUES
    (1000, 1, 1);

INSERT INTO
    [dbo].[role]([roleName])
VALUES
    ('CONTROL'),
    ('PLUS'),
    ('PREMIUM'),
    ('ABOGADO'),
    ('OPERATIVO'),
    ('ADMINISTRATIVO'),
    ('BUYER');

INSERT INTO
    [dbo].[database_type] ([databaseType])
VALUES
    ('Simple'),
    ('Especializada');

INSERT INTO
    [dbo].[status]([statusName])
VALUES
    ('Pendiente'),
    ('Finalizado'),
    ('Rechazado'),
    ('Revisión');

INSERT INTO
    [dbo].[pqr] (pqrsName, pqrsText, pqrsIcon)
VALUES
    (
        'Petición',
        'Peticiones: *Selecciona esta opción si deseas solicitar a *tudata *cualquier información relacionada con la prestación del servicio (tales como información específica sobre cada plan ofrecido).',
        'pqrsIcons/peticiones.svg'
    ),
    (
        'Queja',
        'Quejas: *Selecciona esta opción si deseas reportar cualquier insatisfacción con la conducta o la acción del personal de *tudata. *También incluye cualquier problema que tengas con la aplicación.',
        'pqrsIcons/quejas.svg'
    ),
    (
        'Reclamo',
        'Reclamos: *Selecciona esta opción si deseas solicitarnos corregir, actualizar o suprimir tus datos personales. También puedes revocar la autorización que nos diste para tratar tus datos personales, aunque esto queda supeditado a lo establecido en la ley de protección de datos personales. También se refiere a los casos en que consideres que *tudata *ha vulnerado tus derechos de Hábeas Data o de Intimidad.',
        'pqrsIcons/reclamos.svg'
    ),
    (
        'Sugerencia',
        'Sugerencias: *Selecciona esta opción si deseas darnos a conocer tus ideas o propuestas para mejorar el servicio o la gestión de *tudata.',
        'pqrsIcons/sugerencias.svg'
    ),
    (
        'Felicitación',
        'Felicitaciones: *Selecciona esta opción si deseas manifestarnos tu agradecimiento o satisfacción hacia los productos, servicios, programas y/o personal de *tudata.',
        'pqrsIcons/felicitaciones.svg'
    ),
    ('Registrar Empresa', '', ''),
    ('Pago Bloqueo', '', ''),
    ('Pago Compra', '', ''),
    (
        'Consulta',
        'Consultas: *Selecciona esta opción si deseas que *tudata *exprese su opinión o concepto sobre algún tema relacionado con nuestros productos y servicios. También puedes usarla si deseas acceder a tu información personal que repose en cualquiera de nuestras bases de datos.',
        'pqrsIcons/consultas.svg'
    ),
    ('Contacto no Autorizado', '', ''),
    ('Eliminar Cuenta', '', ''),
    ('Eliminar Datos', '', '');

/* INSERT INTO
 dbo.company(
 companyId,
 companyBussinesName,
 companyComertialName,
 companyNit,
 companyPhone,
 companyEmail,
 companyLogoPath,
 cityId,
 directRemitent
 )
 VALUES
 (
 '8450f246-41cf-4fef-81ac-d3727c33e3c1',
 'COMCEL COLOMBIA S.A',
 'Claro',
 '800153993',
 '6017500500',
 'solucionesclaro@claro.com.co',
 'logos/123456790/logo.png',
 1,
 1
 );*/
/* INSERT INTO
 dbo.category("categoryName", "iconpath")
 VALUES
 ('Economía', 'categories/icon_economia.png'); */
/* INSERT INTO
 dbo.subcategory("subcategoryName", "iconpath", "categoryId")
 VALUES
 (
 'Finanzas personales',
 'subcategories/icon_finanzas-personales.svg',
 1
 ); */
/* INSERT INTO
 dbo.element("elementName", "subCategoryId")
 VALUES
 ('Ahorro de emergencia', 1); */
INSERT INTO
    role_permission
VALUES
    ('BUYER', 'PLUS', 'POST', 0),
    ('BUYER', 'PLUS', 'GET', 0),
    ('BUYER', 'PLUS', 'PATCH', 0),
    ('BUYER', 'PLUS', 'DELETE', 0),
    ('BD-PRICES', 'PLUS', 'POST', 0),
    ('BD-PRICES', 'PLUS', 'GET', 0),
    ('BD-PRICES', 'PLUS', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'POST', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'GET', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'PLUS', 'DELETE', 0),
    ('CATEGORY', 'PLUS', 'POST', 0),
    ('CATEGORY', 'PLUS', 'GET', 1),
    ('CATEGORY', 'PLUS', 'PATCH', 0),
    ('CATEGORY', 'PLUS', 'DELETE', 0),
    ('CITY', 'PLUS', 'POST', 0),
    ('CITY', 'PLUS', 'GET', 1),
    ('CITY', 'PLUS', 'PATCH', 0),
    ('CITY', 'PLUS', 'DELETE', 0),
    ('COMPANY', 'PLUS', 'POST', 0),
    ('COMPANY', 'PLUS', 'GET', 1),
    ('COMPANY', 'PLUS', 'PATCH', 0),
    ('COMPANY', 'PLUS', 'DELETE', 0),
    ('COUNTRY', 'PLUS', 'POST', 0),
    ('COUNTRY', 'PLUS', 'GET', 1),
    ('COUNTRY', 'PLUS', 'PATCH', 0),
    ('COUNTRY', 'PLUS', 'DELETE', 0),
    ('CREDENTIALS', 'PLUS', 'POST', 1),
    ('CREDENTIALS', 'PLUS', 'GET', 1),
    ('CREDENTIALS', 'PLUS', 'PATCH', 1),
    ('CREDENTIALS', 'PLUS', 'DELETE', 0),
    ('DATABASE-TYPE', 'PLUS', 'POST', 0),
    ('DATABASE-TYPE', 'PLUS', 'GET', 0),
    ('DATABASE-TYPE', 'PLUS', 'PATCH', 0),
    ('DATABASE-TYPE', 'PLUS', 'DELETE', 0),
    ('DEMAND', 'PLUS', 'POST', 1),
    ('DEMAND', 'PLUS', 'GET', 1),
    ('DEMAND', 'PLUS', 'PATCH', 0),
    ('DEMAND', 'PLUS', 'DELETE', 0),
    ('ELEMENT', 'PLUS', 'POST', 0),
    ('ELEMENT', 'PLUS', 'GET', 1),
    ('ELEMENT', 'PLUS', 'PATCH', 0),
    ('ELEMENT', 'PLUS', 'DELETE', 0),
    ('EMPLOYEE', 'PLUS', 'POST', 0),
    ('EMPLOYEE', 'PLUS', 'GET', 0),
    ('EMPLOYEE', 'PLUS', 'PATCH', 0),
    ('EMPLOYEE', 'PLUS', 'DELETE', 0),
    ('ERROR-LOG', 'PLUS', 'POST', 0),
    ('ERROR-LOG', 'PLUS', 'GET', 0),
    ('ERROR-LOG', 'PLUS', 'PATCH', 0),
    ('ERROR-LOG', 'PLUS', 'DELETE', 0),
    ('FAQ', 'PLUS', 'POST', 0),
    ('FAQ', 'PLUS', 'GET', 1),
    ('FAQ', 'PLUS', 'PATCH', 0),
    ('FAQ', 'PLUS', 'DELETE', 0),
    ('GENDER', 'PLUS', 'POST', 0),
    ('GENDER', 'PLUS', 'GET', 1),
    ('GENDER', 'PLUS', 'PATCH', 0),
    ('GENDER', 'PLUS', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'PLUS', 'POST', 0),
    ('IDENT-DOCUMENT', 'PLUS', 'GET', 1),
    ('IDENT-DOCUMENT', 'PLUS', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'PLUS', 'DELETE', 0),
    ('OBJECT', 'PLUS', 'POST', 0),
    ('OBJECT', 'PLUS', 'GET', 0),
    ('OBJECT', 'PLUS', 'PATCH', 0),
    ('OBJECT', 'PLUS', 'DELETE', 0),
    ('PERSON', 'PLUS', 'POST', 1),
    ('PERSON', 'PLUS', 'GET', 1),
    ('PERSON', 'PLUS', 'PATCH', 1),
    ('PERSON', 'PLUS', 'DELETE', 0),
    ('PLAN', 'PLUS', 'POST', 0),
    ('PLAN', 'PLUS', 'GET', 1),
    ('PLAN', 'PLUS', 'PATCH', 0),
    ('PLAN', 'PLUS', 'DELETE', 0),
    ('POLITIC', 'PLUS', 'POST', 0),
    ('POLITIC', 'PLUS', 'GET', 1),
    ('POLITIC', 'PLUS', 'PATCH', 0),
    ('POLITIC', 'PLUS', 'DELETE', 0),
    ('POLITIC-BODY', 'PLUS', 'POST', 0),
    ('POLITIC-BODY', 'PLUS', 'GET', 1),
    ('POLITIC-BODY', 'PLUS', 'PATCH', 0),
    ('POLITIC-BODY', 'PLUS', 'DELETE', 0),
    ('POLITICSACCEPTED', 'PLUS', 'POST', 1),
    ('POLITICSACCEPTED', 'PLUS', 'GET', 0),
    ('POLITICSACCEPTED', 'PLUS', 'PATCH', 0),
    ('POLITICSACCEPTED', 'PLUS', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'PLUS', 'POST', 0),
    ('REDEEMED-HISTORY', 'PLUS', 'GET', 1),
    ('REDEEMED-HISTORY', 'PLUS', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'PLUS', 'DELETE', 0),
    ('REQUEST', 'PLUS', 'POST', 1),
    ('REQUEST', 'PLUS', 'GET', 1),
    ('REQUEST', 'PLUS', 'PATCH', 0),
    ('REQUEST', 'PLUS', 'DELETE', 0),
    ('REQUIREMENT', 'PLUS', 'POST', 0),
    ('REQUIREMENT', 'PLUS', 'GET', 1),
    ('REQUIREMENT', 'PLUS', 'PATCH', 0),
    ('REQUIREMENT', 'PLUS', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'PLUS', 'POST', 0),
    ('REQUIREMENT-BODY', 'PLUS', 'GET', 1),
    ('REQUIREMENT-BODY', 'PLUS', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'PLUS', 'DELETE', 0),
    ('REWARD', 'PLUS', 'POST', 1),
    ('REWARD', 'PLUS', 'GET', 1),
    ('REWARD', 'PLUS', 'PATCH', 0),
    ('REWARD', 'PLUS', 'DELETE', 0),
    ('REWARD-CURRENCY', 'PLUS', 'POST', 0),
    ('REWARD-CURRENCY', 'PLUS', 'GET', 1),
    ('REWARD-CURRENCY', 'PLUS', 'PATCH', 0),
    ('REWARD-CURRENCY', 'PLUS', 'DELETE', 0),
    ('ROLE', 'PLUS', 'POST', 0),
    ('ROLE', 'PLUS', 'GET', 0),
    ('ROLE', 'PLUS', 'PATCH', 0),
    ('ROLE', 'PLUS', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'POST', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'GET', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'PLUS', 'DELETE', 0),
    ('SELECTION', 'PLUS', 'POST', 0),
    ('SELECTION', 'PLUS', 'GET', 0),
    ('SELECTION', 'PLUS', 'PATCH', 0),
    ('SELECTION', 'PLUS', 'DELETE', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'PATCH', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PLUS', 'DELETE', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'POST', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'GET', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'PLUS', 'DELETE', 0),
    ('STATE', 'PLUS', 'POST', 0),
    ('STATE', 'PLUS', 'GET', 1),
    ('STATE', 'PLUS', 'PATCH', 0),
    ('STATE', 'PLUS', 'DELETE', 0),
    ('STATUS', 'PLUS', 'POST', 0),
    ('STATUS', 'PLUS', 'GET', 1),
    ('STATUS', 'PLUS', 'PATCH', 0),
    ('STATUS', 'PLUS', 'DELETE', 0),
    ('SUBCATEGORY', 'PLUS', 'POST', 0),
    ('SUBCATEGORY', 'PLUS', 'GET', 0),
    ('SUBCATEGORY', 'PLUS', 'PATCH', 0),
    ('SUBCATEGORY', 'PLUS', 'DELETE', 0),
    ('USER', 'PLUS', 'POST', 1),
    ('USER', 'PLUS', 'GET', 1),
    ('USER', 'PLUS', 'PATCH', 1),
    ('USER', 'PLUS', 'DELETE', 0),
    ('USERSBUYED', 'PLUS', 'POST', 0),
    ('USERSBUYED', 'PLUS', 'GET', 1),
    ('USERSBUYED', 'PLUS', 'PATCH', 0),
    ('USERSBUYED', 'PLUS', 'DELETE', 0),
    ('WHITE-LIST', 'PLUS', 'POST', 1),
    ('WHITE-LIST', 'PLUS', 'GET', 1),
    ('WHITE-LIST', 'PLUS', 'PATCH', 0),
    ('WHITE-LIST', 'PLUS', 'DELETE', 0),
    ('PQRS', 'PLUS', 'POST', 0),
    ('PQRS', 'PLUS', 'GET', 1),
    ('PQRS', 'PLUS', 'PATCH', 0),
    ('PQRS', 'PLUS', 'DELETE', 0),
    ('BUYER', 'CONTROL', 'POST', 0),
    ('BUYER', 'CONTROL', 'GET', 0),
    ('BUYER', 'CONTROL', 'PATCH', 0),
    ('BUYER', 'CONTROL', 'DELETE', 0),
    ('BD-PRICES', 'CONTROL', 'POST', 0),
    ('BD-PRICES', 'CONTROL', 'GET', 0),
    ('BD-PRICES', 'CONTROL', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'POST', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'GET', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'CONTROL', 'DELETE', 0),
    ('CATEGORY', 'CONTROL', 'POST', 0),
    ('CATEGORY', 'CONTROL', 'GET', 0),
    ('CATEGORY', 'CONTROL', 'PATCH', 0),
    ('CATEGORY', 'CONTROL', 'DELETE', 0),
    ('CITY', 'CONTROL', 'POST', 0),
    ('CITY', 'CONTROL', 'GET', 1),
    ('CITY', 'CONTROL', 'PATCH', 0),
    ('CITY', 'CONTROL', 'DELETE', 0),
    ('COMPANY', 'CONTROL', 'POST', 0),
    ('COMPANY', 'CONTROL', 'GET', 1),
    ('COMPANY', 'CONTROL', 'PATCH', 0),
    ('COMPANY', 'CONTROL', 'DELETE', 0),
    ('COUNTRY', 'CONTROL', 'POST', 0),
    ('COUNTRY', 'CONTROL', 'GET', 1),
    ('COUNTRY', 'CONTROL', 'PATCH', 0),
    ('COUNTRY', 'CONTROL', 'DELETE', 0),
    ('CREDENTIALS', 'CONTROL', 'POST', 1),
    ('CREDENTIALS', 'CONTROL', 'GET', 1),
    ('CREDENTIALS', 'CONTROL', 'PATCH', 1),
    ('CREDENTIALS', 'CONTROL', 'DELETE', 0),
    ('DATABASE-TYPE', 'CONTROL', 'POST', 0),
    ('DATABASE-TYPE', 'CONTROL', 'GET', 0),
    ('DATABASE-TYPE', 'CONTROL', 'PATCH', 0),
    ('DATABASE-TYPE', 'CONTROL', 'DELETE', 0),
    ('DEMAND', 'CONTROL', 'POST', 1),
    ('DEMAND', 'CONTROL', 'GET', 1),
    ('DEMAND', 'CONTROL', 'PATCH', 0),
    ('DEMAND', 'CONTROL', 'DELETE', 0),
    ('ELEMENT', 'CONTROL', 'POST', 0),
    ('ELEMENT', 'CONTROL', 'GET', 0),
    ('ELEMENT', 'CONTROL', 'PATCH', 0),
    ('ELEMENT', 'CONTROL', 'DELETE', 0),
    ('EMPLOYEE', 'CONTROL', 'POST', 0),
    ('EMPLOYEE', 'CONTROL', 'GET', 0),
    ('EMPLOYEE', 'CONTROL', 'PATCH', 0),
    ('EMPLOYEE', 'CONTROL', 'DELETE', 0),
    ('ERROR-LOG', 'CONTROL', 'POST', 0),
    ('ERROR-LOG', 'CONTROL', 'GET', 0),
    ('ERROR-LOG', 'CONTROL', 'PATCH', 0),
    ('ERROR-LOG', 'CONTROL', 'DELETE', 0),
    ('FAQ', 'CONTROL', 'POST', 0),
    ('FAQ', 'CONTROL', 'GET', 1),
    ('FAQ', 'CONTROL', 'PATCH', 0),
    ('FAQ', 'CONTROL', 'DELETE', 0),
    ('GENDER', 'CONTROL', 'POST', 0),
    ('GENDER', 'CONTROL', 'GET', 1),
    ('GENDER', 'CONTROL', 'PATCH', 0),
    ('GENDER', 'CONTROL', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'CONTROL', 'POST', 0),
    ('IDENT-DOCUMENT', 'CONTROL', 'GET', 1),
    ('IDENT-DOCUMENT', 'CONTROL', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'CONTROL', 'DELETE', 0),
    ('OBJECT', 'CONTROL', 'POST', 0),
    ('OBJECT', 'CONTROL', 'GET', 0),
    ('OBJECT', 'CONTROL', 'PATCH', 0),
    ('OBJECT', 'CONTROL', 'DELETE', 0),
    ('PERSON', 'CONTROL', 'POST', 1),
    ('PERSON', 'CONTROL', 'GET', 1),
    ('PERSON', 'CONTROL', 'PATCH', 1),
    ('PERSON', 'CONTROL', 'DELETE', 0),
    ('PLAN', 'CONTROL', 'POST', 0),
    ('PLAN', 'CONTROL', 'GET', 1),
    ('PLAN', 'CONTROL', 'PATCH', 0),
    ('PLAN', 'CONTROL', 'DELETE', 0),
    ('POLITIC', 'CONTROL', 'POST', 0),
    ('POLITIC', 'CONTROL', 'GET', 1),
    ('POLITIC', 'CONTROL', 'PATCH', 0),
    ('POLITIC', 'CONTROL', 'DELETE', 0),
    ('POLITIC-BODY', 'CONTROL', 'POST', 0),
    ('POLITIC-BODY', 'CONTROL', 'GET', 1),
    ('POLITIC-BODY', 'CONTROL', 'PATCH', 0),
    ('POLITIC-BODY', 'CONTROL', 'DELETE', 0),
    ('POLITICSACCEPTED', 'CONTROL', 'POST', 1),
    ('POLITICSACCEPTED', 'CONTROL', 'GET', 0),
    ('POLITICSACCEPTED', 'CONTROL', 'PATCH', 0),
    ('POLITICSACCEPTED', 'CONTROL', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'CONTROL', 'POST', 0),
    ('REDEEMED-HISTORY', 'CONTROL', 'GET', 1),
    ('REDEEMED-HISTORY', 'CONTROL', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'CONTROL', 'DELETE', 0),
    ('REQUEST', 'CONTROL', 'POST', 1),
    ('REQUEST', 'CONTROL', 'GET', 1),
    ('REQUEST', 'CONTROL', 'PATCH', 0),
    ('REQUEST', 'CONTROL', 'DELETE', 0),
    ('REQUIREMENT', 'CONTROL', 'POST', 0),
    ('REQUIREMENT', 'CONTROL', 'GET', 1),
    ('REQUIREMENT', 'CONTROL', 'PATCH', 0),
    ('REQUIREMENT', 'CONTROL', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'CONTROL', 'POST', 0),
    ('REQUIREMENT-BODY', 'CONTROL', 'GET', 1),
    ('REQUIREMENT-BODY', 'CONTROL', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'CONTROL', 'DELETE', 0),
    ('REWARD', 'CONTROL', 'POST', 0),
    ('REWARD', 'CONTROL', 'GET', 0),
    ('REWARD', 'CONTROL', 'PATCH', 0),
    ('REWARD', 'CONTROL', 'DELETE', 0),
    ('REWARD-CURRENCY', 'CONTROL', 'POST', 0),
    ('REWARD-CURRENCY', 'CONTROL', 'GET', 1),
    ('REWARD-CURRENCY', 'CONTROL', 'PATCH', 0),
    ('REWARD-CURRENCY', 'CONTROL', 'DELETE', 0),
    ('ROLE', 'CONTROL', 'POST', 0),
    ('ROLE', 'CONTROL', 'GET', 0),
    ('ROLE', 'CONTROL', 'PATCH', 0),
    ('ROLE', 'CONTROL', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'POST', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'GET', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'CONTROL', 'DELETE', 0),
    ('SELECTION', 'CONTROL', 'POST', 0),
    ('SELECTION', 'CONTROL', 'GET', 0),
    ('SELECTION', 'CONTROL', 'PATCH', 0),
    ('SELECTION', 'CONTROL', 'DELETE', 0),
    ('SHOPPING-DEMAND-HISTORY', 'CONTROL', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'CONTROL', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'CONTROL', 'PATCH', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'CONTROL',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'CONTROL', 'POST', 0),
    ('SHOPPINGHISTORY', 'CONTROL', 'GET', 1),
    ('SHOPPINGHISTORY', 'CONTROL', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'CONTROL', 'DELETE', 0),
    ('STATE', 'CONTROL', 'POST', 0),
    ('STATE', 'CONTROL', 'GET', 1),
    ('STATE', 'CONTROL', 'PATCH', 0),
    ('STATE', 'CONTROL', 'DELETE', 0),
    ('STATUS', 'CONTROL', 'POST', 0),
    ('STATUS', 'CONTROL', 'GET', 1),
    ('STATUS', 'CONTROL', 'PATCH', 0),
    ('STATUS', 'CONTROL', 'DELETE', 0),
    ('SUBCATEGORY', 'CONTROL', 'POST', 0),
    ('SUBCATEGORY', 'CONTROL', 'GET', 0),
    ('SUBCATEGORY', 'CONTROL', 'PATCH', 0),
    ('SUBCATEGORY', 'CONTROL', 'DELETE', 0),
    ('USER', 'CONTROL', 'POST', 1),
    ('USER', 'CONTROL', 'GET', 1),
    ('USER', 'CONTROL', 'PATCH', 1),
    ('USER', 'CONTROL', 'DELETE', 0),
    ('USERSBUYED', 'CONTROL', 'POST', 0),
    ('USERSBUYED', 'CONTROL', 'GET', 0),
    ('USERSBUYED', 'CONTROL', 'PATCH', 0),
    ('USERSBUYED', 'CONTROL', 'DELETE', 0),
    ('WHITE-LIST', 'CONTROL', 'POST', 0),
    ('WHITE-LIST', 'CONTROL', 'GET', 0),
    ('WHITE-LIST', 'CONTROL', 'PATCH', 0),
    ('WHITE-LIST', 'CONTROL', 'DELETE', 0),
    ('PQRS', 'CONTROL', 'POST', 0),
    ('PQRS', 'CONTROL', 'GET', 1),
    ('PQRS', 'CONTROL', 'PATCH', 0),
    ('PQRS', 'CONTROL', 'DELETE', 0),
    ('BUYER', 'PREMIUM', 'POST', 0),
    ('BUYER', 'PREMIUM', 'GET', 0),
    ('BUYER', 'PREMIUM', 'PATCH', 0),
    ('BUYER', 'PREMIUM', 'DELETE', 0),
    ('BD-PRICES', 'PREMIUM', 'POST', 0),
    ('BD-PRICES', 'PREMIUM', 'GET', 0),
    ('BD-PRICES', 'PREMIUM', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'POST', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'GET', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'PREMIUM', 'DELETE', 0),
    ('CATEGORY', 'PREMIUM', 'POST', 0),
    ('CATEGORY', 'PREMIUM', 'GET', 1),
    ('CATEGORY', 'PREMIUM', 'PATCH', 0),
    ('CATEGORY', 'PREMIUM', 'DELETE', 0),
    ('CITY', 'PREMIUM', 'POST', 0),
    ('CITY', 'PREMIUM', 'GET', 1),
    ('CITY', 'PREMIUM', 'PATCH', 0),
    ('CITY', 'PREMIUM', 'DELETE', 0),
    ('COMPANY', 'PREMIUM', 'POST', 0),
    ('COMPANY', 'PREMIUM', 'GET', 1),
    ('COMPANY', 'PREMIUM', 'PATCH', 0),
    ('COMPANY', 'PREMIUM', 'DELETE', 0),
    ('COUNTRY', 'PREMIUM', 'POST', 0),
    ('COUNTRY', 'PREMIUM', 'GET', 1),
    ('COUNTRY', 'PREMIUM', 'PATCH', 0),
    ('COUNTRY', 'PREMIUM', 'DELETE', 0),
    ('CREDENTIALS', 'PREMIUM', 'POST', 1),
    ('CREDENTIALS', 'PREMIUM', 'GET', 1),
    ('CREDENTIALS', 'PREMIUM', 'PATCH', 1),
    ('CREDENTIALS', 'PREMIUM', 'DELETE', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'POST', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'GET', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'PATCH', 0),
    ('DATABASE-TYPE', 'PREMIUM', 'DELETE', 0),
    ('DEMAND', 'PREMIUM', 'POST', 1),
    ('DEMAND', 'PREMIUM', 'GET', 1),
    ('DEMAND', 'PREMIUM', 'PATCH', 0),
    ('DEMAND', 'PREMIUM', 'DELETE', 0),
    ('ELEMENT', 'PREMIUM', 'POST', 0),
    ('ELEMENT', 'PREMIUM', 'GET', 1),
    ('ELEMENT', 'PREMIUM', 'PATCH', 0),
    ('ELEMENT', 'PREMIUM', 'DELETE', 0),
    ('EMPLOYEE', 'PREMIUM', 'POST', 0),
    ('EMPLOYEE', 'PREMIUM', 'GET', 0),
    ('EMPLOYEE', 'PREMIUM', 'PATCH', 0),
    ('EMPLOYEE', 'PREMIUM', 'DELETE', 0),
    ('ERROR-LOG', 'PREMIUM', 'POST', 0),
    ('ERROR-LOG', 'PREMIUM', 'GET', 0),
    ('ERROR-LOG', 'PREMIUM', 'PATCH', 0),
    ('ERROR-LOG', 'PREMIUM', 'DELETE', 0),
    ('FAQ', 'PREMIUM', 'POST', 0),
    ('FAQ', 'PREMIUM', 'GET', 1),
    ('FAQ', 'PREMIUM', 'PATCH', 0),
    ('FAQ', 'PREMIUM', 'DELETE', 0),
    ('GENDER', 'PREMIUM', 'POST', 0),
    ('GENDER', 'PREMIUM', 'GET', 1),
    ('GENDER', 'PREMIUM', 'PATCH', 0),
    ('GENDER', 'PREMIUM', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'PREMIUM', 'POST', 0),
    ('IDENT-DOCUMENT', 'PREMIUM', 'GET', 1),
    ('IDENT-DOCUMENT', 'PREMIUM', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'PREMIUM', 'DELETE', 0),
    ('OBJECT', 'PREMIUM', 'POST', 0),
    ('OBJECT', 'PREMIUM', 'GET', 0),
    ('OBJECT', 'PREMIUM', 'PATCH', 0),
    ('OBJECT', 'PREMIUM', 'DELETE', 0),
    ('PERSON', 'PREMIUM', 'POST', 1),
    ('PERSON', 'PREMIUM', 'GET', 1),
    ('PERSON', 'PREMIUM', 'PATCH', 1),
    ('PERSON', 'PREMIUM', 'DELETE', 0),
    ('PLAN', 'PREMIUM', 'POST', 0),
    ('PLAN', 'PREMIUM', 'GET', 1),
    ('PLAN', 'PREMIUM', 'PATCH', 0),
    ('PLAN', 'PREMIUM', 'DELETE', 0),
    ('POLITIC', 'PREMIUM', 'POST', 0),
    ('POLITIC', 'PREMIUM', 'GET', 1),
    ('POLITIC', 'PREMIUM', 'PATCH', 0),
    ('POLITIC', 'PREMIUM', 'DELETE', 0),
    ('POLITIC-BODY', 'PREMIUM', 'POST', 0),
    ('POLITIC-BODY', 'PREMIUM', 'GET', 1),
    ('POLITIC-BODY', 'PREMIUM', 'PATCH', 0),
    ('POLITIC-BODY', 'PREMIUM', 'DELETE', 0),
    ('POLITICSACCEPTED', 'PREMIUM', 'POST', 1),
    ('POLITICSACCEPTED', 'PREMIUM', 'GET', 0),
    ('POLITICSACCEPTED', 'PREMIUM', 'PATCH', 0),
    ('POLITICSACCEPTED', 'PREMIUM', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'PREMIUM', 'POST', 0),
    ('REDEEMED-HISTORY', 'PREMIUM', 'GET', 1),
    ('REDEEMED-HISTORY', 'PREMIUM', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'PREMIUM', 'DELETE', 0),
    ('REQUEST', 'PREMIUM', 'POST', 1),
    ('REQUEST', 'PREMIUM', 'GET', 1),
    ('REQUEST', 'PREMIUM', 'PATCH', 0),
    ('REQUEST', 'PREMIUM', 'DELETE', 0),
    ('REQUIREMENT', 'PREMIUM', 'POST', 0),
    ('REQUIREMENT', 'PREMIUM', 'GET', 1),
    ('REQUIREMENT', 'PREMIUM', 'PATCH', 0),
    ('REQUIREMENT', 'PREMIUM', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'PREMIUM', 'POST', 0),
    ('REQUIREMENT-BODY', 'PREMIUM', 'GET', 1),
    ('REQUIREMENT-BODY', 'PREMIUM', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'PREMIUM', 'DELETE', 0),
    ('REWARD', 'PREMIUM', 'POST', 1),
    ('REWARD', 'PREMIUM', 'GET', 1),
    ('REWARD', 'PREMIUM', 'PATCH', 0),
    ('REWARD', 'PREMIUM', 'DELETE', 0),
    ('REWARD-CURRENCY', 'PREMIUM', 'POST', 0),
    ('REWARD-CURRENCY', 'PREMIUM', 'GET', 1),
    ('REWARD-CURRENCY', 'PREMIUM', 'PATCH', 0),
    ('REWARD-CURRENCY', 'PREMIUM', 'DELETE', 0),
    ('ROLE', 'PREMIUM', 'POST', 0),
    ('ROLE', 'PREMIUM', 'GET', 0),
    ('ROLE', 'PREMIUM', 'PATCH', 0),
    ('ROLE', 'PREMIUM', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'POST', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'GET', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'PREMIUM', 'DELETE', 0),
    ('SELECTION', 'PREMIUM', 'POST', 1),
    ('SELECTION', 'PREMIUM', 'GET', 1),
    ('SELECTION', 'PREMIUM', 'PATCH', 0),
    ('SELECTION', 'PREMIUM', 'DELETE', 1),
    ('SHOPPING-DEMAND-HISTORY', 'PREMIUM', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PREMIUM', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'PREMIUM', 'PATCH', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'PREMIUM',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'PREMIUM', 'POST', 0),
    ('SHOPPINGHISTORY', 'PREMIUM', 'GET', 1),
    ('SHOPPINGHISTORY', 'PREMIUM', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'PREMIUM', 'DELETE', 0),
    ('STATE', 'PREMIUM', 'POST', 0),
    ('STATE', 'PREMIUM', 'GET', 1),
    ('STATE', 'PREMIUM', 'PATCH', 0),
    ('STATE', 'PREMIUM', 'DELETE', 0),
    ('STATUS', 'PREMIUM', 'POST', 0),
    ('STATUS', 'PREMIUM', 'GET', 1),
    ('STATUS', 'PREMIUM', 'PATCH', 0),
    ('STATUS', 'PREMIUM', 'DELETE', 0),
    ('SUBCATEGORY', 'PREMIUM', 'POST', 0),
    ('SUBCATEGORY', 'PREMIUM', 'GET', 1),
    ('SUBCATEGORY', 'PREMIUM', 'PATCH', 0),
    ('SUBCATEGORY', 'PREMIUM', 'DELETE', 0),
    ('USER', 'PREMIUM', 'POST', 1),
    ('USER', 'PREMIUM', 'GET', 1),
    ('USER', 'PREMIUM', 'PATCH', 1),
    ('USER', 'PREMIUM', 'DELETE', 0),
    ('USERSBUYED', 'PREMIUM', 'POST', 0),
    ('USERSBUYED', 'PREMIUM', 'GET', 1),
    ('USERSBUYED', 'PREMIUM', 'PATCH', 0),
    ('USERSBUYED', 'PREMIUM', 'DELETE', 0),
    ('WHITE-LIST', 'PREMIUM', 'POST', 1),
    ('WHITE-LIST', 'PREMIUM', 'GET', 1),
    ('WHITE-LIST', 'PREMIUM', 'PATCH', 0),
    ('WHITE-LIST', 'PREMIUM', 'DELETE', 0),
    ('PQRS', 'PREMIUM', 'POST', 0),
    ('PQRS', 'PREMIUM', 'GET', 1),
    ('PQRS', 'PREMIUM', 'PATCH', 0),
    ('PQRS', 'PREMIUM', 'DELETE', 0),
    ('BUYER', 'ABOGADO', 'POST', 0),
    ('BUYER', 'ABOGADO', 'GET', 1),
    ('BUYER', 'ABOGADO', 'PATCH', 0),
    ('BUYER', 'ABOGADO', 'DELETE', 0),
    ('BD-PRICES', 'ABOGADO', 'POST', 0),
    ('BD-PRICES', 'ABOGADO', 'GET', 0),
    ('BD-PRICES', 'ABOGADO', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'POST', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'GET', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'ABOGADO', 'DELETE', 0),
    ('CATEGORY', 'ABOGADO', 'POST', 0),
    ('CATEGORY', 'ABOGADO', 'GET', 1),
    ('CATEGORY', 'ABOGADO', 'PATCH', 0),
    ('CATEGORY', 'ABOGADO', 'DELETE', 0),
    ('CITY', 'ABOGADO', 'POST', 0),
    ('CITY', 'ABOGADO', 'GET', 1),
    ('CITY', 'ABOGADO', 'PATCH', 0),
    ('CITY', 'ABOGADO', 'DELETE', 0),
    ('COMPANY', 'ABOGADO', 'POST', 1),
    ('COMPANY', 'ABOGADO', 'GET', 1),
    ('COMPANY', 'ABOGADO', 'PATCH', 1),
    ('COMPANY', 'ABOGADO', 'DELETE', 0),
    ('COUNTRY', 'ABOGADO', 'POST', 0),
    ('COUNTRY', 'ABOGADO', 'GET', 1),
    ('COUNTRY', 'ABOGADO', 'PATCH', 0),
    ('COUNTRY', 'ABOGADO', 'DELETE', 0),
    ('CREDENTIALS', 'ABOGADO', 'POST', 0),
    ('CREDENTIALS', 'ABOGADO', 'GET', 0),
    ('CREDENTIALS', 'ABOGADO', 'PATCH', 0),
    ('CREDENTIALS', 'ABOGADO', 'DELETE', 0),
    ('DATABASE-TYPE', 'ABOGADO', 'POST', 0),
    ('DATABASE-TYPE', 'ABOGADO', 'GET', 1),
    ('DATABASE-TYPE', 'ABOGADO', 'PATCH', 0),
    ('DATABASE-TYPE', 'ABOGADO', 'DELETE', 0),
    ('DEMAND', 'ABOGADO', 'POST', 1),
    ('DEMAND', 'ABOGADO', 'GET', 1),
    ('DEMAND', 'ABOGADO', 'PATCH', 1),
    ('DEMAND', 'ABOGADO', 'DELETE', 0),
    ('ELEMENT', 'ABOGADO', 'POST', 0),
    ('ELEMENT', 'ABOGADO', 'GET', 1),
    ('ELEMENT', 'ABOGADO', 'PATCH', 0),
    ('ELEMENT', 'ABOGADO', 'DELETE', 0),
    ('EMPLOYEE', 'ABOGADO', 'POST', 0),
    ('EMPLOYEE', 'ABOGADO', 'GET', 1),
    ('EMPLOYEE', 'ABOGADO', 'PATCH', 0),
    ('EMPLOYEE', 'ABOGADO', 'DELETE', 0),
    ('ERROR-LOG', 'ABOGADO', 'POST', 0),
    ('ERROR-LOG', 'ABOGADO', 'GET', 0),
    ('ERROR-LOG', 'ABOGADO', 'PATCH', 0),
    ('ERROR-LOG', 'ABOGADO', 'DELETE', 0),
    ('FAQ', 'ABOGADO', 'POST', 0),
    ('FAQ', 'ABOGADO', 'GET', 1),
    ('FAQ', 'ABOGADO', 'PATCH', 0),
    ('FAQ', 'ABOGADO', 'DELETE', 0),
    ('GENDER', 'ABOGADO', 'POST', 0),
    ('GENDER', 'ABOGADO', 'GET', 1),
    ('GENDER', 'ABOGADO', 'PATCH', 0),
    ('GENDER', 'ABOGADO', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'ABOGADO', 'POST', 0),
    ('IDENT-DOCUMENT', 'ABOGADO', 'GET', 1),
    ('IDENT-DOCUMENT', 'ABOGADO', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'ABOGADO', 'DELETE', 0),
    ('OBJECT', 'ABOGADO', 'POST', 0),
    ('OBJECT', 'ABOGADO', 'GET', 0),
    ('OBJECT', 'ABOGADO', 'PATCH', 0),
    ('OBJECT', 'ABOGADO', 'DELETE', 0),
    ('PERSON', 'ABOGADO', 'POST', 0),
    ('PERSON', 'ABOGADO', 'GET', 1),
    ('PERSON', 'ABOGADO', 'PATCH', 0),
    ('PERSON', 'ABOGADO', 'DELETE', 0),
    ('PLAN', 'ABOGADO', 'POST', 0),
    ('PLAN', 'ABOGADO', 'GET', 1),
    ('PLAN', 'ABOGADO', 'PATCH', 0),
    ('PLAN', 'ABOGADO', 'DELETE', 0),
    ('POLITIC', 'ABOGADO', 'POST', 0),
    ('POLITIC', 'ABOGADO', 'GET', 1),
    ('POLITIC', 'ABOGADO', 'PATCH', 0),
    ('POLITIC', 'ABOGADO', 'DELETE', 0),
    ('POLITIC-BODY', 'ABOGADO', 'POST', 0),
    ('POLITIC-BODY', 'ABOGADO', 'GET', 1),
    ('POLITIC-BODY', 'ABOGADO', 'PATCH', 0),
    ('POLITIC-BODY', 'ABOGADO', 'DELETE', 0),
    ('POLITICSACCEPTED', 'ABOGADO', 'POST', 0),
    ('POLITICSACCEPTED', 'ABOGADO', 'GET', 1),
    ('POLITICSACCEPTED', 'ABOGADO', 'PATCH', 0),
    ('POLITICSACCEPTED', 'ABOGADO', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'ABOGADO', 'POST', 0),
    ('REDEEMED-HISTORY', 'ABOGADO', 'GET', 1),
    ('REDEEMED-HISTORY', 'ABOGADO', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'ABOGADO', 'DELETE', 0),
    ('REQUEST', 'ABOGADO', 'POST', 1),
    ('REQUEST', 'ABOGADO', 'GET', 1),
    ('REQUEST', 'ABOGADO', 'PATCH', 1),
    ('REQUEST', 'ABOGADO', 'DELETE', 0),
    ('REQUIREMENT', 'ABOGADO', 'POST', 0),
    ('REQUIREMENT', 'ABOGADO', 'GET', 1),
    ('REQUIREMENT', 'ABOGADO', 'PATCH', 0),
    ('REQUIREMENT', 'ABOGADO', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'ABOGADO', 'POST', 0),
    ('REQUIREMENT-BODY', 'ABOGADO', 'GET', 1),
    ('REQUIREMENT-BODY', 'ABOGADO', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'ABOGADO', 'DELETE', 0),
    ('REWARD', 'ABOGADO', 'POST', 0),
    ('REWARD', 'ABOGADO', 'GET', 1),
    ('REWARD', 'ABOGADO', 'PATCH', 0),
    ('REWARD', 'ABOGADO', 'DELETE', 0),
    ('REWARD-CURRENCY', 'ABOGADO', 'POST', 0),
    ('REWARD-CURRENCY', 'ABOGADO', 'GET', 1),
    ('REWARD-CURRENCY', 'ABOGADO', 'PATCH', 0),
    ('REWARD-CURRENCY', 'ABOGADO', 'DELETE', 0),
    ('ROLE', 'ABOGADO', 'POST', 0),
    ('ROLE', 'ABOGADO', 'GET', 1),
    ('ROLE', 'ABOGADO', 'PATCH', 0),
    ('ROLE', 'ABOGADO', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'POST', 0),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'GET', 1),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'ABOGADO', 'DELETE', 0),
    ('SELECTION', 'ABOGADO', 'POST', 0),
    ('SELECTION', 'ABOGADO', 'GET', 1),
    ('SELECTION', 'ABOGADO', 'PATCH', 0),
    ('SELECTION', 'ABOGADO', 'DELETE', 0),
    ('SHOPPING-DEMAND-HISTORY', 'ABOGADO', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'ABOGADO', 'GET', 1),
    ('SHOPPING-DEMAND-HISTORY', 'ABOGADO', 'PATCH', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ABOGADO',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'ABOGADO', 'POST', 0),
    ('SHOPPINGHISTORY', 'ABOGADO', 'GET', 1),
    ('SHOPPINGHISTORY', 'ABOGADO', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'ABOGADO', 'DELETE', 0),
    ('STATE', 'ABOGADO', 'POST', 0),
    ('STATE', 'ABOGADO', 'GET', 1),
    ('STATE', 'ABOGADO', 'PATCH', 0),
    ('STATE', 'ABOGADO', 'DELETE', 0),
    ('STATUS', 'ABOGADO', 'POST', 0),
    ('STATUS', 'ABOGADO', 'GET', 1),
    ('STATUS', 'ABOGADO', 'PATCH', 0),
    ('STATUS', 'ABOGADO', 'DELETE', 0),
    ('SUBCATEGORY', 'ABOGADO', 'POST', 0),
    ('SUBCATEGORY', 'ABOGADO', 'GET', 1),
    ('SUBCATEGORY', 'ABOGADO', 'PATCH', 0),
    ('SUBCATEGORY', 'ABOGADO', 'DELETE', 0),
    ('USER', 'ABOGADO', 'POST', 0),
    ('USER', 'ABOGADO', 'GET', 1),
    ('USER', 'ABOGADO', 'PATCH', 0),
    ('USER', 'ABOGADO', 'DELETE', 0),
    ('USERSBUYED', 'ABOGADO', 'POST', 0),
    ('USERSBUYED', 'ABOGADO', 'GET', 1),
    ('USERSBUYED', 'ABOGADO', 'PATCH', 0),
    ('USERSBUYED', 'ABOGADO', 'DELETE', 0),
    ('WHITE-LIST', 'ABOGADO', 'POST', 0),
    ('WHITE-LIST', 'ABOGADO', 'GET', 1),
    ('WHITE-LIST', 'ABOGADO', 'PATCH', 0),
    ('WHITE-LIST', 'ABOGADO', 'DELETE', 0),
    ('PQRS', 'ABOGADO', 'POST', 0),
    ('PQRS', 'ABOGADO', 'GET', 1),
    ('PQRS', 'ABOGADO', 'PATCH', 0),
    ('PQRS', 'ABOGADO', 'DELETE', 0),
    ('BUYER', 'OPERATIVO', 'POST', 1),
    ('BUYER', 'OPERATIVO', 'GET', 1),
    ('BUYER', 'OPERATIVO', 'PATCH', 1),
    ('BUYER', 'OPERATIVO', 'DELETE', 1),
    ('BD-PRICES', 'OPERATIVO', 'POST', 1),
    ('BD-PRICES', 'OPERATIVO', 'GET', 1),
    ('BD-PRICES', 'OPERATIVO', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'POST', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'GET', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'OPERATIVO', 'DELETE', 1),
    ('CATEGORY', 'OPERATIVO', 'POST', 0),
    ('CATEGORY', 'OPERATIVO', 'GET', 1),
    ('CATEGORY', 'OPERATIVO', 'PATCH', 0),
    ('CATEGORY', 'OPERATIVO', 'DELETE', 0),
    ('CITY', 'OPERATIVO', 'POST', 1),
    ('CITY', 'OPERATIVO', 'GET', 1),
    ('CITY', 'OPERATIVO', 'PATCH', 1),
    ('CITY', 'OPERATIVO', 'DELETE', 1),
    ('COMPANY', 'OPERATIVO', 'POST', 1),
    ('COMPANY', 'OPERATIVO', 'GET', 1),
    ('COMPANY', 'OPERATIVO', 'PATCH', 1),
    ('COMPANY', 'OPERATIVO', 'DELETE', 1),
    ('COUNTRY', 'OPERATIVO', 'POST', 1),
    ('COUNTRY', 'OPERATIVO', 'GET', 1),
    ('COUNTRY', 'OPERATIVO', 'PATCH', 1),
    ('COUNTRY', 'OPERATIVO', 'DELETE', 1),
    ('CREDENTIALS', 'OPERATIVO', 'POST', 1),
    ('CREDENTIALS', 'OPERATIVO', 'GET', 1),
    ('CREDENTIALS', 'OPERATIVO', 'PATCH', 1),
    ('CREDENTIALS', 'OPERATIVO', 'DELETE', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'POST', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'GET', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'PATCH', 1),
    ('DATABASE-TYPE', 'OPERATIVO', 'DELETE', 1),
    ('DEMAND', 'OPERATIVO', 'POST', 1),
    ('DEMAND', 'OPERATIVO', 'GET', 1),
    ('DEMAND', 'OPERATIVO', 'PATCH', 0),
    ('DEMAND', 'OPERATIVO', 'DELETE', 0),
    ('ELEMENT', 'OPERATIVO', 'POST', 1),
    ('ELEMENT', 'OPERATIVO', 'GET', 1),
    ('ELEMENT', 'OPERATIVO', 'PATCH', 1),
    ('ELEMENT', 'OPERATIVO', 'DELETE', 1),
    ('EMPLOYEE', 'OPERATIVO', 'POST', 0),
    ('EMPLOYEE', 'OPERATIVO', 'GET', 1),
    ('EMPLOYEE', 'OPERATIVO', 'PATCH', 0),
    ('EMPLOYEE', 'OPERATIVO', 'DELETE', 0),
    ('ERROR-LOG', 'OPERATIVO', 'POST', 0),
    ('ERROR-LOG', 'OPERATIVO', 'GET', 0),
    ('ERROR-LOG', 'OPERATIVO', 'PATCH', 0),
    ('ERROR-LOG', 'OPERATIVO', 'DELETE', 0),
    ('FAQ', 'OPERATIVO', 'POST', 1),
    ('FAQ', 'OPERATIVO', 'GET', 1),
    ('FAQ', 'OPERATIVO', 'PATCH', 1),
    ('FAQ', 'OPERATIVO', 'DELETE', 1),
    ('GENDER', 'OPERATIVO', 'POST', 1),
    ('GENDER', 'OPERATIVO', 'GET', 1),
    ('GENDER', 'OPERATIVO', 'PATCH', 1),
    ('GENDER', 'OPERATIVO', 'DELETE', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'POST', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'GET', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'PATCH', 1),
    ('IDENT-DOCUMENT', 'OPERATIVO', 'DELETE', 1),
    ('OBJECT', 'OPERATIVO', 'POST', 0),
    ('OBJECT', 'OPERATIVO', 'GET', 0),
    ('OBJECT', 'OPERATIVO', 'PATCH', 0),
    ('OBJECT', 'OPERATIVO', 'DELETE', 0),
    ('PERSON', 'OPERATIVO', 'POST', 1),
    ('PERSON', 'OPERATIVO', 'GET', 1),
    ('PERSON', 'OPERATIVO', 'PATCH', 1),
    ('PERSON', 'OPERATIVO', 'DELETE', 1),
    ('PLAN', 'OPERATIVO', 'POST', 1),
    ('PLAN', 'OPERATIVO', 'GET', 1),
    ('PLAN', 'OPERATIVO', 'PATCH', 1),
    ('PLAN', 'OPERATIVO', 'DELETE', 1),
    ('POLITIC', 'OPERATIVO', 'POST', 1),
    ('POLITIC', 'OPERATIVO', 'GET', 1),
    ('POLITIC', 'OPERATIVO', 'PATCH', 1),
    ('POLITIC', 'OPERATIVO', 'DELETE', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'POST', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'GET', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'PATCH', 1),
    ('POLITIC-BODY', 'OPERATIVO', 'DELETE', 1),
    ('POLITICSACCEPTED', 'OPERATIVO', 'POST', 0),
    ('POLITICSACCEPTED', 'OPERATIVO', 'GET', 1),
    ('POLITICSACCEPTED', 'OPERATIVO', 'PATCH', 0),
    ('POLITICSACCEPTED', 'OPERATIVO', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'POST', 1),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'GET', 1),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'PATCH', 1),
    ('REDEEMED-HISTORY', 'OPERATIVO', 'DELETE', 1),
    ('REQUEST', 'OPERATIVO', 'POST', 1),
    ('REQUEST', 'OPERATIVO', 'GET', 1),
    ('REQUEST', 'OPERATIVO', 'PATCH', 1),
    ('REQUEST', 'OPERATIVO', 'DELETE', 0),
    ('REQUIREMENT', 'OPERATIVO', 'POST', 1),
    ('REQUIREMENT', 'OPERATIVO', 'GET', 1),
    ('REQUIREMENT', 'OPERATIVO', 'PATCH', 1),
    ('REQUIREMENT', 'OPERATIVO', 'DELETE', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'POST', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'GET', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'PATCH', 1),
    ('REQUIREMENT-BODY', 'OPERATIVO', 'DELETE', 1),
    ('REWARD', 'OPERATIVO', 'POST', 1),
    ('REWARD', 'OPERATIVO', 'GET', 1),
    ('REWARD', 'OPERATIVO', 'PATCH', 0),
    ('REWARD', 'OPERATIVO', 'DELETE', 0),
    ('REWARD-CURRENCY', 'OPERATIVO', 'POST', 1),
    ('REWARD-CURRENCY', 'OPERATIVO', 'GET', 1),
    ('REWARD-CURRENCY', 'OPERATIVO', 'PATCH', 1),
    ('REWARD-CURRENCY', 'OPERATIVO', 'DELETE', 1),
    ('ROLE', 'OPERATIVO', 'POST', 1),
    ('ROLE', 'OPERATIVO', 'GET', 1),
    ('ROLE', 'OPERATIVO', 'PATCH', 1),
    ('ROLE', 'OPERATIVO', 'DELETE', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'POST', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'GET', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'PATCH', 1),
    ('ROLE-CREDENTIAL', 'OPERATIVO', 'DELETE', 1),
    ('SELECTION', 'OPERATIVO', 'POST', 1),
    ('SELECTION', 'OPERATIVO', 'GET', 1),
    ('SELECTION', 'OPERATIVO', 'PATCH', 1),
    ('SELECTION', 'OPERATIVO', 'DELETE', 1),
    (
        'SHOPPING-DEMAND-HISTORY',
        'OPERATIVO',
        'POST',
        0
    ),
    ('SHOPPING-DEMAND-HISTORY', 'OPERATIVO', 'GET', 1),
    (
        'SHOPPING-DEMAND-HISTORY',
        'OPERATIVO',
        'PATCH',
        0
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'OPERATIVO',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'POST', 0),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'GET', 1),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'OPERATIVO', 'DELETE', 0),
    ('STATE', 'OPERATIVO', 'POST', 1),
    ('STATE', 'OPERATIVO', 'GET', 1),
    ('STATE', 'OPERATIVO', 'PATCH', 1),
    ('STATE', 'OPERATIVO', 'DELETE', 1),
    ('STATUS', 'OPERATIVO', 'POST', 1),
    ('STATUS', 'OPERATIVO', 'GET', 1),
    ('STATUS', 'OPERATIVO', 'PATCH', 1),
    ('STATUS', 'OPERATIVO', 'DELETE', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'POST', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'GET', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'PATCH', 1),
    ('SUBCATEGORY', 'OPERATIVO', 'DELETE', 1),
    ('USER', 'OPERATIVO', 'POST', 1),
    ('USER', 'OPERATIVO', 'GET', 1),
    ('USER', 'OPERATIVO', 'PATCH', 1),
    ('USER', 'OPERATIVO', 'DELETE', 1),
    ('USERSBUYED', 'OPERATIVO', 'POST', 0),
    ('USERSBUYED', 'OPERATIVO', 'GET', 1),
    ('USERSBUYED', 'OPERATIVO', 'PATCH', 0),
    ('USERSBUYED', 'OPERATIVO', 'DELETE', 0),
    ('WHITE-LIST', 'OPERATIVO', 'POST', 0),
    ('WHITE-LIST', 'OPERATIVO', 'GET', 1),
    ('WHITE-LIST', 'OPERATIVO', 'PATCH', 0),
    ('WHITE-LIST', 'OPERATIVO', 'DELETE', 0),
    ('PQRS', 'OPERATIVO', 'POST', 1),
    ('PQRS', 'OPERATIVO', 'GET', 1),
    ('PQRS', 'OPERATIVO', 'PATCH', 1),
    ('PQRS', 'OPERATIVO', 'DELETE', 1),
    ('BUYER', 'ADMINISTRATIVO', 'POST', 1),
    ('BUYER', 'ADMINISTRATIVO', 'GET', 1),
    ('BUYER', 'ADMINISTRATIVO', 'PATCH', 1),
    ('BUYER', 'ADMINISTRATIVO', 'DELETE', 1),
    ('BD-PRICES', 'ADMINISTRATIVO', 'POST', 1),
    ('BD-PRICES', 'ADMINISTRATIVO', 'GET', 1),
    ('BD-PRICES', 'ADMINISTRATIVO', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'POST', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'GET', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'ADMINISTRATIVO', 'DELETE', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'POST', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'GET', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('CATEGORY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('CITY', 'ADMINISTRATIVO', 'POST', 1),
    ('CITY', 'ADMINISTRATIVO', 'GET', 1),
    ('CITY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('CITY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'POST', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'GET', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('COMPANY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'POST', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'GET', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('COUNTRY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'POST', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'GET', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'PATCH', 1),
    ('CREDENTIALS', 'ADMINISTRATIVO', 'DELETE', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'POST', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'GET', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('DATABASE-TYPE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'POST', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'GET', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'PATCH', 1),
    ('DEMAND', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'POST', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'GET', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ELEMENT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'POST', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'GET', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('EMPLOYEE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'POST', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'GET', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ERROR-LOG', 'ADMINISTRATIVO', 'DELETE', 1),
    ('FAQ', 'ADMINISTRATIVO', 'POST', 1),
    ('FAQ', 'ADMINISTRATIVO', 'GET', 1),
    ('FAQ', 'ADMINISTRATIVO', 'PATCH', 1),
    ('FAQ', 'ADMINISTRATIVO', 'DELETE', 1),
    ('GENDER', 'ADMINISTRATIVO', 'POST', 1),
    ('GENDER', 'ADMINISTRATIVO', 'GET', 1),
    ('GENDER', 'ADMINISTRATIVO', 'PATCH', 1),
    ('GENDER', 'ADMINISTRATIVO', 'DELETE', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'POST', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'GET', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('IDENT-DOCUMENT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'POST', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'GET', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('OBJECT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('PERSON', 'ADMINISTRATIVO', 'POST', 1),
    ('PERSON', 'ADMINISTRATIVO', 'GET', 1),
    ('PERSON', 'ADMINISTRATIVO', 'PATCH', 1),
    ('PERSON', 'ADMINISTRATIVO', 'DELETE', 1),
    ('PLAN', 'ADMINISTRATIVO', 'POST', 1),
    ('PLAN', 'ADMINISTRATIVO', 'GET', 1),
    ('PLAN', 'ADMINISTRATIVO', 'PATCH', 1),
    ('PLAN', 'ADMINISTRATIVO', 'DELETE', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'POST', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'GET', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'PATCH', 1),
    ('POLITIC', 'ADMINISTRATIVO', 'DELETE', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'POST', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'GET', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('POLITIC-BODY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('POLITICSACCEPTED', 'ADMINISTRATIVO', 'POST', 1),
    ('POLITICSACCEPTED', 'ADMINISTRATIVO', 'GET', 1),
    (
        'POLITICSACCEPTED',
        'ADMINISTRATIVO',
        'PATCH',
        1
    ),
    (
        'POLITICSACCEPTED',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('REDEEMED-HISTORY', 'ADMINISTRATIVO', 'POST', 1),
    ('REDEEMED-HISTORY', 'ADMINISTRATIVO', 'GET', 1),
    ('REDEEMED-HISTORY', 'ADMINISTRATIVO', 'PATCH', 1),
    (
        'REDEEMED-HISTORY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('REQUEST', 'ADMINISTRATIVO', 'POST', 1),
    ('REQUEST', 'ADMINISTRATIVO', 'GET', 1),
    ('REQUEST', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REQUEST', 'ADMINISTRATIVO', 'DELETE', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'POST', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'GET', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REQUIREMENT', 'ADMINISTRATIVO', 'DELETE', 1),
    ('REQUIREMENT-BODY', 'ADMINISTRATIVO', 'POST', 1),
    ('REQUIREMENT-BODY', 'ADMINISTRATIVO', 'GET', 1),
    ('REQUIREMENT-BODY', 'ADMINISTRATIVO', 'PATCH', 1),
    (
        'REQUIREMENT-BODY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('REWARD', 'ADMINISTRATIVO', 'POST', 1),
    ('REWARD', 'ADMINISTRATIVO', 'GET', 1),
    ('REWARD', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REWARD', 'ADMINISTRATIVO', 'DELETE', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'POST', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'GET', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('REWARD-CURRENCY', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ROLE', 'ADMINISTRATIVO', 'POST', 1),
    ('ROLE', 'ADMINISTRATIVO', 'GET', 1),
    ('ROLE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ROLE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'POST', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'GET', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'PATCH', 1),
    ('ROLE-CREDENTIAL', 'ADMINISTRATIVO', 'DELETE', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'POST', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'GET', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'PATCH', 1),
    ('SELECTION', 'ADMINISTRATIVO', 'DELETE', 1),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'POST',
        1
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'GET',
        1
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'PATCH',
        1
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('SHOPPINGHISTORY', 'ADMINISTRATIVO', 'POST', 1),
    ('SHOPPINGHISTORY', 'ADMINISTRATIVO', 'GET', 1),
    ('SHOPPINGHISTORY', 'ADMINISTRATIVO', 'PATCH', 1),
    (
        'SHOPPINGHISTORY',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('STATE', 'ADMINISTRATIVO', 'POST', 1),
    ('STATE', 'ADMINISTRATIVO', 'GET', 1),
    ('STATE', 'ADMINISTRATIVO', 'PATCH', 1),
    ('STATE', 'ADMINISTRATIVO', 'DELETE', 1),
    ('STATUS', 'ADMINISTRATIVO', 'POST', 1),
    ('STATUS', 'ADMINISTRATIVO', 'GET', 1),
    ('STATUS', 'ADMINISTRATIVO', 'PATCH', 1),
    ('STATUS', 'ADMINISTRATIVO', 'DELETE', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'POST', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'GET', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'PATCH', 1),
    ('SUBCATEGORY', 'ADMINISTRATIVO', 'DELETE', 1);

INSERT INTO
    role_permission
VALUES
    ('USER', 'ADMINISTRATIVO', 'POST', 1),
    ('USER', 'ADMINISTRATIVO', 'GET', 1),
    ('USER', 'ADMINISTRATIVO', 'PATCH', 1),
    ('USER', 'ADMINISTRATIVO', 'DELETE', 1),
    ('USERSBUYED', 'ADMINISTRATIVO', 'POST', 1),
    ('USERSBUYED', 'ADMINISTRATIVO', 'GET', 1),
    ('USERSBUYED', 'ADMINISTRATIVO', 'PATCH', 1),
    ('USERSBUYED', 'ADMINISTRATIVO', 'DELETE', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'POST', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'GET', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'PATCH', 1),
    ('WHITE-LIST', 'ADMINISTRATIVO', 'DELETE', 1),
    ('PQRS', 'ADMINISTRATIVO', 'POST', 1),
    ('PQRS', 'ADMINISTRATIVO', 'GET', 1),
    ('PQRS', 'ADMINISTRATIVO', 'PATCH', 1),
    ('PQRS', 'ADMINISTRATIVO', 'DELETE', 1),
    ('BUYER', 'BUYER', 'POST', 1),
    ('BUYER', 'BUYER', 'GET', 1),
    ('BUYER', 'BUYER', 'PATCH', 1),
    ('BUYER', 'BUYER', 'DELETE', 0),
    ('BD-PRICES', 'BUYER', 'POST', 1),
    ('BD-PRICES', 'BUYER', 'GET', 1),
    ('BD-PRICES', 'BUYER', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'BUYER', 'POST', 1),
    ('BUYERCREDENTIAL', 'BUYER', 'GET', 0),
    ('BUYERCREDENTIAL', 'BUYER', 'PATCH', 1),
    ('BUYERCREDENTIAL', 'BUYER', 'DELETE', 0),
    ('CATEGORY', 'BUYER', 'POST', 0),
    ('CATEGORY', 'BUYER', 'GET', 1),
    ('CATEGORY', 'BUYER', 'PATCH', 0),
    ('CATEGORY', 'BUYER', 'DELETE', 0),
    ('CITY', 'BUYER', 'POST', 0),
    ('CITY', 'BUYER', 'GET', 1),
    ('CITY', 'BUYER', 'PATCH', 0),
    ('CITY', 'BUYER', 'DELETE', 0),
    ('COMPANY', 'BUYER', 'POST', 1),
    ('COMPANY', 'BUYER', 'GET', 0),
    ('COMPANY', 'BUYER', 'PATCH', 1),
    ('COMPANY', 'BUYER', 'DELETE', 0),
    ('COUNTRY', 'BUYER', 'POST', 0),
    ('COUNTRY', 'BUYER', 'GET', 1),
    ('COUNTRY', 'BUYER', 'PATCH', 0),
    ('COUNTRY', 'BUYER', 'DELETE', 0),
    ('CREDENTIALS', 'BUYER', 'POST', 0),
    ('CREDENTIALS', 'BUYER', 'GET', 0),
    ('CREDENTIALS', 'BUYER', 'PATCH', 0),
    ('CREDENTIALS', 'BUYER', 'DELETE', 0),
    ('DATABASE-TYPE', 'BUYER', 'POST', 0),
    ('DATABASE-TYPE', 'BUYER', 'GET', 1),
    ('DATABASE-TYPE', 'BUYER', 'PATCH', 0),
    ('DATABASE-TYPE', 'BUYER', 'DELETE', 0),
    ('DEMAND', 'BUYER', 'POST', 0),
    ('DEMAND', 'BUYER', 'GET', 0),
    ('DEMAND', 'BUYER', 'PATCH', 0),
    ('DEMAND', 'BUYER', 'DELETE', 0),
    ('ELEMENT', 'BUYER', 'POST', 0),
    ('ELEMENT', 'BUYER', 'GET', 1),
    ('ELEMENT', 'BUYER', 'PATCH', 0),
    ('ELEMENT', 'BUYER', 'DELETE', 0),
    ('EMPLOYEE', 'BUYER', 'POST', 0),
    ('EMPLOYEE', 'BUYER', 'GET', 0),
    ('EMPLOYEE', 'BUYER', 'PATCH', 0),
    ('EMPLOYEE', 'BUYER', 'DELETE', 0),
    ('ERROR-LOG', 'BUYER', 'POST', 0),
    ('ERROR-LOG', 'BUYER', 'GET', 0),
    ('ERROR-LOG', 'BUYER', 'PATCH', 0),
    ('ERROR-LOG', 'BUYER', 'DELETE', 0),
    ('FAQ', 'BUYER', 'POST', 0),
    ('FAQ', 'BUYER', 'GET', 1),
    ('FAQ', 'BUYER', 'PATCH', 0),
    ('FAQ', 'BUYER', 'DELETE', 0),
    ('GENDER', 'BUYER', 'POST', 0),
    ('GENDER', 'BUYER', 'GET', 1),
    ('GENDER', 'BUYER', 'PATCH', 0),
    ('GENDER', 'BUYER', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'BUYER', 'POST', 0),
    ('IDENT-DOCUMENT', 'BUYER', 'GET', 1),
    ('IDENT-DOCUMENT', 'BUYER', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'BUYER', 'DELETE', 0),
    ('OBJECT', 'BUYER', 'POST', 0),
    ('OBJECT', 'BUYER', 'GET', 0),
    ('OBJECT', 'BUYER', 'PATCH', 0),
    ('OBJECT', 'BUYER', 'DELETE', 0),
    ('PERSON', 'BUYER', 'POST', 0),
    ('PERSON', 'BUYER', 'GET', 0),
    ('PERSON', 'BUYER', 'PATCH', 0),
    ('PERSON', 'BUYER', 'DELETE', 0),
    ('PLAN', 'BUYER', 'POST', 0),
    ('PLAN', 'BUYER', 'GET', 0),
    ('PLAN', 'BUYER', 'PATCH', 0),
    ('PLAN', 'BUYER', 'DELETE', 0),
    ('POLITIC', 'BUYER', 'POST', 0),
    ('POLITIC', 'BUYER', 'GET', 0),
    ('POLITIC', 'BUYER', 'PATCH', 0),
    ('POLITIC', 'BUYER', 'DELETE', 0),
    ('POLITIC-BODY', 'BUYER', 'POST', 0),
    ('POLITIC-BODY', 'BUYER', 'GET', 0),
    ('POLITIC-BODY', 'BUYER', 'PATCH', 0),
    ('POLITIC-BODY', 'BUYER', 'DELETE', 0),
    ('POLITICSACCEPTED', 'BUYER', 'POST', 1),
    ('POLITICSACCEPTED', 'BUYER', 'GET', 0),
    ('POLITICSACCEPTED', 'BUYER', 'PATCH', 0),
    ('POLITICSACCEPTED', 'BUYER', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'POST', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'GET', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'BUYER', 'DELETE', 0),
    ('REQUEST', 'BUYER', 'POST', 1),
    ('REQUEST', 'BUYER', 'GET', 1),
    ('REQUEST', 'BUYER', 'PATCH', 0),
    ('REQUEST', 'BUYER', 'DELETE', 0),
    ('REQUIREMENT', 'BUYER', 'POST', 0),
    ('REQUIREMENT', 'BUYER', 'GET', 1),
    ('REQUIREMENT', 'BUYER', 'PATCH', 0),
    ('REQUIREMENT', 'BUYER', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'BUYER', 'POST', 0),
    ('REQUIREMENT-BODY', 'BUYER', 'GET', 1),
    ('REQUIREMENT-BODY', 'BUYER', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'BUYER', 'DELETE', 0),
    ('REWARD', 'BUYER', 'POST', 0),
    ('REWARD', 'BUYER', 'GET', 0),
    ('REWARD', 'BUYER', 'PATCH', 0),
    ('REWARD', 'BUYER', 'DELETE', 0),
    ('REWARD-CURRENCY', 'BUYER', 'POST', 0),
    ('REWARD-CURRENCY', 'BUYER', 'GET', 0),
    ('REWARD-CURRENCY', 'BUYER', 'PATCH', 0),
    ('REWARD-CURRENCY', 'BUYER', 'DELETE', 0),
    ('ROLE', 'BUYER', 'POST', 0),
    ('ROLE', 'BUYER', 'GET', 0),
    ('ROLE', 'BUYER', 'PATCH', 0),
    ('ROLE', 'BUYER', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'POST', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'GET', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'BUYER', 'DELETE', 0),
    ('SELECTION', 'BUYER', 'POST', 1),
    ('SELECTION', 'BUYER', 'GET', 1),
    ('SELECTION', 'BUYER', 'PATCH', 0),
    ('SELECTION', 'BUYER', 'DELETE', 1),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'POST', 0),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'GET', 0),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'PATCH', 0),
    ('SHOPPING-DEMAND-HISTORY', 'BUYER', 'DELETE', 0),
    ('SHOPPINGHISTORY', 'BUYER', 'POST', 1),
    ('SHOPPINGHISTORY', 'BUYER', 'GET', 1),
    ('SHOPPINGHISTORY', 'BUYER', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'BUYER', 'DELETE', 0),
    ('STATE', 'BUYER', 'POST', 0),
    ('STATE', 'BUYER', 'GET', 1),
    ('STATE', 'BUYER', 'PATCH', 0),
    ('STATE', 'BUYER', 'DELETE', 0),
    ('STATUS', 'BUYER', 'POST', 0),
    ('STATUS', 'BUYER', 'GET', 1),
    ('STATUS', 'BUYER', 'PATCH', 0),
    ('STATUS', 'BUYER', 'DELETE', 0),
    ('SUBCATEGORY', 'BUYER', 'POST', 0),
    ('SUBCATEGORY', 'BUYER', 'GET', 1),
    ('SUBCATEGORY', 'BUYER', 'PATCH', 0),
    ('SUBCATEGORY', 'BUYER', 'DELETE', 0),
    ('USER', 'BUYER', 'POST', 0),
    ('USER', 'BUYER', 'GET', 0),
    ('USER', 'BUYER', 'PATCH', 0),
    ('USER', 'BUYER', 'DELETE', 0),
    ('USERSBUYED', 'BUYER', 'POST', 0),
    ('USERSBUYED', 'BUYER', 'GET', 0),
    ('USERSBUYED', 'BUYER', 'PATCH', 0),
    ('USERSBUYED', 'BUYER', 'DELETE', 0),
    ('WHITE-LIST', 'BUYER', 'POST', 0),
    ('WHITE-LIST', 'BUYER', 'GET', 0),
    ('WHITE-LIST', 'BUYER', 'PATCH', 0),
    ('WHITE-LIST', 'BUYER', 'DELETE', 0),
    ('PQRS', 'BUYER', 'POST', 0),
    ('PQRS', 'BUYER', 'GET', 1),
    ('PQRS', 'BUYER', 'PATCH', 0),
    ('PQRS', 'BUYER', 'DELETE', 0);

INSERT INTO
    role_permission
VALUES
    ('AUTH', 'CATALOGUE', 'POST', 1),
    ('AUTH', 'CATALOGUE', 'PATCH', 1),
    ('AUTH', 'CONTROL', 'POST', 1),
    ('AUTH', 'CONTROL', 'PATCH', 1),
    ('AUTH', 'PLUS', 'POST', 1),
    ('AUTH', 'PLUS', 'PATCH', 1),
    ('AUTH', 'PREMIUM', 'POST', 1),
    ('AUTH', 'PREMIUM', 'PATCH', 1),
    ('AUTH', 'BUYER', 'POST', 1),
    ('AUTH', 'BUYER', 'PATCH', 1),
    ('AUTH', 'ADMINISTRATIVO', 'POST', 1),
    ('AUTH', 'ADMINISTRATIVO', 'PATCH', 1),
    ('AUTH', 'ABOGADO', 'POST', 1),
    ('AUTH', 'ABOGADO', 'PATCH', 1),
    ('AUTH', 'OPERATIVO', 'POST', 1),
    ('AUTH', 'OPERATIVO', 'PATCH', 1),
    ('BUYER', 'CATALOGUE', 'POST', 1),
    ('BUYER', 'CATALOGUE', 'GET', 0),
    ('BUYER', 'CATALOGUE', 'PATCH', 0),
    ('BUYER', 'CATALOGUE', 'DELETE', 0),
    ('BD-PRICES', 'CATALOGUE', 'POST', 0),
    ('BD-PRICES', 'CATALOGUE', 'GET', 0),
    ('BD-PRICES', 'CATALOGUE', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'CATALOGUE', 'POST', 1),
    ('BUYERCREDENTIAL', 'CATALOGUE', 'GET', 0),
    ('BUYERCREDENTIAL', 'CATALOGUE', 'PATCH', 0),
    ('BUYERCREDENTIAL', 'CATALOGUE', 'DELETE', 0),
    ('CATEGORY', 'CATALOGUE', 'POST', 0),
    ('CATEGORY', 'CATALOGUE', 'GET', 1),
    ('CATEGORY', 'CATALOGUE', 'PATCH', 0),
    ('CATEGORY', 'CATALOGUE', 'DELETE', 0),
    ('CITY', 'CATALOGUE', 'POST', 0),
    ('CITY', 'CATALOGUE', 'GET', 1),
    ('CITY', 'CATALOGUE', 'PATCH', 0),
    ('CITY', 'CATALOGUE', 'DELETE', 0),
    ('COMPANY', 'CATALOGUE', 'POST', 1),
    ('COMPANY', 'CATALOGUE', 'GET', 1),
    ('COMPANY', 'CATALOGUE', 'PATCH', 0),
    ('COMPANY', 'CATALOGUE', 'DELETE', 0),
    ('COUNTRY', 'CATALOGUE', 'POST', 0),
    ('COUNTRY', 'CATALOGUE', 'GET', 1),
    ('COUNTRY', 'CATALOGUE', 'PATCH', 0),
    ('COUNTRY', 'CATALOGUE', 'DELETE', 0),
    ('CREDENTIALS', 'CATALOGUE', 'POST', 1),
    ('CREDENTIALS', 'CATALOGUE', 'GET', 1),
    ('CREDENTIALS', 'CATALOGUE', 'PATCH', 1),
    ('CREDENTIALS', 'CATALOGUE', 'DELETE', 0),
    ('DATABASE-TYPE', 'CATALOGUE', 'POST', 0),
    ('DATABASE-TYPE', 'CATALOGUE', 'GET', 0),
    ('DATABASE-TYPE', 'CATALOGUE', 'PATCH', 0),
    ('DATABASE-TYPE', 'CATALOGUE', 'DELETE', 0),
    ('DEMAND', 'CATALOGUE', 'POST', 0),
    ('DEMAND', 'CATALOGUE', 'GET', 0),
    ('DEMAND', 'CATALOGUE', 'PATCH', 0),
    ('DEMAND', 'CATALOGUE', 'DELETE', 0),
    ('ELEMENT', 'CATALOGUE', 'POST', 0),
    ('ELEMENT', 'CATALOGUE', 'GET', 1),
    ('ELEMENT', 'CATALOGUE', 'PATCH', 0),
    ('ELEMENT', 'CATALOGUE', 'DELETE', 0),
    ('EMPLOYEE', 'CATALOGUE', 'POST', 0),
    ('EMPLOYEE', 'CATALOGUE', 'GET', 1),
    ('EMPLOYEE', 'CATALOGUE', 'PATCH', 0),
    ('EMPLOYEE', 'CATALOGUE', 'DELETE', 0),
    ('ERROR-LOG', 'CATALOGUE', 'POST', 0),
    ('ERROR-LOG', 'CATALOGUE', 'GET', 0),
    ('ERROR-LOG', 'CATALOGUE', 'PATCH', 0),
    ('ERROR-LOG', 'CATALOGUE', 'DELETE', 0),
    ('FAQ', 'CATALOGUE', 'POST', 0),
    ('FAQ', 'CATALOGUE', 'GET', 1),
    ('FAQ', 'CATALOGUE', 'PATCH', 0),
    ('FAQ', 'CATALOGUE', 'DELETE', 0),
    ('GENDER', 'CATALOGUE', 'POST', 0),
    ('GENDER', 'CATALOGUE', 'GET', 1),
    ('GENDER', 'CATALOGUE', 'PATCH', 0),
    ('GENDER', 'CATALOGUE', 'DELETE', 0),
    ('IDENT-DOCUMENT', 'CATALOGUE', 'POST', 0),
    ('IDENT-DOCUMENT', 'CATALOGUE', 'GET', 1),
    ('IDENT-DOCUMENT', 'CATALOGUE', 'PATCH', 0),
    ('IDENT-DOCUMENT', 'CATALOGUE', 'DELETE', 0),
    ('OBJECT', 'CATALOGUE', 'POST', 0),
    ('OBJECT', 'CATALOGUE', 'GET', 0),
    ('OBJECT', 'CATALOGUE', 'PATCH', 0),
    ('OBJECT', 'CATALOGUE', 'DELETE', 0),
    ('PERSON', 'CATALOGUE', 'POST', 1),
    ('PERSON', 'CATALOGUE', 'GET', 1),
    ('PERSON', 'CATALOGUE', 'PATCH', 1),
    ('PERSON', 'CATALOGUE', 'DELETE', 0),
    ('PLAN', 'CATALOGUE', 'POST', 0),
    ('PLAN', 'CATALOGUE', 'GET', 1),
    ('PLAN', 'CATALOGUE', 'PATCH', 0),
    ('PLAN', 'CATALOGUE', 'DELETE', 0),
    ('POLITIC', 'CATALOGUE', 'POST', 1),
    ('POLITIC', 'CATALOGUE', 'GET', 1),
    ('POLITIC', 'CATALOGUE', 'PATCH', 0),
    ('POLITIC', 'CATALOGUE', 'DELETE', 0),
    ('POLITIC-BODY', 'CATALOGUE', 'POST', 0),
    ('POLITIC-BODY', 'CATALOGUE', 'GET', 1),
    ('POLITIC-BODY', 'CATALOGUE', 'PATCH', 0),
    ('POLITIC-BODY', 'CATALOGUE', 'DELETE', 0),
    ('POLITICSACCEPTED', 'CATALOGUE', 'POST', 1),
    ('POLITICSACCEPTED', 'CATALOGUE', 'GET', 1),
    ('POLITICSACCEPTED', 'CATALOGUE', 'PATCH', 0),
    ('POLITICSACCEPTED', 'CATALOGUE', 'DELETE', 0),
    ('REDEEMED-HISTORY', 'CATALOGUE', 'POST', 0),
    ('REDEEMED-HISTORY', 'CATALOGUE', 'GET', 0),
    ('REDEEMED-HISTORY', 'CATALOGUE', 'PATCH', 0),
    ('REDEEMED-HISTORY', 'CATALOGUE', 'DELETE', 0),
    ('REQUEST', 'CATALOGUE', 'POST', 1),
    ('REQUEST', 'CATALOGUE', 'GET', 0),
    ('REQUEST', 'CATALOGUE', 'PATCH', 0),
    ('REQUEST', 'CATALOGUE', 'DELETE', 0),
    ('REQUIREMENT', 'CATALOGUE', 'POST', 0),
    ('REQUIREMENT', 'CATALOGUE', 'GET', 1),
    ('REQUIREMENT', 'CATALOGUE', 'PATCH', 0),
    ('REQUIREMENT', 'CATALOGUE', 'DELETE', 0),
    ('REQUIREMENT-BODY', 'CATALOGUE', 'POST', 0),
    ('REQUIREMENT-BODY', 'CATALOGUE', 'GET', 1),
    ('REQUIREMENT-BODY', 'CATALOGUE', 'PATCH', 0),
    ('REQUIREMENT-BODY', 'CATALOGUE', 'DELETE', 0),
    ('REWARD', 'CATALOGUE', 'POST', 0),
    ('REWARD', 'CATALOGUE', 'GET', 0),
    ('REWARD', 'CATALOGUE', 'PATCH', 0),
    ('REWARD', 'CATALOGUE', 'DELETE', 0),
    ('REWARD-CURRENCY', 'CATALOGUE', 'POST', 0),
    ('REWARD-CURRENCY', 'CATALOGUE', 'GET', 0),
    ('REWARD-CURRENCY', 'CATALOGUE', 'PATCH', 0),
    ('REWARD-CURRENCY', 'CATALOGUE', 'DELETE', 0),
    ('ROLE', 'CATALOGUE', 'POST', 0),
    ('ROLE', 'CATALOGUE', 'GET', 0),
    ('ROLE', 'CATALOGUE', 'PATCH', 0),
    ('ROLE', 'CATALOGUE', 'DELETE', 0),
    ('ROLE-CREDENTIAL', 'CATALOGUE', 'POST', 0),
    ('ROLE-CREDENTIAL', 'CATALOGUE', 'GET', 0),
    ('ROLE-CREDENTIAL', 'CATALOGUE', 'PATCH', 0),
    ('ROLE-CREDENTIAL', 'CATALOGUE', 'DELETE', 0),
    ('SELECTION', 'CATALOGUE', 'POST', 0),
    ('SELECTION', 'CATALOGUE', 'GET', 1),
    ('SELECTION', 'CATALOGUE', 'PATCH', 0),
    ('SELECTION', 'CATALOGUE', 'DELETE', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'CATALOGUE',
        'POST',
        0
    ),
    ('SHOPPING-DEMAND-HISTORY', 'CATALOGUE', 'GET', 0),
    (
        'SHOPPING-DEMAND-HISTORY',
        'CATALOGUE',
        'PATCH',
        0
    ),
    (
        'SHOPPING-DEMAND-HISTORY',
        'CATALOGUE',
        'DELETE',
        0
    ),
    ('SHOPPINGHISTORY', 'CATALOGUE', 'POST', 0),
    ('SHOPPINGHISTORY', 'CATALOGUE', 'GET', 0),
    ('SHOPPINGHISTORY', 'CATALOGUE', 'PATCH', 0),
    ('SHOPPINGHISTORY', 'CATALOGUE', 'DELETE', 0),
    ('STATE', 'CATALOGUE', 'POST', 0),
    ('STATE', 'CATALOGUE', 'GET', 1),
    ('STATE', 'CATALOGUE', 'PATCH', 0),
    ('STATE', 'CATALOGUE', 'DELETE', 0),
    ('SPONSORCODE', 'CATALOGUE', 'POST', 1),
    ('SPONSORCODE', 'CATALOGUE', 'GET', 0),
    ('SPONSORCODE', 'CATALOGUE', 'PATCH', 0),
    ('SPONSORCODE', 'CATALOGUE', 'DELETE', 0),
    ('SPONSORCODE', 'OPERATIVO', 'POST', 1),
    ('SPONSORCODE', 'OPERATIVO', 'GET', 1),
    ('SPONSORCODE', 'OPERATIVO', 'PATCH', 1),
    ('SPONSORCODE', 'OPERATIVO', 'DELETE', 1),
    ('STATUS', 'CATALOGUE', 'POST', 0),
    ('STATUS', 'CATALOGUE', 'GET', 1),
    ('STATUS', 'CATALOGUE', 'PATCH', 0),
    ('STATUS', 'CATALOGUE', 'DELETE', 0),
    ('SUBCATEGORY', 'CATALOGUE', 'POST', 0),
    ('SUBCATEGORY', 'CATALOGUE', 'GET', 1),
    ('SUBCATEGORY', 'CATALOGUE', 'PATCH', 0),
    ('SUBCATEGORY', 'CATALOGUE', 'DELETE', 0),
    ('USER', 'CATALOGUE', 'POST', 1),
    ('USER', 'CATALOGUE', 'GET', 0),
    ('USER', 'CATALOGUE', 'PATCH', 0),
    ('USER', 'CATALOGUE', 'DELETE', 0),
    ('USERSBUYED', 'CATALOGUE', 'POST', 0),
    ('USERSBUYED', 'CATALOGUE', 'GET', 0),
    ('USERSBUYED', 'CATALOGUE', 'PATCH', 0),
    ('USERSBUYED', 'CATALOGUE', 'DELETE', 0),
    ('WHITE-LIST', 'CATALOGUE', 'POST', 0),
    ('WHITE-LIST', 'CATALOGUE', 'GET', 0),
    ('WHITE-LIST', 'CATALOGUE', 'PATCH', 0),
    ('WHITE-LIST', 'CATALOGUE', 'DELETE', 0),
    ('PQRS', 'CATALOGUE', 'POST', 0),
    ('PQRS', 'CATALOGUE', 'GET', 1),
    ('PQRS', 'CATALOGUE', 'PATCH', 0),
    ('PQRS', 'CATALOGUE', 'DELETE', 0),
    ('PAYMENTS-RECEIPTS', 'ADMINISTRATIVO', 'POST', 1),
    ('PAYMENTS-RECEIPTS', 'ADMINISTRATIVO', 'GET', 1),
    ('PAYMENTS-RECEIPTS', 'OPERATIVO', 'POST', 1),
    ('PAYMENTS-RECEIPTS', 'OPERATIVO', 'GET', 1),
    ('PAYMENTS-RECEIPTS', 'PREMIUM', 'POST', 1),
    ('PAYMENTS-RECEIPTS', 'PREMIUM', 'GET', 1),
    ('PAYMENTS-RECEIPTS', 'PLUS', 'POST', 1),
    ('PAYMENTS-RECEIPTS', 'PLUS', 'GET', 1),
    ('PAYMENTS-RECEIPTS', 'CONTROL', 'POST', 1),
    ('PAYMENTS-RECEIPTS', 'CONTROL', 'GET', 1),
    ('PAYMENTS-RECEIPTS', 'BUYER', 'POST', 1),
    ('PAYMENTS-RECEIPTS', 'BUYER', 'GET', 1);

INSERT INTO
    role_permission
VALUES
    (
        'EMPLOYEECREDENTIAL',
        'ADMINISTRATIVO',
        'POST',
        1
    ),
    ('EMPLOYEECREDENTIAL', 'ADMINISTRATIVO', 'GET', 1),
    (
        'EMPLOYEECREDENTIAL',
        'ADMINISTRATIVO',
        'PATCH',
        1
    ),
    (
        'EMPLOYEECREDENTIAL',
        'ADMINISTRATIVO',
        'DELETE',
        1
    ),
    ('PAYOUT', 'PLUS', 'GET', 1),
    ('PAYOUT', 'PREMIUM', 'GET', 1);

INSERT INTO
    [dbo].[politic] ([politicName])
VALUES
    ('GENERAL-USER'),
    ('GENERAL-BUYER'),
    ('PREMIUM-USER'),
    ('PLUS-USER'),
    ('CONTROL-USER'),
    ('DATA-USER'),
    ('DATA-CONTROL'),
    ('DATA-PLUS'),
    ('DATA-PREMIUM'),
    ('MOVISTAR-USER');

INSERT INTO
    [dbo].[politic_body] (
        [politicText],
        [politicVersion],
        [politicState],
        [politicId]
    )
VALUES
    ('politics/GENERAL-USER.pdf', '1.0', 1, 1),
    ('politics/GENERAL-BUYER.pdf', '1.0', 1, 2),
    ('politics/PREMIUM-USER.pdf', '1.0', 1, 3),
    ('politics/PLUS-USER.pdf', '1.0', 1, 4),
    ('politics/CONTROL-USER.pdf', '1.0', 1, 5),
    ('politics/DATA-USER.pdf', '1.0', 1, 6),
    ('politics/DATA-CONTROL.pdf', '1.0', 1, 7),
    ('politics/DATA-PLUS.pdf', '1.0', 1, 8),
    ('politics/DATA-PREMIUM.pdf', '1.0', 1, 9),
    (
        'politics/MOVISTAR-USER.pdf',
        '1.0',
        1,
        10
    );

/* INSERT INTO [dbo].[sponsor_code] ([sponsorCode], [documentNumber], [companyId])
 VALUES
 ('MOV0123456', '1234567890', '0e76433e-f36b-1410-81c2-009e18c9ad57'); */
/* INSERT INTO
 [dbo].[company_competence] (
 [companyCompetenceId],
 [competenceId],
 [companyId]
 )
 VALUES
 (
 '3934433e-f36b-1410-87a6-0065356853cd',
 'c075433e-f36b-1410-81c2-009e18c9ad57',
 '0e76433e-f36b-1410-81c2-009e18c9ad57'
 ),
 (
 '3c34433e-f36b-1410-87a6-0065356853cd',
 'c675433e-f36b-1410-81c2-009e18c9ad57',
 '0e76433e-f36b-1410-81c2-009e18c9ad57'
 ); */
/* INSERT INTO
 [dbo].[bd_price] (
 [bdPriceMinUsers],
 [bdPriceMaxUsers],
 [bdPriceValue],
 [bdPriceActive],
 [databaseId]
 )
 VALUES
 (0, 100, 1000, 1, 1),
 (101, 500, 2000, 1, 1),
 (501, 1000, 3000, 1, 1),
 (1001, 5000, 4000, 1, 1),
 (5001, 10000, 5000, 1, 1),
 (10001, 1000000, 6000, 1, 1),
 (0, 100, 1100, 1, 2),
 (101, 500, 2100, 1, 2),
 (501, 1000, 3100, 1, 2),
 (1001, 5000, 4100, 1, 2),
 (5001, 10000, 5100, 1, 2),
 (10001, 1000000, 6100, 1, 2); */
INSERT INTO
    dbo.company(
        companyId,
        companyBussinesName,
        companyComertialName,
        companyNit,
        companyPhone,
        companyEmail,
        companyLogoPath,
        cityId,
        directRemitent,
        companyUsed
    )
VALUES
    (
        '00000000-0000-0000-0000-000000000000',
        'Ofuscated',
        'Ofuscated',
        '000000000',
        '0000000000',
        'ofuscated@ofuscated.ofuscated',
        'null',
        1,
        0,
        0
    )
insert into
    package_currency(
        packageCurrencyName,
        packageCurrencyValue,
        packageCurrencyActive,
        packageQuantity,
        packageVersion
    )
VALUES
    ('BASIC', 0, 1, 2, '1.0'),
    ('STANDARD', 20000, 1, 1, '1.0'),
    ('CONTROL3', 40000, 1, 3, '1.0'),
    ('CONTROL5', 60000, 1, 5, '1.0');